var searchData=
[
  ['ebusy_20errors_0',['EBUSY errors',['../error_handling.html#error_ebusy',1,'']]],
  ['enable_20libfuzzer_1',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['enable_20operation_20tracking_2',['Enable operation tracking',['../tool-optrack.html#autotoc_md31',1,'']]],
  ['enabling_20commit_20level_20durability_3',['Enabling commit-level durability',['../durability_log.html#commit_durability_enable',1,'']]],
  ['enabling_20statistics_4',['Enabling statistics',['../tool-statistics.html#autotoc_md49',1,'']]],
  ['encrypt_5',['encrypt',['../group__wt__ext.html#a0f0f363b689363d36ffce7fdf8a337ac',1,'WT_ENCRYPTOR']]],
  ['encryption_20configuration_6',['Encryption configuration',['../encryption.html#encryption_config',1,'']]],
  ['encryption_20extension_7',['encryption extension',['../encryption.html#encryption_sodium',1,'The libsodium encryption extension'],['../encryption.html#encryption_nop',1,'The nop encryption extension'],['../encryption.html#encryption_rotn',1,'The rotn encryption extension'],['../encryption.html#encryption_use',1,'Using an encryption extension']]],
  ['encryption_20extensions_8',['Custom encryption extensions',['../encryption.html#encryption_custom',1,'']]],
  ['encryption_20in_20wiredtiger_9',['Overview of Encryption in WiredTiger',['../encryption.html#encryption_overview',1,'']]],
  ['encryptors_10',['Encryptors',['../encryption.html',1,'programming']]],
  ['engines_11',['engines',['../compression.html#compression_custom',1,'Custom compression engines'],['../compression.html#compression_upgrading',1,'Upgrading compression engines']]],
  ['ensuring_20references_20on_20the_20pre_20fetch_20queue_20remain_20valid_12',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['environment_20name_20space_13',['Process&apos; environment name space',['../namespace.html#namespace_env',1,'']]],
  ['environment_20variable_14',['WIREDTIGER_CONFIG environment variable',['../database_config.html#config_env',1,'']]],
  ['environment_20variables_15',['Environment variables',['../security.html#environment_variables',1,'']]],
  ['equals_16',['equals',['../struct_w_t___c_u_r_s_o_r.html#a6736da9b394239a201ba97761b7b941b',1,'WT_CURSOR']]],
  ['err_5fprintf_17',['err_printf',['../group__wt__ext.html#a6d58298e356dbf58ac854c3d1af99678',1,'WT_EXTENSION_API']]],
  ['error_18',['Cursor position after error',['../cursor_ops.html#cursor_error',1,'']]],
  ['error_20handling_19',['Error handling',['../error_handling.html',1,'Error handling'],['../custom_data_sources.html#custom_ds_error_handling',1,'Error handling']]],
  ['error_20return_20name_20space_20',['Error return name space',['../namespace.html#namespace_error',1,'']]],
  ['errors_21',['errors',['../error_handling.html#error_ebusy',1,'EBUSY errors'],['../error_handling.html#error_translation',1,'Translating errors'],['../error_handling.html#error_list',1,'WiredTiger-specific errors']]],
  ['events_22',['Counting events',['../tool-perf.html#autotoc_md44',1,'']]],
  ['events_20profiling_23',['Sampling events (profiling)',['../tool-perf.html#autotoc_md45',1,'']]],
  ['eviction_24',['Eviction',['../cursors.html#cursors_eviction',1,'Cursors and Eviction'],['../arch-eviction.html',1,'Eviction'],['../eviction.html',1,'Eviction'],['../arch-eviction.html#eviction_overall',1,'Eviction']]],
  ['eviction_25',['eviction',['../eviction.html#clean_eviction',1,'Clean eviction'],['../arch-eviction.html#clean_dirty_eviction',1,'Clean vs dirty eviction'],['../eviction.html#hs_eviction',1,'History store eviction'],['../arch-rts.html#interaction-with-checkpoints-and-eviction',1,'Interaction with checkpoints and eviction'],['../eviction.html#update_restore_eviction',1,'Update restore eviction']]],
  ['eviction_20full_26',['Eviction (full)',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples-eviction',1,'']]],
  ['eviction_20locks_27',['Cache and Eviction locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-cache-and-eviction',1,'']]],
  ['eviction_20no_20queue_20lock_28',['Eviction (no queue lock)',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples-eviction0',1,'']]],
  ['eviction_20overview_29',['Eviction overview',['../eviction.html#eviction_overview',1,'']]],
  ['eviction_20triggers_20and_20targets_30',['Eviction triggers and targets',['../arch-eviction.html#eviction_triggers',1,'']]],
  ['eviction_20tuning_31',['Eviction tuning',['../tune_cache.html#cache_eviction',1,'']]],
  ['eviction_20tuning_32',['Cache and eviction tuning',['../tune_cache.html',1,'programming']]],
  ['ex_5fencrypt_20example_33',['The ex_encrypt example',['../encryption.html#encryption_ex',1,'']]],
  ['examining_20the_20output_34',['Examining the output',['../tool-perf.html#autotoc_md46',1,'']]],
  ['example_35',['Example',['../arch-usage-patterns.html#win-the-race-example',1,'']]],
  ['example_36',['example',['../tool-statistics.html#autotoc_md54',1,'A complete example'],['../encryption.html#encryption_ex',1,'The ex_encrypt example']]],
  ['example_201_37',['Example 1',['../arch-rts.html#rts-example-1',1,'']]],
  ['example_202_38',['Example 2',['../arch-rts.html#rts-example-2',1,'']]],
  ['example_203_39',['Example 3',['../arch-rts.html#rts-example-3',1,'']]],
  ['example_20metadata_40',['Example Metadata',['../arch-metadata.html#metadata_example',1,'']]],
  ['example_20pseudocode_41',['Example Pseudocode',['../arch-usage-patterns.html#win-the-race-pseudocode',1,'']]],
  ['example_20with_20timeline_42',['Example with timeline',['../tiered_storage.html#example',1,'']]],
  ['example_20wt_20implementation_43',['Example WT implementation',['../arch-usage-patterns.html#write-while-stable-wt-implementation',1,'']]],
  ['examples_44',['Examples',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples',1,'Examples'],['../group__wt.html#pack_examples',1,'Packing Examples']]],
  ['examples_45',['examples',['../struct_w_t___c_o_n_f_i_g___p_a_r_s_e_r.html#config_parse_examples',1,'Configuration String Parsing examples'],['../tool-perf.html#autotoc_md47',1,'More examples'],['../custom_storage_sources.html#storage_examples',1,'Storage source examples']]],
  ['exceptions_46',['Exceptions',['../eviction.html#exceptions',1,'']]],
  ['explicit_20secret_20key_47',['Keys via explicit secret key',['../encryption.html#encryption_secretkey',1,'']]],
  ['explicit_20transactions_48',['Explicit transactions',['../transactions_api.html#transactions_grouping',1,'']]],
  ['export_20tables_20using_20backup_20cursor_49',['Export tables using backup cursor',['../backup.html#backup_export',1,'']]],
  ['extending_20wiredtiger_50',['Extending WiredTiger',['../extensions.html',1,'encryption']]],
  ['extension_51',['extension',['../encryption.html#encryption_sodium',1,'The libsodium encryption extension'],['../encryption.html#encryption_nop',1,'The nop encryption extension'],['../encryption.html#encryption_rotn',1,'The rotn encryption extension'],['../encryption.html#encryption_use',1,'Using an encryption extension']]],
  ['extension_20api_52',['WiredTiger Extension API',['../group__wt__ext.html',1,'']]],
  ['extensions_53',['extensions',['../encryption.html#encryption_custom',1,'Custom encryption extensions'],['../extensions.html#extensions_loadable',1,'Loadable extensions'],['../extensions.html#extensions_local',1,'Local extensions']]],
  ['extensions_20and_20recovery_54',['Extensions and recovery',['../extensions.html#extensions_recovery',1,'']]],
  ['extent_20lists_55',['Extent lists',['../arch-block.html#block_lists',1,'']]],
  ['extract_56',['extract',['../group__wt__ext.html#a4db101f00fce80af9ebd4f29f56f7b6a',1,'WT_EXTRACTOR']]],
  ['extractors_57',['Extractors',['../custom_extractors.html',1,'Custom Extractors'],['../custom_extractors.html#custom_extractors_intro',1,'Introduction to Custom Extractors']]]
];
