var searchData=
[
  ['a_20block_0',['What is a block?',['../arch-block.html#block_what',1,'']]],
  ['a_20complete_20example_1',['A complete example',['../tool-statistics.html#autotoc_md54',1,'']]],
  ['a_20copy_20of_20the_20wtperf_20binary_20and_20the_20xray_20log_2',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['a_20cursor_3',['a cursor',['../cursor_ops.html#cursor_closing',1,'Closing a cursor'],['../cursor_ops.html#cursor_opening',1,'Opening a cursor'],['../cursor_ops.html#cursor_position',1,'Positioning a cursor']]],
  ['a_20database_4',['Connecting to a database',['../basic_api.html#basic_connection',1,'']]],
  ['a_20file_20format_5',['Choosing a file format',['../file_formats.html#file_formats_choice',1,'']]],
  ['a_20fuzzer_6',['Step 3: Run a fuzzer',['../tool-libfuzzer.html#autotoc_md14',1,'']]],
  ['a_20key_20in_20history_20store_7',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['a_20more_20precise_20control_20of_20the_20outlier_20thresholds_8',['Getting a more precise control of the outlier thresholds',['../tool-optrack.html#autotoc_md37',1,'']]],
  ['a_20single_20table_9',['RTS for a single table',['../arch-rts.html#rts-for-a-single-table',1,'']]],
  ['a_20table_10',['Creating a table',['../basic_api.html#basic_create_table',1,'']]],
  ['aborts_20unstable_20updates_11',['How RTS aborts unstable updates',['../arch-rts.html#rts-abort-updates',1,'']]],
  ['absolute_20paths_12',['Absolute paths',['../security.html#absolute_path',1,'']]],
  ['access_13',['Marked Access',['../arch-concurrency.html#marked-access',1,'']]],
  ['accessing_20data_20with_20cursors_14',['Accessing data with cursors',['../basic_api.html#basic_cursors',1,'']]],
  ['accessing_20statistics_15',['Accessing statistics',['../tool-statistics.html#autotoc_md50',1,'']]],
  ['acid_20properties_16',['Tutorial: transactions and ACID properties',['../explain_acid.html',1,'programming']]],
  ['acquire_17',['Acquire',['../arch-concurrency.html#acq-marked',1,'']]],
  ['acquire_20and_20release_18',['Message passing with acquire and release',['../arch-usage-patterns.html#message-passing',1,'']]],
  ['acquire_20barrier_19',['Acquire barrier',['../arch-concurrency.html#acq-bar',1,'']]],
  ['actions_20',['Flush actions',['../arch-tiered-storage.html#ts_checkpoint_flush',1,'']]],
  ['add_5fcollator_21',['add_collator',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a89290382c55f20e5a4e1bc9216c7a8c8',1,'WT_CONNECTION']]],
  ['add_5fcompressor_22',['add_compressor',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a4f26bfa799ae5e72b536ac93d6200783',1,'WT_CONNECTION']]],
  ['add_5fdata_5fsource_23',['add_data_source',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a459c1b71346bbcecb552ad73d43f27ea',1,'WT_CONNECTION']]],
  ['add_5fencryptor_24',['add_encryptor',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a59d203f4474780ca34bd3e07b8064949',1,'WT_CONNECTION']]],
  ['add_5fextractor_25',['add_extractor',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a2d65a70a305838e2a2a728fe5cb54903',1,'WT_CONNECTION']]],
  ['adding_20timestamps_26',['Adding timestamps',['../durability_overview.html#explain_durability_timestamp',1,'']]],
  ['address_20cookies_27',['Address Cookies',['../arch-block.html#block_address_cookie',1,'']]],
  ['after_20error_28',['Cursor position after error',['../cursor_ops.html#cursor_error',1,'']]],
  ['algorithm_29',['Pre-fetch Algorithm',['../arch-prefetch.html#prefetch_algorithm',1,'']]],
  ['algorithm_30',['The checkpoint algorithm',['../arch-checkpoint.html#autotoc_md6',1,'']]],
  ['algorithms_31',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['all_5fdurable_20timestamp_32',['Reading the &quot;all_durable&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_all_durable',1,'']]],
  ['allocation_33',['allocation',['../tune_file_alloc.html',1,'File allocation'],['../tune_file_alloc.html#tuning_system_file_block_allocation',1,'File block allocation']]],
  ['allocation_20size_34',['Allocation size',['../arch-block.html#alloc_size',1,'']]],
  ['allocation_5fsize_35',['allocation_size',['../tune_page_size_and_comp.html#allocation_size',1,'']]],
  ['allocator_36',['Memory allocator',['../tune_memory_allocator.html',1,'programming']]],
  ['allowing_20reading_20while_20allowing_20writes_37',['Correctness of allowing reading while allowing writes',['../arch-usage-patterns.html#slotted-arrays-correctness',1,'']]],
  ['allowing_20writes_38',['Correctness of allowing reading while allowing writes',['../arch-usage-patterns.html#slotted-arrays-correctness',1,'']]],
  ['alter_39',['Alter',['../arch-schema.html#schema_alter',1,'']]],
  ['alter_40',['alter',['../group__wt__ext.html#a1a7b6f26d733bd91ad8d205d8cb3482d',1,'WT_DATA_SOURCE::alter'],['../struct_w_t___s_e_s_s_i_o_n.html#ac6f0630cb70bb057aa4512f7888dc701',1,'WT_SESSION::alter()'],['../command_line.html#util_alter',1,'wt alter']]],
  ['always_20included_20in_20the_20wiredtiger_20library_41',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['an_20application_42',['Backup from an application',['../backup.html#backup_process',1,'']]],
  ['an_20encryption_20extension_43',['Using an encryption extension',['../encryption.html#encryption_use',1,'']]],
  ['an_20llvm_20libfuzzer_20fuzzer_44',['an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'Building and running an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md16',1,'Implementing an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md20',1,'Viewing code coverage for an LLVM LibFuzzer fuzzer']]],
  ['and_20acid_20properties_45',['Tutorial: transactions and ACID properties',['../explain_acid.html',1,'programming']]],
  ['and_20algorithms_46',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['and_20associated_20data_20structures_47',['Metadata and Associated Data Structures',['../arch-tiered-storage.html#ts_metadata',1,'']]],
  ['and_20backups_48',['Checkpoint durability and backups',['../durability_checkpoint.html#checkpoint_backup',1,'']]],
  ['and_20build_20wiredtiger_20with_20llvm_20flags_49',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['and_20column_20store_50',['Row Store and Column Store',['../arch-row-column.html',1,'arch-toc-data-src']]],
  ['and_20columns_51',['Tables, rows and columns',['../schema.html#schema_intro',1,'']]],
  ['and_20compile_20wiredtiger_20with_20xray_20instrumentation_52',['Step 2: Configure and compile WiredTiger with XRay instrumentation',['../tool-xray.html#autotoc_md57',1,'']]],
  ['and_20composite_20keys_53',['Syntactic Sugar and Composite Keys',['../arch-config-compile.html#compile_composite',1,'']]],
  ['and_20compression_54',['and compression',['../file_formats.html',1,'File formats and compression'],['../file_formats.html#file_formats_compression',1,'File formats and compression'],['../tune_page_size_and_comp.html',1,'Tuning page size and compression']]],
  ['and_20contact_20information_55',['WiredTiger community and contact information',['../community.html',1,'index']]],
  ['and_20content_56',['Cache size and content',['../arch-cache.html#arch_cache_size',1,'']]],
  ['and_20data_20handles_57',['File cursors, Btrees and data handles',['../arch-cursor.html#arch_cursor_dhandle',1,'']]],
  ['and_20definitions_58',['Introduction and Definitions',['../arch-tiered-storage.html#ts_intro',1,'']]],
  ['and_20deleted_20pages_59',['FLCS and deleted pages',['../arch-fast-truncate.html#ft_flcs',1,'']]],
  ['and_20details_60',['Safety rationale and details',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_safety',1,'']]],
  ['and_20disk_61',['Moving Data Between Memory and Disk',['../arch-toc-mem-disk.html',1,'arch-index']]],
  ['and_20disk_20pages_62',['Handling of timestamps in updates and disk pages',['../arch-timestamp.html#arch-timestamp-handling',1,'']]],
  ['and_20downgrading_20databases_63',['Upgrading and downgrading databases',['../upgrade.html',1,'programming']]],
  ['and_20enable_20libfuzzer_64',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['and_20eviction_65',['Cursors and Eviction',['../cursors.html#cursors_eviction',1,'']]],
  ['and_20eviction_66',['Interaction with checkpoints and eviction',['../arch-rts.html#interaction-with-checkpoints-and-eviction',1,'']]],
  ['and_20eviction_20locks_67',['Cache and Eviction locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-cache-and-eviction',1,'']]],
  ['and_20eviction_20tuning_68',['Cache and eviction tuning',['../tune_cache.html',1,'programming']]],
  ['and_20fast_20truncate_69',['Deleted Pages and Fast-Truncate',['../arch-fast-truncate.html',1,'arch-toc-fundamentals']]],
  ['and_20features_70',['WiredTiger Overview and Features',['../overview.html',1,'index']]],
  ['and_20file_20compaction_71',['Checkpoints and file compaction',['../durability_checkpoint.html#checkpoint_compaction',1,'']]],
  ['and_20file_20handle_20interfaces_72',['WiredTiger File System and File Handle Interfaces',['../arch-fs-os.html#file_system_and_handle',1,'']]],
  ['and_20gcp_20storage_20source_73',['Azure and GCP Storage Source',['../arch-cloud-storage-extension.html#azure_gcp_store',1,'']]],
  ['and_20github_74',['and GitHub',['../build-posix.html#posix_github',1,'Building using Git and GitHub'],['../build-windows.html#windows_github',1,'Building using Git and GitHub']]],
  ['and_20graphviz_75',['Step 1: Install LLVM and graphviz',['../tool-xray.html#autotoc_md56',1,'']]],
  ['and_20handle_20customization_76',['File System and Handle Customization',['../arch-fs-os.html#file_customization',1,'']]],
  ['and_20index_20cursors_77',['Table and index cursors',['../arch-cursor.html#arch_cursor_table',1,'']]],
  ['and_20installing_20wiredtiger_20on_20posix_20linux_20bsd_20os_20x_20_3a_78',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['and_20installing_20wiredtiger_20on_20windows_79',['Building and installing WiredTiger on Windows',['../build-windows.html',1,'index']]],
  ['and_20introspection_20with_20xray_80',['Instrumentation and introspection with XRay',['../tool-xray.html',1,'tool-index']]],
  ['and_20layout_81',['and Layout',['../arch-data-file.html#data_file_format',1,'Data File Format and Layout'],['../arch-data-file.html#data_file_on_disk_page_format',1,'On-Disk Page Format and Layout']]],
  ['and_20logging_82',['Readonly configuration and logging',['../readonly.html#readonly_logging',1,'']]],
  ['and_20logs_83',['Commit-level durability and logs',['../durability_log.html#commit_durability_logs',1,'']]],
  ['and_20lsm_20trees_84',['Readonly configuration and LSM trees',['../readonly.html#readonly_lsm',1,'']]],
  ['and_20multiple_20database_20handles_85',['Readonly configuration and multiple database handles',['../readonly.html#readonly_handles',1,'']]],
  ['and_20o_5fdirect_86',['Backup and O_DIRECT',['../backup.html#backup_o_direct',1,'']]],
  ['and_20open_20source_87',['NoSQL and Open Source',['../overview.html#nosql',1,'']]],
  ['and_20operating_20system_20support_88',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['and_20pages_89',['Reading files and pages',['../arch-block.html#read',1,'']]],
  ['and_20plans_90',['Projections and plans',['../arch-cursor.html#arch_cursor_projections',1,'']]],
  ['and_20prefixes_91',['Storage Sources, Buckets, and Prefixes',['../arch-tiered-storage.html#ts_buckets',1,'']]],
  ['and_20prepared_20transactions_92',['History store and prepared transactions',['../arch-hs.html#arch_hs_prepared',1,'']]],
  ['and_20projections_93',['Schema, Columns, Column Groups, Indices and Projections',['../schema.html',1,'programming']]],
  ['and_20reconciliation_94',['History store and reconciliation',['../arch-hs.html#arch_hs_reconciliation',1,'']]],
  ['and_20records_95',['Log operations and records',['../arch-logging.html#log_records',1,'']]],
  ['and_20recovery_96',['Custom Collators and Recovery',['../custom_collators.html#custom_collators_recovery',1,'']]],
  ['and_20recovery_97',['and recovery',['../extensions.html#extensions_recovery',1,'Extensions and recovery'],['../readonly.html#readonly_recovery',1,'Readonly configuration and recovery']]],
  ['and_20release_98',['Message passing with acquire and release',['../arch-usage-patterns.html#message-passing',1,'']]],
  ['and_20removal_99',['Log file archival and removal',['../durability_log.html#commit_durability_archiving',1,'']]],
  ['and_20rollback_20to_20stable_100',['History store and rollback to stable',['../arch-hs.html#arch_hs_rts',1,'']]],
  ['and_20run_20fuzzer_101',['Step 2: Build and run fuzzer',['../tool-libfuzzer.html#autotoc_md22',1,'']]],
  ['and_20running_20an_20llvm_20libfuzzer_20fuzzer_102',['Building and running an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'']]],
  ['and_20schema_20locks_103',['Checkpoint and Schema locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-checkpoint-schema',1,'']]],
  ['and_20statistics_104',['Messaging and Statistics',['../arch-cloud-storage-extension.html#extension_log_stat',1,'']]],
  ['and_20targets_105',['Eviction triggers and targets',['../arch-eviction.html#eviction_triggers',1,'']]],
  ['and_20techniques_106',['Tools and Techniques',['../tool-index.html',1,'index']]],
  ['and_20the_20block_20manager_107',['File creation and the block manager',['../arch-block.html#creation',1,'']]],
  ['and_20the_20page_5fdel_20field_108',['The instantiated flag and the page_del field',['../arch-fast-truncate.html#ft_instantiated_instantiated',1,'']]],
  ['and_20the_20xray_20log_109',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['and_20their_20implications_110',['Configuration choices and their implications',['../arch-logging.html#log_configuration',1,'']]],
  ['and_20time_20windows_111',['Representation of timestamps and time windows',['../arch-timestamp.html#arch-timestamp-representation',1,'']]],
  ['and_20timestamps_112',['and timestamps',['../timestamp_model.html#timestamps_durability_checkpoint',1,'Checkpoint durability and timestamps'],['../timestamp_misc.html#timestamps_misc_in_memory',1,'In-memory configurations and timestamps'],['../timestamp_model.html#timestamps_durability_commit',1,'Logged objects, commit-level durability and timestamps']]],
  ['and_20transactions_113',['and transactions',['../transactions_api.html#cursors_transactions',1,'Cursors and transactions'],['../timestamp_model.html#timestamp_transactions',1,'Timestamps and transactions']]],
  ['and_20unpacking_20data_114',['Packing and Unpacking Data',['../packing.html',1,'schema']]],
  ['and_20updating_115',['Inserting, removing and updating',['../cursor_ops.html#cursor_writes',1,'']]],
  ['and_20value_20formats_116',['Key and value formats',['../schema.html#schema_key_and_value_formats',1,'']]],
  ['and_20visibility_20rules_117',['History store cursor interface and visibility rules',['../arch-hs.html#arch_hs_cursor_visibility',1,'']]],
  ['and_20work_20queue_118',['Tiered Server and Work Queue',['../arch-tiered-storage.html#ts_server',1,'']]],
  ['and_20worldview_119',['Timestamp data model and worldview',['../arch-timestamp.html#arch-timestamp-model',1,'']]],
  ['and_20writes_120',['Atomic reads and writes',['../portability.html#atomic-reads-writes',1,'']]],
  ['api_121',['API',['../arch-toc-api.html',1,'API'],['../basic_api.html',1,'Getting Started with the API'],['../arch-prefetch.html#prefetch_api',1,'Pre-fetch API'],['../arch-python.html',1,'Python API'],['../group__wt.html',1,'WiredTiger API'],['../group__wt__ext.html',1,'WiredTiger Extension API']]],
  ['api_20calls_122',['Transactional API calls',['../transactions_api.html',1,'programming']]],
  ['app_5fprivate_123',['app_private',['../struct_w_t___s_e_s_s_i_o_n.html#a480525d3881dfcb90060af823a7f4a52',1,'WT_SESSION']]],
  ['application_124',['Backup from an application',['../backup.html#backup_process',1,'']]],
  ['application_20timestamp_20configuration_125',['Application timestamp configuration',['../timestamp_txn_api.html#timestamp_txn_api_configure',1,'']]],
  ['applications_126',['applications',['../transactions.html',1,'Transactional applications'],['../upgrading.html',1,'Upgrading WiredTiger applications'],['../programming.html',1,'Writing WiredTiger applications']]],
  ['apply_20bounds_20to_20the_20cursor_127',['Apply bounds to the cursor',['../cursor_ops.html#cursor_bound',1,'']]],
  ['architecture_20guide_128',['WiredTiger Architecture Guide',['../arch-index.html',1,'index']]],
  ['architecture_20support_129',['Multiple System Architecture Support',['../arch-fs-os.html#filesystem_usage',1,'']]],
  ['architectures_130',['Supported CPU architectures',['../portability.html#cpu',1,'']]],
  ['archival_20and_20removal_131',['Log file archival and removal',['../durability_log.html#commit_durability_archiving',1,'']]],
  ['arrays_132',['arrays',['../arch-usage-patterns.html#growable-arrays',1,'Growable arrays'],['../arch-usage-patterns.html#slotted-arrays',1,'Slotted arrays']]],
  ['as_20usual_133',['Step 2: Build as usual',['../tool-libfuzzer.html#autotoc_md13',1,'']]],
  ['as_20your_20c_20compiler_20and_20enable_20libfuzzer_134',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['assertions_135',['Assertions',['../debugging.html#assertions',1,'']]],
  ['associated_20data_20structures_136',['Metadata and Associated Data Structures',['../arch-tiered-storage.html#ts_metadata',1,'']]],
  ['at_20the_20data_3a_20part_201_137',['Looking at the data: Part 1',['../tool-optrack.html#autotoc_md36',1,'']]],
  ['at_20the_20data_3a_20part_202_138',['Looking at the data: Part 2',['../tool-optrack.html#autotoc_md38',1,'']]],
  ['atomic_20reads_20and_20writes_139',['Atomic reads and writes',['../portability.html#atomic-reads-writes',1,'']]],
  ['atomics_140',['Atomics',['../arch-concurrency.html#atomics',1,'']]],
  ['automatic_20prepare_20timestamp_20rounding_141',['Automatic prepare timestamp rounding',['../timestamp_prepare_roundup.html',1,'programming']]],
  ['azure_20and_20gcp_20storage_20source_142',['Azure and GCP Storage Source',['../arch-cloud-storage-extension.html#azure_gcp_store',1,'']]]
];
