var searchData=
[
  ['i_20o_0',['Direct I/O',['../tune_system_buffer_cache.html#tuning_system_buffer_cache_direct_io',1,'']]],
  ['i_20o_20more_20valuable_1',['Making I/O more valuable',['../overview.html#io',1,'']]],
  ['iaa_20compression_2',['Using iaa compression',['../compression.html#compression_iaa',1,'']]],
  ['id_3',['Keys via key ID',['../encryption.html#encryption_keyid',1,'']]],
  ['identifiers_4',['No Scoped Identifiers',['../arch-config-compile.html#compile_scoped_id',1,'']]],
  ['ids_5',['IDs',['../arch-rts.html#interaction-with-transaction-ids',1,'Interaction with transaction IDs'],['../arch-tiered-storage.html#ts_objectid',1,'Object IDs']]],
  ['ignore_5fprepare_6',['Configuring ignore_prepare',['../timestamp_prepare.html#timestamp_prepare_ignore_prepare',1,'']]],
  ['immutable_20indices_7',['Immutable indices',['../schema.html#schema_index_immutable',1,'']]],
  ['implementation_8',['Cloud Storage Source Implementation',['../arch-cloud-storage-extension.html#extension_storage_source',1,'']]],
  ['implementation_9',['implementation',['../arch-usage-patterns.html#write-while-stable-wt-implementation',1,'Example WT implementation'],['../arch-fast-truncate.html#ft_pointers',1,'Pointers to pieces of the implementation']]],
  ['implementation_20details_10',['Block manager implementation details',['../arch-block.html#block_implementation',1,'']]],
  ['implementation_20notes_11',['Implementation notes',['../custom_extractors.html#custom_extractors_notes',1,'']]],
  ['implementing_20an_20llvm_20libfuzzer_20fuzzer_12',['Implementing an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md16',1,'']]],
  ['implications_13',['Configuration choices and their implications',['../arch-logging.html#log_configuration',1,'']]],
  ['implicit_20transactions_14',['Implicit transactions',['../transactions_api.html#transactions_implicit',1,'']]],
  ['in_20history_20store_15',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['in_20memory_20concepts_16',['In Memory Concepts',['../arch-toc-in-mem.html',1,'arch-index']]],
  ['in_20memory_20configurations_20and_20timestamps_17',['In-memory configurations and timestamps',['../timestamp_misc.html#timestamps_misc_in_memory',1,'']]],
  ['in_20memory_20databases_18',['In memory databases',['../in_memory.html',1,'In-memory databases'],['../durability_overview.html#explain_durability_in_memory',1,'In-memory databases']]],
  ['in_20memory_20representation_19',['B-Tree In-Memory Representation',['../arch-btree.html#btree_btree_in_memory_representation',1,'']]],
  ['in_20memory_20support_20',['In-memory support',['../arch-fs-os.html#file_in_memory',1,'']]],
  ['in_20raw_20mode_21',['Custom Collators in raw mode',['../custom_extractors.html#custom_extractors_raw',1,'']]],
  ['in_20the_20block_20manager_22',['Files in the Block Manager',['../arch-tiered-storage.html#ts_block_files',1,'']]],
  ['in_20the_20database_20directory_23',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['in_20the_20history_20store_20table_24',['Tombstones in the history store table',['../arch-hs.html#arch_hs_table_tombstone',1,'']]],
  ['in_20the_20wiredtiger_20distribution_25',['3rd party software included in the WiredTiger distribution',['../license.html#license_distribution',1,'']]],
  ['in_20the_20wiredtiger_20library_26',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['in_20the_20wiredtiger_20library_3a_20ppc64_27',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['in_20the_20wiredtiger_20library_3a_20s390x_28',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['in_20tiered_20storage_29',['Cookies in Tiered Storage',['../arch-tiered-storage.html#ts_cookies',1,'']]],
  ['in_20updates_20and_20disk_20pages_30',['Handling of timestamps in updates and disk pages',['../arch-timestamp.html#arch-timestamp-handling',1,'']]],
  ['in_20wiredtiger_31',['in WiredTiger',['../tune_page_size_and_comp.html#configurable_page_struct',1,'Configurable page structures in WiredTiger'],['../encryption.html#encryption_overview',1,'Overview of Encryption in WiredTiger'],['../custom_storage_sources.html#storage_overview',1,'Overview of Tiered Storage in WiredTiger'],['../tune_page_size_and_comp.html#table_compress',1,'Table summarizing compression in WiredTiger']]],
  ['included_20in_20the_20wiredtiger_20distribution_32',['3rd party software included in the WiredTiger distribution',['../license.html#license_distribution',1,'']]],
  ['included_20in_20the_20wiredtiger_20library_33',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['included_20in_20the_20wiredtiger_20library_3a_20ppc64_34',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['included_20in_20the_20wiredtiger_20library_3a_20s390x_35',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['incremental_20backup_36',['Incremental backup',['../backup.html#backup_incremental-block',1,'Block-based Incremental backup'],['../backup.html#backup_incremental',1,'Log-based Incremental backup']]],
  ['incremental_20backup_37',['incremental backup',['../arch-backup.html#autotoc_md2',1,'Block-based incremental backup'],['../arch-backup.html#autotoc_md3',1,'Log-based incremental backup']]],
  ['independent_20structures_38',['Position Independent Structures',['../arch-config-compile.html#compile_position_independent',1,'']]],
  ['index_20cursor_20projections_39',['Index cursor projections',['../schema.html#schema_index_projections',1,'']]],
  ['index_20cursors_40',['Table and index cursors',['../arch-cursor.html#arch_cursor_table',1,'']]],
  ['index_20data_41',['Table Index data',['../data_sources.html#data_indices',1,'']]],
  ['indices_42',['Indices',['../custom_collators.html#custom_collators_indices',1,'Custom Collators for Indices'],['../schema.html#schema_indices',1,'Indices']]],
  ['indices_43',['Immutable indices',['../schema.html#schema_index_immutable',1,'']]],
  ['indices_20and_20projections_44',['Schema, Columns, Column Groups, Indices and Projections',['../schema.html',1,'programming']]],
  ['information_45',['information',['../timestamp_txn_api.html#timestamp_txn_api_query',1,'Querying transaction timestamp information'],['../tool-libfuzzer.html#autotoc_md23',1,'Step 3: Generate code coverage information'],['../community.html',1,'WiredTiger community and contact information']]],
  ['information_20on_20portability_46',['General information on portability',['../portability.html',1,'index']]],
  ['information_20with_20wt_5fsession_3a_3abegin_5ftransaction_47',['Configuring transaction timestamp information with WT_SESSION::begin_transaction',['../timestamp_txn_api.html#timestamp_txn_api_begin',1,'']]],
  ['information_20with_20wt_5fsession_3a_3acommit_5ftransaction_48',['Configuring transaction timestamp information with WT_SESSION::commit_transaction',['../timestamp_txn_api.html#timestamp_txn_api_commit',1,'']]],
  ['information_20with_20wt_5fsession_3a_3aprepare_5ftransaction_49',['Configuring transaction timestamp information with WT_SESSION::prepare_transaction',['../timestamp_txn_api.html#timestamp_txn_api_prepare',1,'']]],
  ['information_20with_20wt_5fsession_3a_3atimestamp_5ftransaction_50',['Configuring transaction timestamp information with WT_SESSION::timestamp_transaction',['../timestamp_txn_api.html#timestamp_txn_api_timestamp_transaction',1,'']]],
  ['initial_20pre_20compilation_51',['Initial Pre-Compilation',['../arch-config-compile.html#compile_initial',1,'']]],
  ['initialization_52',['Initialization',['../arch-connection.html#arch_conn_init',1,'']]],
  ['initialization_53',['History store initialization',['../arch-hs.html#arch_hs_initialize',1,'']]],
  ['inputs_54',['Slicing inputs',['../tool-libfuzzer.html#autotoc_md19',1,'']]],
  ['insert_55',['insert',['../struct_w_t___c_u_r_s_o_r.html#aac90d9fbcc031570f924db55f8a1cee3',1,'WT_CURSOR']]],
  ['inserted_20or_20modified_20content_56',['Newly inserted or modified content',['../chunkcache.html#inserts',1,'']]],
  ['inserting_20removing_20and_20updating_57',['Inserting, removing and updating',['../cursor_ops.html#cursor_writes',1,'']]],
  ['inst_5fupdates_20field_58',['The inst_updates field',['../arch-fast-truncate.html#ft_instantiated_updates',1,'']]],
  ['install_20llvm_20and_20graphviz_59',['Step 1: Install LLVM and graphviz',['../tool-xray.html#autotoc_md56',1,'']]],
  ['install_20the_20python_20modules_60',['Install the python modules',['../tool-optrack.html#autotoc_md30',1,'']]],
  ['installing_20wiredtiger_61',['Installing WiredTiger',['../build-posix.html#posix_installing',1,'Installing WiredTiger'],['../build-windows.html#windows_installing',1,'Installing WiredTiger']]],
  ['installing_20wiredtiger_20on_20posix_20linux_20bsd_20os_20x_20_3a_62',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['installing_20wiredtiger_20on_20windows_63',['Building and installing WiredTiger on Windows',['../build-windows.html',1,'index']]],
  ['instantiated_20flag_20and_20the_20page_5fdel_20field_64',['The instantiated flag and the page_del field',['../arch-fast-truncate.html#ft_instantiated_instantiated',1,'']]],
  ['instantiated_20pages_65',['Instantiated Pages',['../arch-fast-truncate.html#ft_instantiated_pages',1,'']]],
  ['instantiation_66',['Instantiation',['../arch-fast-truncate.html#ft_instantiation',1,'']]],
  ['instrumentation_67',['Step 2: Configure and compile WiredTiger with XRay instrumentation',['../tool-xray.html#autotoc_md57',1,'']]],
  ['instrumentation_20and_20introspection_20with_20xray_68',['Instrumentation and introspection with XRay',['../tool-xray.html',1,'tool-index']]],
  ['instrumenting_20with_20xray_69',['Instrumenting with XRay',['../tool-xray.html#autotoc_md55',1,'']]],
  ['integrity_70',['Schema Integrity',['../arch-schema.html#schema_integrity',1,'']]],
  ['interaction_20with_20checkpoints_20and_20eviction_71',['Interaction with checkpoints and eviction',['../arch-rts.html#interaction-with-checkpoints-and-eviction',1,'']]],
  ['interaction_20with_20other_20components_72',['Interaction With Other Components',['../arch-prefetch.html#prefetch_other',1,'']]],
  ['interaction_20with_20other_20operations_73',['Interaction With Other Operations',['../arch-btree.html#btree_truncate_interaction_with_other_operations',1,'']]],
  ['interaction_20with_20timestamps_74',['Interaction with timestamps',['../arch-rts.html#interaction-with-timestamps',1,'']]],
  ['interaction_20with_20transaction_20ids_75',['Interaction with transaction IDs',['../arch-rts.html#interaction-with-transaction-ids',1,'']]],
  ['interface_76',['Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_handle',1,'Cloud File Handle Interface'],['../arch-cloud-storage-extension.html#extension_cloud_file_system',1,'Cloud File System Interface'],['../arch-fs-os.html#file_handle',1,'File Handle Interface'],['../arch-fs-os.html#file_system',1,'File System Interface']]],
  ['interface_77',['History store cursor interface',['../arch-hs.html#arch_hs_cursor',1,'']]],
  ['interface_20and_20operating_20system_20support_78',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['interface_20and_20visibility_20rules_79',['History store cursor interface and visibility rules',['../arch-hs.html#arch_hs_cursor_visibility',1,'']]],
  ['interface_20to_20lsm_20trees_80',['Interface to LSM trees',['../lsm.html#lsm_api',1,'']]],
  ['interfaces_81',['WiredTiger File System and File Handle Interfaces',['../arch-fs-os.html#file_system_and_handle',1,'']]],
  ['internal_20leaf_20key_20value_20max_82',['internal/leaf key/value max',['../tune_page_size_and_comp.html#key_val_max',1,'']]],
  ['internal_20page_20reconciliation_83',['Internal page reconciliation',['../arch-fast-truncate.html#ft_internal_reconciliation',1,'']]],
  ['internal_20threads_84',['Internal Threads',['../arch-logging.html#log_threads',1,'']]],
  ['internal_20usage_85',['Internal usage',['../arch-row-column.html#row_column_internal_use',1,'']]],
  ['internal_20wiredtiger_20development_86',['Internal WiredTiger Development',['../arch-toc-int-wt-dev.html',1,'arch-index']]],
  ['internal_5fpage_5fmax_87',['internal_page_max',['../tune_page_size_and_comp.html#internal_page_max',1,'']]],
  ['internals_88',['Snapshot Internals',['../arch-snapshot.html#snapshot_internals',1,'']]],
  ['into_20memory_89',['Skipping reading unnecessary pages into memory',['../arch-rts.html#rts-page-skip',1,'']]],
  ['into_20the_20cache_90',['Pre-fetching Content Into the Cache',['../arch-prefetch.html#prefetch_algorithm_process_pages',1,'']]],
  ['introduce_20runtime_20overhead_91',['Will operation tracking introduce runtime overhead?',['../tool-optrack.html#autotoc_md27',1,'']]],
  ['introduction_92',['Introduction',['../arch-config-compile.html#compile_intro',1,'Introduction'],['../config_strings.html#config_intro',1,'Introduction'],['../tool-perf-flamegraphs.html#autotoc_md40',1,'Introduction'],['../tool-statistics.html#autotoc_md48',1,'Introduction']]],
  ['introduction_20and_20definitions_93',['Introduction and Definitions',['../arch-tiered-storage.html#ts_intro',1,'']]],
  ['introduction_20to_20custom_20collators_94',['Introduction to Custom Collators',['../custom_collators.html#custom_collators_intro',1,'']]],
  ['introduction_20to_20custom_20extractors_95',['Introduction to Custom Extractors',['../custom_extractors.html#custom_extractors_intro',1,'']]],
  ['introspection_20with_20xray_96',['Instrumentation and introspection with XRay',['../tool-xray.html',1,'tool-index']]],
  ['is_20a_20block_97',['What is a block?',['../arch-block.html#block_what',1,'']]],
  ['is_20pre_20fetching_20useful_98',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['is_20pre_20fetching_20when_20is_20pre_20fetching_20useful_99',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['is_5fnew_100',['is_new',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#ae2bacefe9777b8ab32d8b22c292c4f39',1,'WT_CONNECTION']]],
  ['isolation_20levels_101',['Isolation levels',['../transactions_api.html#isolation_levels',1,'']]],
  ['isolation_20levels_102',['Tutorial: isolation levels',['../explain_isolation.html',1,'programming']]],
  ['iterating_20over_20b_20trees_103',['Iterating over B-Trees',['../arch-rts.html#iterating-over-b-trees',1,'']]],
  ['iterating_20over_20pages_104',['Iterating over pages',['../arch-rts.html#iterating-over-pages',1,'']]],
  ['iterating_20over_20updates_105',['Iterating over updates',['../arch-rts.html#iterating-over-updates',1,'']]]
];
