var searchData=
[
  ['s_20commit_20timestamp_0',['Setting the transaction&apos;s commit timestamp',['../timestamp_txn_api.html#timestamp_txn_api_commit_timestamp',1,'']]],
  ['s_20read_20timestamp_1',['Setting the transaction&apos;s read timestamp',['../timestamp_txn_api.html#timestamp_txn_api_read_timestamp',1,'']]],
  ['s3_20storage_20source_2',['S3 Storage source',['../arch-cloud-storage-extension.html#s3_store',1,'']]],
  ['s390x_3',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['safety_20rationale_20and_20details_4',['Safety rationale and details',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_safety',1,'']]],
  ['salvage_5',['salvage',['../group__wt__ext.html#a4f8baf9dba6309b6051f79c9cbbb10e2',1,'WT_DATA_SOURCE::salvage'],['../struct_w_t___s_e_s_s_i_o_n.html#ab3399430e474f7005bd5ea20e6ec7a8e',1,'WT_SESSION::salvage()'],['../command_line.html#util_salvage',1,'wt salvage']]],
  ['samples_6',['samples',['../packing.html#config_examples',1,'Code samples'],['../schema.html#schema_examples',1,'Code samples'],['../threads.html#threads_example',1,'Code samples']]],
  ['sampling_20events_20profiling_7',['Sampling events (profiling)',['../tool-perf.html#autotoc_md45',1,'']]],
  ['scaling_8',['Multi-core scaling',['../overview.html#multi_core',1,'']]],
  ['schema_9',['Schema',['../arch-schema.html',1,'arch-toc-data-org']]],
  ['schema_20columns_20column_20groups_20indices_20and_20projections_10',['Schema, Columns, Column Groups, Indices and Projections',['../schema.html',1,'programming']]],
  ['schema_20integrity_11',['Schema Integrity',['../arch-schema.html#schema_integrity',1,'']]],
  ['schema_20locks_12',['Checkpoint and Schema locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-checkpoint-schema',1,'']]],
  ['schema_20manipulation_13',['Schema Manipulation',['../arch-schema.html#schema_api',1,'']]],
  ['scoped_20identifiers_14',['No Scoped Identifiers',['../arch-config-compile.html#compile_scoped_id',1,'']]],
  ['scoping_15',['Cursor key/value memory scoping',['../cursor_ops.html#cursor_memory_scoping',1,'']]],
  ['scr_5falloc_16',['scr_alloc',['../group__wt__ext.html#a6c41c29c8db84b35217b8ad19bd09a87',1,'WT_EXTENSION_API']]],
  ['scr_5ffree_17',['scr_free',['../group__wt__ext.html#a13b8f3c923c8b0f8bb683ed3b192ee73',1,'WT_EXTENSION_API']]],
  ['scripts_20supporting_20configuration_20compilation_18',['Scripts Supporting Configuration Compilation',['../arch-config-compile.html#compile_scripts',1,'']]],
  ['search_19',['search',['../struct_w_t___c_u_r_s_o_r.html#a7e25b2ced2cf3ec68bd5429bf921c79f',1,'WT_CURSOR']]],
  ['search_5fnear_20',['search_near',['../struct_w_t___c_u_r_s_o_r.html#a8068ddce20d0775f26f6dac6e5eb209c',1,'WT_CURSOR']]],
  ['searching_20for_20older_20versions_20of_20a_20key_20in_20history_20store_21',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['secret_20key_22',['Keys via explicit secret key',['../encryption.html#encryption_secretkey',1,'']]],
  ['security_23',['Security',['../security.html',1,'admin']]],
  ['serialization_24',['Serialization',['../custom_data_sources.html#custom_data_source_cursor_serialize',1,'']]],
  ['server_20and_20work_20queue_25',['Tiered Server and Work Queue',['../arch-tiered-storage.html#ts_server',1,'']]],
  ['server_20dhandle_20sweep_26',['Sweep-Server Dhandle Sweep',['../arch-dhandle.html#dhandle_sweep_server_dhandle_sweep',1,'']]],
  ['session_27',['Session',['../arch-session.html',1,'arch-toc-fundamentals']]],
  ['session_28',['session',['../struct_w_t___c_u_r_s_o_r.html#a050e8dfd68303048921e528fa591a00c',1,'WT_CURSOR']]],
  ['session_20cache_20sweep_29',['Dhandle Session Cache Sweep',['../arch-dhandle.html#dhandle_dhandle_session_cache_sweep',1,'']]],
  ['session_20cursor_20sweep_30',['Session cursor sweep',['../arch-cursor.html#arch_cursor_sweep',1,'']]],
  ['session_20level_20configuration_31',['Session-Level Configuration',['../arch-prefetch.html#prefetch_api_session',1,'']]],
  ['session_20snapshot_32',['Resetting the session snapshot',['../transactions_api.html#snapshot_reset',1,'']]],
  ['set_5ffile_5fsystem_33',['set_file_system',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a7c9d5b40133a6ba1cbc4a6b1d8e1e86b',1,'WT_CONNECTION']]],
  ['set_5fkey_34',['set_key',['../struct_w_t___c_u_r_s_o_r.html#ad1088d719df40babc1f57d086691ebdc',1,'WT_CURSOR']]],
  ['set_5ftimestamp_35',['set_timestamp',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#ad082439541b1b95d6aae6c15026fe512',1,'WT_CONNECTION']]],
  ['set_5fvalue_36',['set_value',['../struct_w_t___c_u_r_s_o_r.html#a27f7cbd0cd3e561f6a145704813ad64c',1,'WT_CURSOR']]],
  ['setting_20global_20timestamps_37',['Setting global timestamps',['../timestamp_global_api.html#timestamp_global_setting_timestamps',1,'']]],
  ['setting_20multiple_20commit_20timestamps_38',['Setting multiple commit timestamps',['../timestamp_txn_api.html#timestamp_txn_api_commit_multi_timestamp',1,'']]],
  ['setting_20the_20global_20durable_5ftimestamp_20timestamp_39',['Setting the global &quot;durable_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_set_api_durable_timestamp',1,'']]],
  ['setting_20the_20oldest_5ftimestamp_20timestamp_40',['Setting the &quot;oldest_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_set_api_oldest_timestamp',1,'']]],
  ['setting_20the_20stable_5ftimestamp_20timestamp_41',['Setting the &quot;stable_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_set_api_stable_timestamp',1,'']]],
  ['setting_20the_20transaction_20s_20commit_20timestamp_42',['Setting the transaction&apos;s commit timestamp',['../timestamp_txn_api.html#timestamp_txn_api_commit_timestamp',1,'']]],
  ['setting_20the_20transaction_20s_20read_20timestamp_43',['Setting the transaction&apos;s read timestamp',['../timestamp_txn_api.html#timestamp_txn_api_read_timestamp',1,'']]],
  ['shared_20caches_44',['Shared caches',['../arch-cache.html#arch_cache_shared',1,'']]],
  ['shared_20caches_45',['Per-process shared caches',['../shared_cache.html',1,'programming']]],
  ['sharing_20of_20tiered_20objects_46',['Sharing of Tiered Objects',['../arch-tiered-storage.html#ts_future_sharing',1,'']]],
  ['signal_20handling_47',['Signal handling',['../signals.html',1,'programming']]],
  ['simulating_20workloads_20with_20wtperf_48',['Simulating workloads with wtperf',['../wtperf.html',1,'programming']]],
  ['single_20table_49',['RTS for a single table',['../arch-rts.html#rts-for-a-single-table',1,'']]],
  ['size_50',['size',['../arch-block.html#alloc_size',1,'Allocation size'],['../tune_cache.html#tuning_cache_size',1,'Cache size'],['../group__wt.html#abd8b1299dfb5c54dc049fa42a4680b55',1,'WT_ITEM::size'],['../group__wt.html#ac08f030bf6cfe86eed9810e90ba6cc20',1,'WT_MODIFY::size'],['../group__wt__ext.html#a817b5bc96a33010a1caca4a745a9d16d',1,'WT_DATA_SOURCE::size']]],
  ['size_20and_20compression_51',['Tuning page size and compression',['../tune_page_size_and_comp.html',1,'programming']]],
  ['size_20and_20content_52',['Cache size and content',['../arch-cache.html#arch_cache_size',1,'']]],
  ['sizing_53',['sizing',['../group__wt__ext.html#ac965990f0d81b99fc10ec0b13b9df162',1,'WT_ENCRYPTOR']]],
  ['skipping_20checkpoints_54',['Skipping checkpoints',['../arch-checkpoint.html#autotoc_md7',1,'']]],
  ['skipping_20deleted_20pages_55',['Skipping deleted pages',['../arch-fast-truncate.html#ft_page_skip',1,'']]],
  ['skipping_20reading_20unnecessary_20pages_20into_20memory_56',['Skipping reading unnecessary pages into memory',['../arch-rts.html#rts-page-skip',1,'']]],
  ['slicing_20inputs_57',['Slicing inputs',['../tool-libfuzzer.html#autotoc_md19',1,'']]],
  ['slotted_20arrays_58',['Slotted arrays',['../arch-usage-patterns.html#slotted-arrays',1,'']]],
  ['snappy_20compression_59',['Using snappy compression',['../compression.html#compression_snappy',1,'']]],
  ['snapshot_60',['Snapshot',['../arch-snapshot.html',1,'arch-toc-fundamentals']]],
  ['snapshot_61',['Resetting the session snapshot',['../transactions_api.html#snapshot_reset',1,'']]],
  ['snapshot_20internals_62',['Snapshot Internals',['../arch-snapshot.html#snapshot_internals',1,'']]],
  ['snapshot_20read_20uncommitted_20modifies_63',['Snapshot Read-uncommitted \&amp; Modifies',['../arch-snapshot.html#snapshot_read_uncommitted',1,'']]],
  ['snapshot_20visibility_64',['Snapshot Visibility',['../arch-snapshot.html#snapshot_visibility',1,'']]],
  ['snapshots_65',['Transactions using Snapshots',['../arch-snapshot.html#snapshot_transaction',1,'']]],
  ['snapshots_66',['Checkpoints vs. snapshots',['../durability_checkpoint.html#checkpoint_snapshot',1,'']]],
  ['snapshots_20checkpoints_67',['Snapshots \&amp; Checkpoints',['../arch-snapshot.html#snapshot_checkpoint',1,'']]],
  ['software_20always_20included_20in_20the_20wiredtiger_20library_68',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['software_20included_20in_20the_20wiredtiger_20distribution_69',['3rd party software included in the WiredTiger distribution',['../license.html#license_distribution',1,'']]],
  ['software_20optionally_20included_20in_20the_20wiredtiger_20library_3a_20ppc64_70',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['software_20optionally_20included_20in_20the_20wiredtiger_20library_3a_20s390x_71',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['source_72',['Source',['../arch-cloud-storage-extension.html#azure_gcp_store',1,'Azure and GCP Storage Source'],['../overview.html#nosql',1,'NoSQL and Open Source'],['../arch-cloud-storage-extension.html',1,'Storage Source']]],
  ['source_73',['S3 Storage source',['../arch-cloud-storage-extension.html#s3_store',1,'']]],
  ['source_20examples_74',['Storage source examples',['../custom_storage_sources.html#storage_examples',1,'']]],
  ['source_20implementation_75',['Cloud Storage Source Implementation',['../arch-cloud-storage-extension.html#extension_storage_source',1,'']]],
  ['source_20parameters_76',['Storage source parameters',['../custom_storage_sources.html#storage_parameters',1,'']]],
  ['source_20wt_5fbtree_77',['B-Tree Data Source (WT_BTREE)',['../arch-btree.html#btree_btree_data_source',1,'']]],
  ['sources_78',['Sources',['../custom_data_sources.html',1,'Custom Data Sources'],['../arch-toc-data-src.html',1,'Data Sources'],['../data_sources.html',1,'Data Sources']]],
  ['sources_79',['sources',['../data_sources.html#data_builtin',1,'Builtin data sources'],['../custom_storage_sources.html',1,'Custom Tiered Storage sources']]],
  ['sources_20buckets_20and_20prefixes_80',['Storage Sources, Buckets, and Prefixes',['../arch-tiered-storage.html#ts_buckets',1,'']]],
  ['space_81',['space',['../namespace.html#namespace_c',1,'C language name space'],['../namespace.html#namespace_error',1,'Error return name space'],['../namespace.html#namespace_filesystem',1,'File system name space'],['../namespace.html#namespace_env',1,'Process&apos; environment name space']]],
  ['spaces_82',['Name spaces',['../namespace.html',1,'programming']]],
  ['specific_20configuration_20strings_83',['Creating data-specific configuration strings',['../custom_data_sources.html#custom_ds_config_add',1,'']]],
  ['specific_20errors_84',['WiredTiger-specific errors',['../error_handling.html#error_list',1,'']]],
  ['specific_20objects_85',['Checkpointing specific objects',['../durability_checkpoint.html#checkpoint_target',1,'']]],
  ['spin_5fdestroy_86',['spin_destroy',['../group__wt__ext.html#aae6af390efb79e1c9b9259e32853f9a3',1,'WT_EXTENSION_API']]],
  ['spin_5finit_87',['spin_init',['../group__wt__ext.html#a8f41cf1359a2d3260173e35a324297a7',1,'WT_EXTENSION_API']]],
  ['spin_5flock_88',['spin_lock',['../group__wt__ext.html#a18438824d6782a7e73c00e09e5e69066',1,'WT_EXTENSION_API']]],
  ['spin_5funlock_89',['spin_unlock',['../group__wt__ext.html#aa6b38740c7216fa7b63b21902858bee1',1,'WT_EXTENSION_API']]],
  ['split_20percentage_90',['split_pct (split percentage)',['../tune_page_size_and_comp.html#split_pct',1,'']]],
  ['split_5fpct_20split_20percentage_91',['split_pct (split percentage)',['../tune_page_size_and_comp.html#split_pct',1,'']]],
  ['stable_92',['History store and rollback to stable',['../arch-hs.html#arch_hs_rts',1,'']]],
  ['stable_20rts_93',['Rollback to Stable (RTS)',['../arch-rts.html',1,'arch-toc-fundamentals']]],
  ['stable_20with_20timestamps_94',['Using rollback-to-stable with timestamps',['../timestamp_misc.html#timestamp_misc_rts',1,'']]],
  ['stable_20wws_95',['Write While stable (WwS)',['../arch-usage-patterns.html#write-while-stable',1,'']]],
  ['stable_5ftimestamp_20timestamp_96',['stable_timestamp timestamp',['../timestamp_global_api.html#timestamp_global_query_api_stable_timestamp',1,'Reading the &quot;stable_timestamp&quot; timestamp'],['../timestamp_global_api.html#timestamp_global_set_api_stable_timestamp',1,'Setting the &quot;stable_timestamp&quot; timestamp']]],
  ['started_20with_20the_20api_97',['Getting Started with the API',['../basic_api.html',1,'programming']]],
  ['stat_98',['wt stat',['../command_line.html#util_stat',1,'']]],
  ['state_99',['state',['../timestamp_global_api.html',1,'Managing the global timestamp state'],['../timestamp_txn_api.html',1,'Managing the transaction timestamp state']]],
  ['statistics_100',['Statistics',['../arch-cloud-storage-extension.html#extension_log_stat',1,'Messaging and Statistics'],['../statistics.html',1,'Statistics']]],
  ['statistics_101',['statistics',['../tool-statistics.html#autotoc_md50',1,'Accessing statistics'],['../tool-statistics.html#autotoc_md49',1,'Enabling statistics'],['../tune_statistics.html',1,'Performance monitoring with statistics'],['../tool-statistics.html#autotoc_md51',1,'Visualizing statistics']]],
  ['statistics_20data_102',['Statistics Data',['../data_sources.html#data_statistics',1,'']]],
  ['statistics_20logging_103',['Statistics Logging',['../tool-statistics.html',1,'tool-index']]],
  ['statistics_20logging_104',['Statistics logging',['../statistics.html#statistics_log',1,'']]],
  ['step_201_3a_20configure_20with_20clang_20as_20your_20c_20compiler_20and_20enable_20libfuzzer_105',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['step_201_3a_20configure_20your_20build_20to_20compile_20with_20clang_20coverage_106',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['step_201_3a_20install_20llvm_20and_20graphviz_107',['Step 1: Install LLVM and graphviz',['../tool-xray.html#autotoc_md56',1,'']]],
  ['step_201_3a_20take_20a_20copy_20of_20the_20wtperf_20binary_20and_20the_20xray_20log_108',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['step_202_3a_20build_20and_20run_20fuzzer_109',['Step 2: Build and run fuzzer',['../tool-libfuzzer.html#autotoc_md22',1,'']]],
  ['step_202_3a_20build_20as_20usual_110',['Step 2: Build as usual',['../tool-libfuzzer.html#autotoc_md13',1,'']]],
  ['step_202_3a_20configure_20and_20build_20wiredtiger_20with_20llvm_20flags_111',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['step_202_3a_20configure_20and_20compile_20wiredtiger_20with_20xray_20instrumentation_112',['Step 2: Configure and compile WiredTiger with XRay instrumentation',['../tool-xray.html#autotoc_md57',1,'']]],
  ['step_203_3a_20generate_20code_20coverage_20information_113',['Step 3: Generate code coverage information',['../tool-libfuzzer.html#autotoc_md23',1,'']]],
  ['step_203_3a_20process_20the_20traces_114',['Step 3: Process the traces',['../tool-xray.html#autotoc_md62',1,'']]],
  ['step_203_3a_20run_20a_20fuzzer_115',['Step 3: Run a fuzzer',['../tool-libfuzzer.html#autotoc_md14',1,'']]],
  ['step_203_3a_20run_20wtperf_116',['Step 3: Run wtperf',['../tool-xray.html#autotoc_md58',1,'']]],
  ['storage_117',['Storage',['../arch-tiered-storage.html#ts_cookies',1,'Cookies in Tiered Storage'],['../arch-tiered-storage.html',1,'Tiered Storage'],['../tiered_storage.html',1,'Tiered Storage']]],
  ['storage_20in_20wiredtiger_118',['Overview of Tiered Storage in WiredTiger',['../custom_storage_sources.html#storage_overview',1,'']]],
  ['storage_20layout_119',['WT_CONF storage layout',['../arch-config-compile.html#compile_layout',1,'']]],
  ['storage_20source_120',['Storage Source',['../arch-cloud-storage-extension.html#azure_gcp_store',1,'Azure and GCP Storage Source'],['../arch-cloud-storage-extension.html',1,'Storage Source']]],
  ['storage_20source_121',['S3 Storage source',['../arch-cloud-storage-extension.html#s3_store',1,'']]],
  ['storage_20source_20examples_122',['Storage source examples',['../custom_storage_sources.html#storage_examples',1,'']]],
  ['storage_20source_20implementation_123',['Cloud Storage Source Implementation',['../arch-cloud-storage-extension.html#extension_storage_source',1,'']]],
  ['storage_20source_20parameters_124',['Storage source parameters',['../custom_storage_sources.html#storage_parameters',1,'']]],
  ['storage_20sources_125',['Custom Tiered Storage sources',['../custom_storage_sources.html',1,'programming']]],
  ['storage_20sources_20buckets_20and_20prefixes_126',['Storage Sources, Buckets, and Prefixes',['../arch-tiered-storage.html#ts_buckets',1,'']]],
  ['store_127',['Store',['../arch-hs.html',1,'History Store'],['../arch-row-column.html',1,'Row Store and Column Store'],['../arch-hs.html#arch_hs_read',1,'Searching for older versions of a key in History Store']]],
  ['store_128',['Operations on the history store',['../arch-rts.html#operations-on-the-history-store',1,'']]],
  ['store_20and_20column_20store_129',['Row Store and Column Store',['../arch-row-column.html',1,'arch-toc-data-src']]],
  ['store_20and_20prepared_20transactions_130',['History store and prepared transactions',['../arch-hs.html#arch_hs_prepared',1,'']]],
  ['store_20and_20reconciliation_131',['History store and reconciliation',['../arch-hs.html#arch_hs_reconciliation',1,'']]],
  ['store_20and_20rollback_20to_20stable_132',['History store and rollback to stable',['../arch-hs.html#arch_hs_rts',1,'']]],
  ['store_20cursor_20interface_133',['History store cursor interface',['../arch-hs.html#arch_hs_cursor',1,'']]],
  ['store_20cursor_20interface_20and_20visibility_20rules_134',['History store cursor interface and visibility rules',['../arch-hs.html#arch_hs_cursor_visibility',1,'']]],
  ['store_20eviction_135',['History store eviction',['../eviction.html#hs_eviction',1,'']]],
  ['store_20initialization_136',['History store initialization',['../arch-hs.html#arch_hs_initialize',1,'']]],
  ['store_20table_137',['Tombstones in the history store table',['../arch-hs.html#arch_hs_table_tombstone',1,'']]],
  ['store_20table_20structure_138',['History store table structure',['../arch-hs.html#arch_hs_table',1,'']]],
  ['stores_139',['stores',['../arch-row-column.html#row_column_flcs',1,'Fixed length column-stores'],['../arch-row-column.html#row_column_rs',1,'Row-stores'],['../arch-row-column.html#row_column_vlcs',1,'Variable length column-stores']]],
  ['storing_20checkpoint_20metadata_140',['Storing Checkpoint Metadata',['../arch-metadata.html#metadata_checkpoint',1,'']]],
  ['str_141',['str',['../struct_w_t___c_o_n_f_i_g___i_t_e_m.html#aa0ce7d30a32600e16824966c638ee45f',1,'WT_CONFIG_ITEM']]],
  ['stream_142',['File Stream',['../arch-fs-os.html#file_stream',1,'']]],
  ['strerror_143',['strerror',['../group__wt__ext.html#a5ccafb43c81bdd2ab9178ed698d6d34c',1,'WT_EXTENSION_API::strerror'],['../struct_w_t___s_e_s_s_i_o_n.html#a5fd589634b16fbce8fd9d5c1df1b3e09',1,'WT_SESSION::strerror()']]],
  ['string_144',['The Compiled String',['../arch-config-compile.html#compile_returned_string',1,'']]],
  ['string_20compilation_145',['Configuration String Compilation',['../arch-config-compile.html',1,'arch-toc-api']]],
  ['string_20format_146',['Flat string format',['../message_handling.html#message_handling_output_flat_string',1,'']]],
  ['string_20parsing_20examples_147',['Configuration String Parsing examples',['../struct_w_t___c_o_n_f_i_g___p_a_r_s_e_r.html#config_parse_examples',1,'']]],
  ['strings_148',['Configuration Strings',['../config_strings.html',1,'programming']]],
  ['strings_149',['strings',['../custom_data_sources.html#custom_ds_config',1,'Configuration strings'],['../custom_data_sources.html#custom_ds_config_add',1,'Creating data-specific configuration strings'],['../custom_data_sources.html#custom_ds_config_parsing',1,'Parsing configuration strings']]],
  ['struct_5fpack_150',['struct_pack',['../group__wt__ext.html#a353dd240d0f7b32910d1bb97c0762ee8',1,'WT_EXTENSION_API']]],
  ['struct_5fsize_151',['struct_size',['../group__wt__ext.html#af0256206a330cf5b8ec738c1ec60c6a9',1,'WT_EXTENSION_API']]],
  ['struct_5funpack_152',['struct_unpack',['../group__wt__ext.html#a4bff77f867b83e76a65426eabd9e6da3',1,'WT_EXTENSION_API']]],
  ['structure_153',['structure',['../arch-cache.html#arch_cache_structure',1,'Cache structure'],['../arch-hs.html#arch_hs_table',1,'History store table structure'],['../arch-config-compile.html#compile_conf',1,'The WT_CONF structure'],['../arch-config-compile.html#compile_conf_value',1,'The WT_CONF_VALUE structure']]],
  ['structured_20merge_20trees_154',['Log-Structured Merge Trees',['../lsm.html',1,'programming']]],
  ['structures_155',['Structures',['../arch-tiered-storage.html#ts_metadata',1,'Metadata and Associated Data Structures'],['../arch-config-compile.html#compile_position_independent',1,'Position Independent Structures']]],
  ['structures_20and_20algorithms_156',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['structures_20in_20wiredtiger_157',['Configurable page structures in WiredTiger',['../tune_page_size_and_comp.html#configurable_page_struct',1,'']]],
  ['subsystem_20data_20structures_20and_20algorithms_158',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['sugar_20and_20composite_20keys_159',['Syntactic Sugar and Composite Keys',['../arch-config-compile.html#compile_composite',1,'']]],
  ['summarizing_20compression_20in_20wiredtiger_160',['Table summarizing compression in WiredTiger',['../tune_page_size_and_comp.html#table_compress',1,'']]],
  ['summary_161',['Summary',['../tool-optrack.html#autotoc_md39',1,'']]],
  ['support_162',['Support',['../arch-toc-platform.html',1,'Cross-Platform Support'],['../arch-fs-os.html',1,'File System Interface and Operating System Support'],['../arch-fs-os.html#filesystem_usage',1,'Multiple System Architecture Support']]],
  ['support_163',['In-memory support',['../arch-fs-os.html#file_in_memory',1,'']]],
  ['support_20for_20multiple_20operating_20systems_164',['Support for Multiple Operating Systems',['../arch-fs-os.html#multiple_os',1,'']]],
  ['supported_20cpu_20architectures_165',['Supported CPU architectures',['../portability.html#cpu',1,'']]],
  ['supporting_20configuration_20compilation_166',['Scripts Supporting Configuration Compilation',['../arch-config-compile.html#compile_scripts',1,'']]],
  ['sweep_167',['Sweep',['../arch-dhandle.html#dhandle_dhandle_session_cache_sweep',1,'Dhandle Session Cache Sweep'],['../arch-dhandle.html#dhandle_sweep_server_dhandle_sweep',1,'Sweep-Server Dhandle Sweep']]],
  ['sweep_168',['Session cursor sweep',['../arch-cursor.html#arch_cursor_sweep',1,'']]],
  ['sweep_20server_20dhandle_20sweep_169',['Sweep-Server Dhandle Sweep',['../arch-dhandle.html#dhandle_sweep_server_dhandle_sweep',1,'']]],
  ['synopsis_170',['SYNOPSIS',['../command_line.html#util_global_synopsis',1,'']]],
  ['synopsis_171',['Synopsis',['../command_line.html#util_alter_synopsis',1,'Synopsis'],['../command_line.html#util_backup_synopsis',1,'Synopsis'],['../command_line.html#util_compact_synopsis',1,'Synopsis'],['../command_line.html#util_copyright_synopsis',1,'Synopsis'],['../command_line.html#util_create_synopsis',1,'Synopsis'],['../command_line.html#util_downgrade_synopsis',1,'Synopsis'],['../command_line.html#util_drop_synopsis',1,'Synopsis'],['../command_line.html#util_dump_synopsis',1,'Synopsis'],['../command_line.html#util_list_synopsis',1,'Synopsis'],['../command_line.html#util_load_synopsis',1,'Synopsis'],['../command_line.html#util_loadtext_synopsis',1,'Synopsis'],['../command_line.html#util_printlog_synopsis',1,'Synopsis'],['../command_line.html#util_read_synopsis',1,'Synopsis'],['../command_line.html#util_rename_synopsis',1,'Synopsis'],['../command_line.html#util_salvage_synopsis',1,'Synopsis'],['../command_line.html#util_stat_synopsis',1,'Synopsis'],['../command_line.html#util_truncate_synopsis',1,'Synopsis'],['../command_line.html#util_verify_synopsis',1,'Synopsis'],['../command_line.html#util_write_synopsis',1,'Synopsis']]],
  ['syntactic_20sugar_20and_20composite_20keys_172',['Syntactic Sugar and Composite Keys',['../arch-config-compile.html#compile_composite',1,'']]],
  ['system_20and_20file_20handle_20interfaces_173',['WiredTiger File System and File Handle Interfaces',['../arch-fs-os.html#file_system_and_handle',1,'']]],
  ['system_20and_20handle_20customization_174',['File System and Handle Customization',['../arch-fs-os.html#file_customization',1,'']]],
  ['system_20architecture_20support_175',['Multiple System Architecture Support',['../arch-fs-os.html#filesystem_usage',1,'']]],
  ['system_20buffer_20cache_176',['System buffer cache',['../tune_system_buffer_cache.html',1,'programming']]],
  ['system_20interface_177',['System Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_system',1,'Cloud File System Interface'],['../arch-fs-os.html#file_system',1,'File System Interface']]],
  ['system_20interface_20and_20operating_20system_20support_178',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['system_20name_20space_179',['File system name space',['../namespace.html#namespace_filesystem',1,'']]],
  ['system_20support_180',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['systems_181',['Systems',['../custom_file_systems.html',1,'Custom File Systems'],['../arch-fs-os.html#multiple_os',1,'Support for Multiple Operating Systems']]],
  ['systems_182',['Remote file systems',['../filesystems.html#remote',1,'']]]
];
