var searchData=
[
  ['d3_20graph_0',['Data Driven Documents (D3) graph',['../tool-statistics.html#autotoc_md52',1,'']]],
  ['data_1',['Data',['../packing.html',1,'Packing and Unpacking Data'],['../data_sources.html#data_statistics',1,'Statistics Data']]],
  ['data_2',['data',['../arch-eviction.html#clean_dirty_data',1,'Clean vs dirty data'],['../group__wt.html#a57f5e62aa968275d7e398cfa70e49450',1,'WT_ITEM::data'],['../group__wt.html#a263d61ab5ccb1fb61f1d5c32d42e7ad1',1,'WT_MODIFY::data'],['../data_sources.html#data_indices',1,'Table Index data']]],
  ['data_20between_20memory_20and_20disk_3',['Moving Data Between Memory and Disk',['../arch-toc-mem-disk.html',1,'arch-index']]],
  ['data_20driven_20documents_20d3_20graph_4',['Data Driven Documents (D3) graph',['../tool-statistics.html#autotoc_md52',1,'']]],
  ['data_20file_20checkpoint_5',['Data file checkpoint',['../arch-tiered-storage.html#ts_checkpoint_data_file',1,'']]],
  ['data_20file_20format_6',['Data File Format',['../arch-data-file.html',1,'arch-toc-mem-disk']]],
  ['data_20file_20format_20and_20layout_7',['Data File Format and Layout',['../arch-data-file.html#data_file_format',1,'']]],
  ['data_20file_20functions_8',['Data File Functions',['../arch-data-file.html#data_file_functions',1,'']]],
  ['data_20files_9',['Data Files',['../arch-schema.html#schema_files',1,'']]],
  ['data_20for_20viewing_10',['Preparing data for viewing',['../tool-optrack.html#autotoc_md35',1,'']]],
  ['data_20formats_11',['Data Formats',['../arch-schema.html#schema_data_formats',1,'']]],
  ['data_20handle_20creation_12',['Data Handle Creation',['../arch-dhandle.html#dhandle_data_handle_creation',1,'']]],
  ['data_20handle_20lifecycle_13',['Data Handle Lifecycle',['../arch-dhandle.html#dhandle_data_handle_lifecycle',1,'']]],
  ['data_20handle_20reference_20counts_14',['Data Handle Reference Counts',['../arch-dhandle.html#dhandle_data_handle_reference_counts',1,'']]],
  ['data_20handles_15',['Data Handles',['../arch-dhandle.html',1,'Data Handles'],['../arch-session.html#arch_session_dhandles',1,'Data Handles']]],
  ['data_20handles_16',['File cursors, Btrees and data handles',['../arch-cursor.html#arch_cursor_dhandle',1,'']]],
  ['data_20life_20cycle_17',['Data life cycle',['../tune_page_size_and_comp.html#data_life_cycle',1,'']]],
  ['data_20model_20and_20worldview_18',['Timestamp data model and worldview',['../arch-timestamp.html#arch-timestamp-model',1,'']]],
  ['data_20organization_19',['Data Organization',['../arch-toc-data-org.html',1,'arch-index']]],
  ['data_20source_20wt_5fbtree_20',['B-Tree Data Source (WT_BTREE)',['../arch-btree.html#btree_btree_data_source',1,'']]],
  ['data_20sources_21',['Data Sources',['../custom_data_sources.html',1,'Custom Data Sources'],['../arch-toc-data-src.html',1,'Data Sources'],['../data_sources.html',1,'Data Sources']]],
  ['data_20sources_22',['Builtin data sources',['../data_sources.html#data_builtin',1,'']]],
  ['data_20specific_20configuration_20strings_23',['Creating data-specific configuration strings',['../custom_data_sources.html#custom_ds_config_add',1,'']]],
  ['data_20structures_24',['Metadata and Associated Data Structures',['../arch-tiered-storage.html#ts_metadata',1,'']]],
  ['data_20structures_20and_20algorithms_25',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['data_20translation_26',['Data translation',['../arch-cursor.html#arch_cursor_raw',1,'']]],
  ['data_20with_20cursors_27',['Accessing data with cursors',['../basic_api.html#basic_cursors',1,'']]],
  ['data_3a_20part_201_28',['Looking at the data: Part 1',['../tool-optrack.html#autotoc_md36',1,'']]],
  ['data_3a_20part_202_29',['Looking at the data: Part 2',['../tool-optrack.html#autotoc_md38',1,'']]],
  ['database_30',['database',['../basic_api.html#basic_connection',1,'Connecting to a database'],['../arch-backup.html#autotoc_md1',1,'Full database']]],
  ['database_20configuration_31',['Database Configuration',['../database_config.html',1,'admin']]],
  ['database_20directory_32',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['database_20directory_20permissions_33',['Database directory permissions',['../security.html#directory_permissions',1,'']]],
  ['database_20files_34',['Database Files',['../arch-data-file.html#data_file_database_files',1,'']]],
  ['database_20handles_35',['Readonly configuration and multiple database handles',['../readonly.html#readonly_handles',1,'']]],
  ['database_20home_20directory_36',['Database Home Directory',['../home.html',1,'admin']]],
  ['database_20read_20only_20configuration_20considerations_37',['Database read-only configuration considerations',['../readonly.html#readonly_config',1,'']]],
  ['database_20read_20only_20mode_38',['Database read-only mode',['../readonly.html',1,'programming']]],
  ['databases_39',['databases',['../in_memory.html',1,'In-memory databases'],['../durability_overview.html#explain_durability_in_memory',1,'In-memory databases'],['../admin.html',1,'Managing WiredTiger databases'],['../upgrade.html',1,'Upgrading and downgrading databases']]],
  ['debug_20copy_40',['Debug copy',['../arch-cursor.html#arch_cursor_debug_copy',1,'']]],
  ['debugging_41',['Debugging',['../debugging.html',1,'programming']]],
  ['decompress_42',['decompress',['../group__wt__ext.html#a12e35ffbbe63b041c0571fb622b7f9da',1,'WT_COMPRESSOR']]],
  ['decrypt_43',['decrypt',['../group__wt__ext.html#abad5447ebeb99d06b9024df435cffc26',1,'WT_ENCRYPTOR']]],
  ['definition_44',['Definition',['../arch-connection.html#arch_conn_def',1,'Definition'],['../arch-row-column.html#row_column_definition',1,'Definition'],['../arch-session.html#arch_session_def',1,'Definition']]],
  ['definitions_45',['Introduction and Definitions',['../arch-tiered-storage.html#ts_intro',1,'']]],
  ['deleted_20pages_46',['Deleted Pages',['../arch-fast-truncate.html#ft_deleted_pages',1,'']]],
  ['deleted_20pages_47',['deleted pages',['../arch-fast-truncate.html#ft_flcs',1,'FLCS and deleted pages'],['../arch-fast-truncate.html#ft_deleted_generation',1,'Generation of other deleted pages'],['../arch-fast-truncate.html#ft_page_skip',1,'Skipping deleted pages']]],
  ['deleted_20pages_20and_20fast_20truncate_48',['Deleted Pages and Fast-Truncate',['../arch-fast-truncate.html',1,'arch-toc-fundamentals']]],
  ['description_49',['DESCRIPTION',['../command_line.html#util_global_description',1,'']]],
  ['description_20of_20lsm_20trees_50',['Description of LSM trees',['../lsm.html#lsm_description',1,'']]],
  ['descriptor_20blocks_51',['Descriptor blocks',['../arch-block.html#desc_block',1,'']]],
  ['details_52',['details',['../arch-block.html#block_implementation',1,'Block manager implementation details'],['../arch-usage-patterns.html#growable-arrays-further-details',1,'Further details'],['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_safety',1,'Safety rationale and details']]],
  ['development_53',['Internal WiredTiger Development',['../arch-toc-int-wt-dev.html',1,'arch-index']]],
  ['dhandle_20session_20cache_20sweep_54',['Dhandle Session Cache Sweep',['../arch-dhandle.html#dhandle_dhandle_session_cache_sweep',1,'']]],
  ['dhandle_20sweep_55',['Sweep-Server Dhandle Sweep',['../arch-dhandle.html#dhandle_sweep_server_dhandle_sweep',1,'']]],
  ['diagnostic_20categories_56',['Diagnostic Categories',['../debugging.html#diagnostic_categories',1,'']]],
  ['diagnostic_20code_20blocks_57',['Diagnostic Code Blocks',['../debugging.html#diagnostic_code_blocks',1,'']]],
  ['diagnostics_58',['Configuring runtime diagnostics',['../debugging.html#extra_diagnostics_configuration',1,'']]],
  ['direct_20i_20o_59',['Direct I/O',['../tune_system_buffer_cache.html#tuning_system_buffer_cache_direct_io',1,'']]],
  ['directory_60',['Database Home Directory',['../home.html',1,'admin']]],
  ['directory_61',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['directory_20permissions_62',['Database directory permissions',['../security.html#directory_permissions',1,'']]],
  ['dirty_20data_63',['Clean vs dirty data',['../arch-eviction.html#clean_dirty_data',1,'']]],
  ['dirty_20eviction_64',['Clean vs dirty eviction',['../arch-eviction.html#clean_dirty_eviction',1,'']]],
  ['disk_65',['Moving Data Between Memory and Disk',['../arch-toc-mem-disk.html',1,'arch-index']]],
  ['disk_20concepts_66',['On Disk Concepts',['../arch-toc-on-disk.html',1,'arch-index']]],
  ['disk_20format_67',['On-disk format',['../arch-fast-truncate.html#ft_on_disk_format',1,'']]],
  ['disk_20page_20format_20and_20layout_68',['On-Disk Page Format and Layout',['../arch-data-file.html#data_file_on_disk_page_format',1,'']]],
  ['disk_20pages_69',['Handling of timestamps in updates and disk pages',['../arch-timestamp.html#arch-timestamp-handling',1,'']]],
  ['distribution_70',['3rd party software included in the WiredTiger distribution',['../license.html#license_distribution',1,'']]],
  ['documents_20d3_20graph_71',['Data Driven Documents (D3) graph',['../tool-statistics.html#autotoc_md52',1,'']]],
  ['does_20operation_20tracking_20work_72',['How does operation tracking work?',['../tool-optrack.html#autotoc_md26',1,'']]],
  ['downgrade_73',['wt downgrade',['../command_line.html#util_downgrade',1,'']]],
  ['downgrading_20databases_74',['Upgrading and downgrading databases',['../upgrade.html',1,'programming']]],
  ['driven_20documents_20d3_20graph_75',['Data Driven Documents (D3) graph',['../tool-statistics.html#autotoc_md52',1,'']]],
  ['drop_76',['Drop',['../arch-schema.html#schema_drop',1,'']]],
  ['drop_77',['drop',['../group__wt__ext.html#a4569fa21343c2681357dedb4dd5facc1',1,'WT_DATA_SOURCE::drop'],['../struct_w_t___s_e_s_s_i_o_n.html#adf785ef53c16d9dcc77e22cc04c87b70',1,'WT_SESSION::drop()'],['../command_line.html#util_drop',1,'wt drop']]],
  ['dry_20run_20mode_78',['Dry-run mode',['../arch-rts.html#dry-run-mode',1,'']]],
  ['dump_79',['wt dump',['../command_line.html#util_dump',1,'']]],
  ['dump_20cursors_80',['Dump cursors',['../arch-cursor.html#arch_cursor_dump',1,'']]],
  ['dump_20format_81',['dump format',['../dump_formats.html#dump_formats_json',1,'JSON dump format'],['../dump_formats.html#dump_formats_text',1,'Text dump format']]],
  ['dump_20formats_82',['Dump Formats',['../dump_formats.html',1,'command_line']]],
  ['duplicate_20backup_20cursors_83',['Duplicate backup cursors',['../backup.html#backup_duplicate',1,'']]],
  ['duplicating_20cursors_84',['Duplicating cursors',['../arch-cursor.html#arch_cursor_duplicate',1,'']]],
  ['durability_85',['durability',['../durability_checkpoint.html',1,'Checkpoint-level durability'],['../durability_log.html',1,'Commit-level durability'],['../tune_durability.html',1,'Commit-level durability'],['../durability_log.html#commit_durability_enable',1,'Enabling commit-level durability'],['../durability_log.html#commit_durability_tuning',1,'Tuning commit-level durability']]],
  ['durability_20and_20backups_86',['Checkpoint durability and backups',['../durability_checkpoint.html#checkpoint_backup',1,'']]],
  ['durability_20and_20logs_87',['Commit-level durability and logs',['../durability_log.html#commit_durability_logs',1,'']]],
  ['durability_20and_20timestamps_88',['durability and timestamps',['../timestamp_model.html#timestamps_durability_checkpoint',1,'Checkpoint durability and timestamps'],['../timestamp_model.html#timestamps_durability_commit',1,'Logged objects, commit-level durability and timestamps']]],
  ['durability_20overview_89',['Durability overview',['../durability_overview.html',1,'programming']]],
  ['durability_20without_20timestamps_90',['durability without timestamps',['../durability_overview.html#explain_durability_checkpoint',1,'Checkpoint durability (without timestamps)'],['../durability_overview.html#explain_durability_commit',1,'Commit-level durability (without timestamps)']]],
  ['durable_5ftimestamp_20timestamp_91',['Setting the global &quot;durable_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_set_api_durable_timestamp',1,'']]]
];
