var searchData=
[
  ['pack_5fclose_0',['pack_close',['../group__wt__ext.html#a6793729220ccd2bec82a52e949cd63ca',1,'WT_EXTENSION_API']]],
  ['pack_5fint_1',['pack_int',['../group__wt__ext.html#a5ec2af7659fe872ba1a65f4f05b961ca',1,'WT_EXTENSION_API']]],
  ['pack_5fitem_2',['pack_item',['../group__wt__ext.html#ac55b0c42dc2eda2774cc2cf8668961fe',1,'WT_EXTENSION_API']]],
  ['pack_5fstart_3',['pack_start',['../group__wt__ext.html#aa465dc00b4fdcb127963da236f322652',1,'WT_EXTENSION_API']]],
  ['pack_5fstr_4',['pack_str',['../group__wt__ext.html#a1a46e4d4a21195c00fb20cf5b3b2768c',1,'WT_EXTENSION_API']]],
  ['pack_5fuint_5',['pack_uint',['../group__wt__ext.html#aaf38b597d369fd073a4501aba3b14954',1,'WT_EXTENSION_API']]],
  ['packing_20and_20unpacking_20data_6',['Packing and Unpacking Data',['../packing.html',1,'schema']]],
  ['packing_20examples_7',['Packing Examples',['../group__wt.html#pack_examples',1,'']]],
  ['page_20format_20and_20layout_8',['On-Disk Page Format and Layout',['../arch-data-file.html#data_file_on_disk_page_format',1,'']]],
  ['page_20reconciliation_9',['Internal page reconciliation',['../arch-fast-truncate.html#ft_internal_reconciliation',1,'']]],
  ['page_20size_20and_20compression_10',['Tuning page size and compression',['../tune_page_size_and_comp.html',1,'programming']]],
  ['page_20structures_20in_20wiredtiger_11',['Configurable page structures in WiredTiger',['../tune_page_size_and_comp.html#configurable_page_struct',1,'']]],
  ['page_20types_12',['Page Types',['../arch-data-file.html#data_file_page_types',1,'']]],
  ['page_5fdel_20field_13',['The instantiated flag and the page_del field',['../arch-fast-truncate.html#ft_instantiated_instantiated',1,'']]],
  ['pages_14',['Pages',['../arch-fast-truncate.html#ft_deleted_pages',1,'Deleted Pages'],['../arch-prefetch.html#prefetch_algorithm_find_pages',1,'Finding Candidate Pages'],['../arch-fast-truncate.html#ft_instantiated_pages',1,'Instantiated Pages']]],
  ['pages_15',['pages',['../arch-fast-truncate.html#ft_flcs',1,'FLCS and deleted pages'],['../arch-fast-truncate.html#ft_deleted_generation',1,'Generation of other deleted pages'],['../arch-timestamp.html#arch-timestamp-handling',1,'Handling of timestamps in updates and disk pages'],['../arch-rts.html#iterating-over-pages',1,'Iterating over pages'],['../tune_transparent_huge_pages.html',1,'Linux transparent huge pages'],['../arch-block.html#read',1,'Reading files and pages'],['../arch-eviction.html#eviction_related',1,'Related pages'],['../arch-logging.html#log_related',1,'Related pages'],['../arch-fast-truncate.html#ft_page_skip',1,'Skipping deleted pages']]],
  ['pages_20and_20fast_20truncate_16',['Deleted Pages and Fast-Truncate',['../arch-fast-truncate.html',1,'arch-toc-fundamentals']]],
  ['pages_20into_20memory_17',['Skipping reading unnecessary pages into memory',['../arch-rts.html#rts-page-skip',1,'']]],
  ['pairs_18',['Key/Value pairs',['../keyvalue.html',1,'schema']]],
  ['parameters_19',['Parameters',['../arch-config-compile.html#compile_bind',1,'Binding Parameters'],['../arch-config-compile.html#compile_unbound',1,'Compiling Unbound Parameters']]],
  ['parameters_20',['Storage source parameters',['../custom_storage_sources.html#storage_parameters',1,'']]],
  ['parsing_20configuration_20strings_21',['Parsing configuration strings',['../custom_data_sources.html#custom_ds_config_parsing',1,'']]],
  ['parsing_20examples_22',['Configuration String Parsing examples',['../struct_w_t___c_o_n_f_i_g___p_a_r_s_e_r.html#config_parse_examples',1,'']]],
  ['part_201_23',['Looking at the data: Part 1',['../tool-optrack.html#autotoc_md36',1,'']]],
  ['part_202_24',['Looking at the data: Part 2',['../tool-optrack.html#autotoc_md38',1,'']]],
  ['party_20software_20always_20included_20in_20the_20wiredtiger_20library_25',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['party_20software_20included_20in_20the_20wiredtiger_20distribution_26',['3rd party software included in the WiredTiger distribution',['../license.html#license_distribution',1,'']]],
  ['party_20software_20optionally_20included_20in_20the_20wiredtiger_20library_3a_20ppc64_27',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['party_20software_20optionally_20included_20in_20the_20wiredtiger_20library_3a_20s390x_28',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['passing_20with_20acquire_20and_20release_29',['Message passing with acquire and release',['../arch-usage-patterns.html#message-passing',1,'']]],
  ['paths_30',['Absolute paths',['../security.html#absolute_path',1,'']]],
  ['patterns_31',['Usage Patterns',['../arch-usage-patterns.html',1,'arch-toc-int-wt-dev']]],
  ['per_20process_20shared_20caches_32',['Per-process shared caches',['../shared_cache.html',1,'programming']]],
  ['percentage_33',['split_pct (split percentage)',['../tune_page_size_and_comp.html#split_pct',1,'']]],
  ['perf_20with_20wiredtiger_34',['Running perf with WiredTiger',['../tool-perf.html#autotoc_md43',1,'']]],
  ['performance_20monitoring_35',['Performance Monitoring',['../tool-perf.html',1,'tool-index']]],
  ['performance_20monitoring_20with_20statistics_36',['Performance monitoring with statistics',['../tune_statistics.html',1,'programming']]],
  ['permissions_37',['permissions',['../security.html#directory_permissions',1,'Database directory permissions'],['../security.html#file_permissions',1,'File permissions']]],
  ['persisted_20content_38',['Persisted content',['../chunkcache.html#persistence',1,'']]],
  ['persistence_39',['Cursor persistence',['../tune_cursor_persist.html',1,'programming']]],
  ['phase_40',['Checkpoint Prepare Phase',['../arch-tiered-storage.html#ts_checkpoint_prepare',1,'']]],
  ['pieces_20of_20the_20implementation_41',['Pointers to pieces of the implementation',['../arch-fast-truncate.html#ft_pointers',1,'']]],
  ['pinned_20content_42',['Pinned Content',['../chunkcache.html#pinned',1,'']]],
  ['pinned_20timestamp_43',['Reading the &quot;pinned&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_pinned',1,'']]],
  ['plans_44',['Projections and plans',['../arch-cursor.html#arch_cursor_projections',1,'']]],
  ['platform_20support_45',['Cross-Platform Support',['../arch-toc-platform.html',1,'arch-index']]],
  ['pointers_20to_20pieces_20of_20the_20implementation_46',['Pointers to pieces of the implementation',['../arch-fast-truncate.html#ft_pointers',1,'']]],
  ['populating_20the_20pre_20fetch_20queue_47',['Populating the Pre-fetch Queue',['../arch-prefetch.html#prefetch_algorithm_populate_queue',1,'']]],
  ['portability_48',['General information on portability',['../portability.html',1,'index']]],
  ['position_20after_20error_49',['Cursor position after error',['../cursor_ops.html#cursor_error',1,'']]],
  ['position_20independent_20structures_50',['Position Independent Structures',['../arch-config-compile.html#compile_position_independent',1,'']]],
  ['positioning_20a_20cursor_51',['Positioning a cursor',['../cursor_ops.html#cursor_position',1,'']]],
  ['posix_20compliance_52',['POSIX compliance',['../portability.html#posix',1,'']]],
  ['posix_20linux_20bsd_20os_20x_20_3a_53',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['ppc64_54',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['pre_20compilation_55',['Initial Pre-Compilation',['../arch-config-compile.html#compile_initial',1,'']]],
  ['pre_20fetch_56',['Pre-fetch',['../arch-prefetch.html',1,'arch-toc-mem-disk']]],
  ['pre_20fetch_20algorithm_57',['Pre-fetch Algorithm',['../arch-prefetch.html#prefetch_algorithm',1,'']]],
  ['pre_20fetch_20api_58',['Pre-fetch API',['../arch-prefetch.html#prefetch_api',1,'']]],
  ['pre_20fetch_20queue_59',['Populating the Pre-fetch Queue',['../arch-prefetch.html#prefetch_algorithm_populate_queue',1,'']]],
  ['pre_20fetch_20queue_20remain_20valid_60',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['pre_20fetching_20content_20into_20the_20cache_61',['Pre-fetching Content Into the Cache',['../arch-prefetch.html#prefetch_algorithm_process_pages',1,'']]],
  ['pre_20fetching_20useful_62',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['pre_20fetching_20when_20is_20pre_20fetching_20useful_63',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['pre_5fsize_64',['pre_size',['../group__wt__ext.html#a8b72f263db4faea37d8362ebc4725990',1,'WT_COMPRESSOR']]],
  ['precise_20control_20of_20the_20outlier_20thresholds_65',['Getting a more precise control of the outlier thresholds',['../tool-optrack.html#autotoc_md37',1,'']]],
  ['prefixes_66',['Storage Sources, Buckets, and Prefixes',['../arch-tiered-storage.html#ts_buckets',1,'']]],
  ['prepare_20phase_67',['Checkpoint Prepare Phase',['../arch-tiered-storage.html#ts_checkpoint_prepare',1,'']]],
  ['prepare_20timestamp_68',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]],
  ['prepare_20timestamp_20rounding_69',['Automatic prepare timestamp rounding',['../timestamp_prepare_roundup.html',1,'programming']]],
  ['prepare_20with_20timestamps_70',['Using transaction prepare with timestamps',['../timestamp_prepare.html',1,'programming']]],
  ['prepare_20your_20workload_71',['Prepare your workload',['../tool-optrack.html#autotoc_md29',1,'']]],
  ['prepare_5ftransaction_72',['prepare_transaction',['../struct_w_t___s_e_s_s_i_o_n.html#a96b8a369610c8cbb08b8a7c504fd1008',1,'WT_SESSION']]],
  ['prepared_20transactions_73',['Prepared Transactions',['../arch-transaction.html#arch-transaction-prepare',1,'']]],
  ['prepared_20transactions_74',['Prepared transactions',['../arch-timestamp.html#arch-timestamp-prepare',1,'']]],
  ['prepared_20transactions_75',['History store and prepared transactions',['../arch-hs.html#arch_hs_prepared',1,'']]],
  ['prepared_20transactions_20by_20rounding_20up_20the_20prepare_20timestamp_76',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]],
  ['preparing_20data_20for_20viewing_77',['Preparing data for viewing',['../tool-optrack.html#autotoc_md35',1,'']]],
  ['prerequisites_78',['Prerequisites',['../tool-optrack.html#autotoc_md28',1,'']]],
  ['prev_79',['prev',['../struct_w_t___c_u_r_s_o_r.html#a43d6664d2f68902aa63f933864242e76',1,'WT_CURSOR']]],
  ['printing_20metadata_20with_20the_20wt_20utility_80',['Printing metadata with the wt utility',['../arch-metadata.html#metadata_wt_util',1,'']]],
  ['printlog_81',['wt printlog',['../command_line.html#util_printlog',1,'']]],
  ['process_20environment_20name_20space_82',['Process&apos; environment name space',['../namespace.html#namespace_env',1,'']]],
  ['process_20shared_20caches_83',['Per-process shared caches',['../shared_cache.html',1,'programming']]],
  ['process_20the_20traces_84',['Step 3: Process the traces',['../tool-xray.html#autotoc_md62',1,'']]],
  ['processing_20the_20log_20files_85',['Processing the log files',['../tool-optrack.html#autotoc_md34',1,'']]],
  ['production_20quality_86',['Production quality',['../overview.html#quality',1,'']]],
  ['profiling_87',['Sampling events (profiling)',['../tool-perf.html#autotoc_md45',1,'']]],
  ['projections_88',['Projections',['../cursors.html#cursor_projections',1,'Projections'],['../schema.html',1,'Schema, Columns, Column Groups, Indices and Projections']]],
  ['projections_89',['Index cursor projections',['../schema.html#schema_index_projections',1,'']]],
  ['projections_20and_20plans_90',['Projections and plans',['../arch-cursor.html#arch_cursor_projections',1,'']]],
  ['properties_91',['Properties',['../arch-transaction.html#ACID',1,'']]],
  ['properties_92',['Tutorial: transactions and ACID properties',['../explain_acid.html',1,'programming']]],
  ['pseudocode_93',['Pseudocode',['../arch-usage-patterns.html#win-the-race-pseudocode',1,'Example Pseudocode'],['../arch-usage-patterns.html#write-while-stable-pseudocode',1,'Pseudocode']]],
  ['python_20api_94',['Python API',['../arch-python.html',1,'arch-toc-tools']]],
  ['python_20modules_95',['Install the python modules',['../tool-optrack.html#autotoc_md30',1,'']]]
];
