var searchData=
[
  ['c_20c_20tests_0',['C C Tests',['../build-posix.html#posix_ctest',1,'Running WiredTiger C/C++ Tests'],['../build-windows.html#windows_ctest',1,'Running WiredTiger C/C++ Tests']]],
  ['c_20compiler_20and_20enable_20libfuzzer_1',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['c_20language_20name_20space_2',['C language name space',['../namespace.html#namespace_c',1,'']]],
  ['c_20tests_3',['C Tests',['../build-posix.html#posix_ctest',1,'Running WiredTiger C/C++ Tests'],['../build-windows.html#windows_ctest',1,'Running WiredTiger C/C++ Tests']]],
  ['cache_4',['Cache',['../arch-cache.html',1,'Cache'],['../arch-prefetch.html#prefetch_algorithm_process_pages',1,'Pre-fetching Content Into the Cache']]],
  ['cache_5',['cache',['../chunkcache.html',1,'Chunk cache'],['../tune_system_buffer_cache.html',1,'System buffer cache']]],
  ['cache_20and_20eviction_20locks_6',['Cache and Eviction locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-cache-and-eviction',1,'']]],
  ['cache_20and_20eviction_20tuning_7',['Cache and eviction tuning',['../tune_cache.html',1,'programming']]],
  ['cache_20busyness_8',['Considering Current Cache Busyness',['../arch-prefetch.html#prefetch_other_cache_busyness',1,'']]],
  ['cache_20resident_20objects_9',['Cache resident objects',['../tune_cache.html#tuning_cache_resident',1,'']]],
  ['cache_20size_10',['Cache size',['../tune_cache.html#tuning_cache_size',1,'']]],
  ['cache_20size_20and_20content_11',['Cache size and content',['../arch-cache.html#arch_cache_size',1,'']]],
  ['cache_20structure_12',['Cache structure',['../arch-cache.html#arch_cache_structure',1,'']]],
  ['cache_20sweep_13',['Dhandle Session Cache Sweep',['../arch-dhandle.html#dhandle_dhandle_session_cache_sweep',1,'']]],
  ['caches_14',['caches',['../overview.html#cache',1,'Hot caches'],['../shared_cache.html',1,'Per-process shared caches'],['../arch-cache.html#arch_cache_shared',1,'Shared caches']]],
  ['caching_15',['Cursor caching',['../arch-cursor.html#arch_cursor_caching',1,'']]],
  ['call_20configuration_16',['call configuration',['../durability_log.html#commit_durability_flush_config',1,'Flush call configuration'],['../tune_durability.html#tune_durability_flush_config',1,'Flush call configuration']]],
  ['calls_17',['calls',['../operation_tracking.html',1,'Track function calls'],['../transactions_api.html',1,'Transactional API calls']]],
  ['candidate_20pages_18',['Finding Candidate Pages',['../arch-prefetch.html#prefetch_algorithm_find_pages',1,'']]],
  ['capacity_20tuning_19',['Capacity tuning',['../tune_capacity.html',1,'programming']]],
  ['cases_20',['Use cases',['../arch-usage-patterns.html#slotted-arrays-use-cases',1,'']]],
  ['categories_21',['Categories',['../verbose_messaging.html#verbosity_configuration',1,'Configuring Verbose Categories'],['../debugging.html#diagnostic_categories',1,'Diagnostic Categories'],['../verbose_messaging.html#verbosity_categories',1,'Verbosity Categories']]],
  ['caveats_22',['Caveats',['../lsm.html#lsm_caveats',1,'']]],
  ['changing_20compiler_20or_20loader_20options_23',['Changing compiler or loader options',['../build-posix.html#posix_compiler',1,'']]],
  ['checkpoint_24',['Checkpoint',['../arch-checkpoint.html',1,'arch-toc-on-disk']]],
  ['checkpoint_25',['checkpoint',['../group__wt__ext.html#a0ab6e469464fa132901f3292934ad26c',1,'WT_DATA_SOURCE::checkpoint'],['../struct_w_t___s_e_s_s_i_o_n.html#a6550c9079198955c5071583941c85bbf',1,'WT_SESSION::checkpoint()'],['../arch-tiered-storage.html#ts_checkpoint_data_file',1,'Data file checkpoint']]],
  ['checkpoint_20algorithm_26',['The checkpoint algorithm',['../arch-checkpoint.html#autotoc_md6',1,'']]],
  ['checkpoint_20and_20schema_20locks_27',['Checkpoint and Schema locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-checkpoint-schema',1,'']]],
  ['checkpoint_20cursors_28',['Checkpoint cursors',['../durability_checkpoint.html#checkpoint_cursors',1,'']]],
  ['checkpoint_20durability_20and_20backups_29',['Checkpoint durability and backups',['../durability_checkpoint.html#checkpoint_backup',1,'']]],
  ['checkpoint_20durability_20and_20timestamps_30',['Checkpoint durability and timestamps',['../timestamp_model.html#timestamps_durability_checkpoint',1,'']]],
  ['checkpoint_20durability_20without_20timestamps_31',['Checkpoint durability (without timestamps)',['../durability_overview.html#explain_durability_checkpoint',1,'']]],
  ['checkpoint_20generations_32',['Checkpoint generations',['../arch-checkpoint.html#autotoc_md8',1,'']]],
  ['checkpoint_20level_20durability_33',['Checkpoint-level durability',['../durability_checkpoint.html',1,'programming']]],
  ['checkpoint_20metadata_34',['Storing Checkpoint Metadata',['../arch-metadata.html#metadata_checkpoint',1,'']]],
  ['checkpoint_20naming_35',['Checkpoint naming',['../durability_checkpoint.html#checkpoint_naming',1,'']]],
  ['checkpoint_20operations_36',['Flush Checkpoint Operations',['../arch-tiered-storage.html#ts_flush',1,'']]],
  ['checkpoint_20prepare_20phase_37',['Checkpoint Prepare Phase',['../arch-tiered-storage.html#ts_checkpoint_prepare',1,'']]],
  ['checkpointing_20specific_20objects_38',['Checkpointing specific objects',['../durability_checkpoint.html#checkpoint_target',1,'']]],
  ['checkpoints_39',['Checkpoints',['../arch-tiered-storage.html#ts_checkpoints',1,'Checkpoints'],['../durability_checkpoint.html#checkpoint_checkpoints',1,'Checkpoints'],['../durability_log.html#commit_durability_checkpoint',1,'Checkpoints'],['../arch-snapshot.html#snapshot_checkpoint',1,'Snapshots \&amp; Checkpoints']]],
  ['checkpoints_40',['checkpoints',['../lsm.html#lsm_checkpoints',1,'Named checkpoints'],['../arch-checkpoint.html#autotoc_md7',1,'Skipping checkpoints']]],
  ['checkpoints_20and_20eviction_41',['Interaction with checkpoints and eviction',['../arch-rts.html#interaction-with-checkpoints-and-eviction',1,'']]],
  ['checkpoints_20and_20file_20compaction_42',['Checkpoints and file compaction',['../durability_checkpoint.html#checkpoint_compaction',1,'']]],
  ['checkpoints_20vs_20snapshots_43',['Checkpoints vs. snapshots',['../durability_checkpoint.html#checkpoint_snapshot',1,'']]],
  ['checksum_44',['Checksum',['../arch-block.html#checksum',1,'']]],
  ['checksums_45',['Checksums',['../tune_checksum.html',1,'programming']]],
  ['child_20reconciliation_46',['Leaf (child) reconciliation',['../arch-fast-truncate.html#ft_leaf_reconciliation',1,'']]],
  ['choices_20and_20their_20implications_47',['Configuration choices and their implications',['../arch-logging.html#log_configuration',1,'']]],
  ['choosing_20a_20file_20format_48',['Choosing a file format',['../file_formats.html#file_formats_choice',1,'']]],
  ['chunk_20cache_49',['Chunk cache',['../chunkcache.html',1,'programming']]],
  ['clang_20as_20your_20c_20compiler_20and_20enable_20libfuzzer_50',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['clang_20build_20options_51',['gcc/clang build options',['../tune_build_options.html',1,'programming']]],
  ['clang_20coverage_52',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['class_53',['Connection class',['../arch-cloud-storage-extension.html#extension_connection',1,'']]],
  ['clean_20eviction_54',['Clean eviction',['../eviction.html#clean_eviction',1,'']]],
  ['clean_20vs_20dirty_20data_55',['Clean vs dirty data',['../arch-eviction.html#clean_dirty_data',1,'']]],
  ['clean_20vs_20dirty_20eviction_56',['Clean vs dirty eviction',['../arch-eviction.html#clean_dirty_eviction',1,'']]],
  ['close_57',['close',['../group__wt__ext.html#aa4376c70336f8a0bbd8bf1c91749aeed',1,'WT_FILE_HANDLE::close'],['../struct_w_t___c_u_r_s_o_r.html#aeea071f192cab12245a50fbe71c3460b',1,'WT_CURSOR::close()'],['../struct_w_t___s_e_s_s_i_o_n.html#a96f25dfa6447034aea1f67ab02ab5698',1,'WT_SESSION::close()'],['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#af535c517df851eeac8ebf3594d40b545',1,'WT_CONNECTION::close()'],['../struct_w_t___c_o_n_f_i_g___p_a_r_s_e_r.html#a44eea5e27a4da10006ab444ee7cf00f3',1,'WT_CONFIG_PARSER::close()'],['../tune_close.html',1,'Connection close']]],
  ['closing_20a_20cursor_58',['Closing a cursor',['../cursor_ops.html#cursor_closing',1,'']]],
  ['closing_20handles_59',['Closing handles',['../basic_api.html#basic_close',1,'']]],
  ['closure_60',['Closure',['../arch-connection.html#arch_conn_closure',1,'Closure'],['../arch-session.html#arch_session_closure',1,'Closure']]],
  ['cloud_20file_20handle_20interface_61',['Cloud File Handle Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_handle',1,'']]],
  ['cloud_20file_20system_20interface_62',['Cloud File System Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_system',1,'']]],
  ['cloud_20storage_20source_20implementation_63',['Cloud Storage Source Implementation',['../arch-cloud-storage-extension.html#extension_storage_source',1,'']]],
  ['code_20blocks_64',['Diagnostic Code Blocks',['../debugging.html#diagnostic_code_blocks',1,'']]],
  ['code_20coverage_20for_20an_20llvm_20libfuzzer_20fuzzer_65',['Viewing code coverage for an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md20',1,'']]],
  ['code_20coverage_20information_66',['Step 3: Generate code coverage information',['../tool-libfuzzer.html#autotoc_md23',1,'']]],
  ['code_20samples_67',['Code samples',['../packing.html#config_examples',1,'Code samples'],['../schema.html#schema_examples',1,'Code samples'],['../threads.html#threads_example',1,'Code samples']]],
  ['collate_68',['collate',['../group__wt__ext.html#ab34ce4a2511c0fb370f3ee46d8ffd880',1,'WT_EXTENSION_API']]],
  ['collator_5fconfig_69',['collator_config',['../group__wt__ext.html#a7ed2b2297783ea88c0f513721ff54b7c',1,'WT_EXTENSION_API']]],
  ['collators_70',['Collators',['../custom_collators.html',1,'Custom Collators'],['../custom_collators.html#custom_collators_intro',1,'Introduction to Custom Collators']]],
  ['collators_20and_20recovery_71',['Custom Collators and Recovery',['../custom_collators.html#custom_collators_recovery',1,'']]],
  ['collators_20for_20indices_72',['Custom Collators for Indices',['../custom_collators.html#custom_collators_indices',1,'']]],
  ['collators_20in_20raw_20mode_73',['Custom Collators in raw mode',['../custom_extractors.html#custom_extractors_raw',1,'']]],
  ['collection_74',['Garbage Collection',['../arch-tiered-storage.html#ts_future_garbage',1,'']]],
  ['collection_75',['Garbage collection',['../arch-checkpoint.html#autotoc_md9',1,'']]],
  ['column_20groups_76',['Column groups',['../schema.html#schema_column_groups',1,'']]],
  ['column_20groups_20indices_20and_20projections_77',['Schema, Columns, Column Groups, Indices and Projections',['../schema.html',1,'programming']]],
  ['column_20store_78',['Row Store and Column Store',['../arch-row-column.html',1,'arch-toc-data-src']]],
  ['column_20stores_79',['column stores',['../arch-row-column.html#row_column_flcs',1,'Fixed length column-stores'],['../arch-row-column.html#row_column_vlcs',1,'Variable length column-stores']]],
  ['column_20types_80',['Column types',['../schema.html#schema_column_types',1,'']]],
  ['columns_81',['Columns',['../schema.html#schema_columns',1,'']]],
  ['columns_82',['Tables, rows and columns',['../schema.html#schema_intro',1,'']]],
  ['columns_20column_20groups_20indices_20and_20projections_83',['Schema, Columns, Column Groups, Indices and Projections',['../schema.html',1,'programming']]],
  ['command_20line_84',['Backup from the command line',['../backup.html#backup_util',1,'']]],
  ['command_20line_20utility_85',['WiredTiger command line utility',['../command_line.html',1,'index']]],
  ['commit_86',['commit',['../durability_log.html#commit_durability_group_commit',1,'Group commit'],['../tune_durability.html#tune_durability_group_commit',1,'Group commit']]],
  ['commit_20level_20durability_87',['Commit level durability',['../durability_log.html',1,'Commit-level durability'],['../tune_durability.html',1,'Commit-level durability']]],
  ['commit_20level_20durability_88',['commit level durability',['../durability_log.html#commit_durability_enable',1,'Enabling commit-level durability'],['../durability_log.html#commit_durability_tuning',1,'Tuning commit-level durability']]],
  ['commit_20level_20durability_20and_20logs_89',['Commit-level durability and logs',['../durability_log.html#commit_durability_logs',1,'']]],
  ['commit_20level_20durability_20and_20timestamps_90',['Logged objects, commit-level durability and timestamps',['../timestamp_model.html#timestamps_durability_commit',1,'']]],
  ['commit_20level_20durability_20without_20timestamps_91',['Commit-level durability (without timestamps)',['../durability_overview.html#explain_durability_commit',1,'']]],
  ['commit_20timestamp_92',['Setting the transaction&apos;s commit timestamp',['../timestamp_txn_api.html#timestamp_txn_api_commit_timestamp',1,'']]],
  ['commit_20timestamps_93',['Setting multiple commit timestamps',['../timestamp_txn_api.html#timestamp_txn_api_commit_multi_timestamp',1,'']]],
  ['commit_5ftransaction_94',['commit_transaction',['../struct_w_t___s_e_s_s_i_o_n.html#a712226eca5ade5bd123026c624468fa2',1,'WT_SESSION']]],
  ['community_20and_20contact_20information_95',['WiredTiger community and contact information',['../community.html',1,'index']]],
  ['compact_96',['compact',['../group__wt__ext.html#a8eae397273ef872bc8da6743aa9824cb',1,'WT_DATA_SOURCE::compact'],['../struct_w_t___s_e_s_s_i_o_n.html#aafa7a12a4891a5bfdc98673a5b8f9c69',1,'WT_SESSION::compact()'],['../command_line.html#util_compact',1,'wt compact']]],
  ['compaction_97',['Compaction',['../arch-compact.html',1,'Compaction'],['../compact.html',1,'Compaction']]],
  ['compaction_98',['compaction',['../arch-compact.html#autotoc_md10',1,'Background compaction'],['../compact.html#background',1,'Background compaction'],['../durability_checkpoint.html#checkpoint_compaction',1,'Checkpoints and file compaction'],['../compact.html#foreground',1,'Foreground compaction']]],
  ['compare_99',['compare',['../group__wt__ext.html#a8b187a50a9830bfb63390ee5bf9b6cd0',1,'WT_COLLATOR::compare'],['../struct_w_t___c_u_r_s_o_r.html#acd3f345e375e26d223ad5c6f35dc15e8',1,'WT_CURSOR::compare()']]],
  ['compatibility_100',['JavaScript Object Notation (JSON) compatibility',['../config_strings.html#config_json',1,'']]],
  ['compilation_101',['Compilation',['../arch-config-compile.html',1,'Configuration String Compilation'],['../arch-config-compile.html#compile_initial',1,'Initial Pre-Compilation'],['../arch-config-compile.html#compile_scripts',1,'Scripts Supporting Configuration Compilation']]],
  ['compile_20wiredtiger_20with_20xray_20instrumentation_102',['Step 2: Configure and compile WiredTiger with XRay instrumentation',['../tool-xray.html#autotoc_md57',1,'']]],
  ['compile_20with_20clang_20coverage_103',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['compile_5fconfiguration_104',['compile_configuration',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a476b94edd7babeba038ec877b3277291',1,'WT_CONNECTION']]],
  ['compiled_20string_105',['The Compiled String',['../arch-config-compile.html#compile_returned_string',1,'']]],
  ['compiler_20and_20enable_20libfuzzer_106',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['compiler_20barrier_107',['Compiler barrier',['../arch-concurrency.html#com-bar',1,'']]],
  ['compiler_20or_20loader_20options_108',['Changing compiler or loader options',['../build-posix.html#posix_compiler',1,'']]],
  ['compiling_20unbound_20parameters_109',['Compiling Unbound Parameters',['../arch-config-compile.html#compile_unbound',1,'']]],
  ['complete_20example_110',['A complete example',['../tool-statistics.html#autotoc_md54',1,'']]],
  ['compliance_111',['POSIX compliance',['../portability.html#posix',1,'']]],
  ['components_112',['Interaction With Other Components',['../arch-prefetch.html#prefetch_other',1,'']]],
  ['composite_20keys_113',['Syntactic Sugar and Composite Keys',['../arch-config-compile.html#compile_composite',1,'']]],
  ['compress_114',['compress',['../group__wt__ext.html#a075294c61c5d29abd55fc4603afe431f',1,'WT_COMPRESSOR']]],
  ['compression_115',['compression',['../file_formats.html',1,'File formats and compression'],['../file_formats.html#file_formats_compression',1,'File formats and compression'],['../tune_page_size_and_comp.html',1,'Tuning page size and compression'],['../compression.html#compression_iaa',1,'Using iaa compression'],['../compression.html#compression_lz4',1,'Using LZ4 compression'],['../compression.html#compression_snappy',1,'Using snappy compression'],['../compression.html#compression_zlib',1,'Using zlib compression'],['../compression.html#compression_zstd',1,'Using zstd compression']]],
  ['compression_20considerations_116',['Compression considerations',['../tune_page_size_and_comp.html#compression_considerations',1,'']]],
  ['compression_20engines_117',['compression engines',['../compression.html#compression_custom',1,'Custom compression engines'],['../compression.html#compression_upgrading',1,'Upgrading compression engines']]],
  ['compression_20in_20wiredtiger_118',['Table summarizing compression in WiredTiger',['../tune_page_size_and_comp.html#table_compress',1,'']]],
  ['compressors_119',['Compressors',['../compression.html',1,'programming']]],
  ['concepts_120',['Concepts',['../arch-toc-in-mem.html',1,'In Memory Concepts'],['../arch-toc-on-disk.html',1,'On Disk Concepts']]],
  ['concurrency_121',['Concurrency',['../arch-prefetch.html#prefetch_other_concurrency',1,'']]],
  ['concurrency_20control_122',['Concurrency control',['../transactions_api.html#transactions_concurrency',1,'']]],
  ['concurrency_20management_123',['Concurrency management',['../arch-concurrency.html',1,'arch-toc-int-wt-dev']]],
  ['config_20file_124',['WiredTiger.config file',['../database_config.html#config_file',1,'']]],
  ['config_5fget_125',['config_get',['../group__wt__ext.html#a0d3aae2ceac28f7b45188bcfa4306d45',1,'WT_EXTENSION_API']]],
  ['config_5fget_5fstring_126',['config_get_string',['../group__wt__ext.html#acac24b7ad23022698ee8ef64be164727',1,'WT_EXTENSION_API']]],
  ['config_5fparser_5fopen_127',['config_parser_open',['../group__wt__ext.html#a925298c80d5c887172e184ff67027ed6',1,'WT_EXTENSION_API']]],
  ['config_5fparser_5fopen_5farg_128',['config_parser_open_arg',['../group__wt__ext.html#ae498b02cf83cdb644c2665c37917e785',1,'WT_EXTENSION_API']]],
  ['configurable_20page_20structures_20in_20wiredtiger_129',['Configurable page structures in WiredTiger',['../tune_page_size_and_comp.html#configurable_page_struct',1,'']]],
  ['configuration_130',['Configuration',['../arch-prefetch.html#prefetch_api_connection',1,'Connection-Level Configuration'],['../database_config.html',1,'Database Configuration'],['../arch-prefetch.html#prefetch_api_session',1,'Session-Level Configuration']]],
  ['configuration_131',['configuration',['../timestamp_txn_api.html#timestamp_txn_api_configure',1,'Application timestamp configuration'],['../encryption.html#encryption_config',1,'Encryption configuration'],['../durability_log.html#commit_durability_flush_config',1,'Flush call configuration'],['../tune_durability.html#tune_durability_flush_config',1,'Flush call configuration'],['../lsm.html#lsm_key_format',1,'Key_format configuration']]],
  ['configuration_20and_20logging_132',['Readonly configuration and logging',['../readonly.html#readonly_logging',1,'']]],
  ['configuration_20and_20lsm_20trees_133',['Readonly configuration and LSM trees',['../readonly.html#readonly_lsm',1,'']]],
  ['configuration_20and_20multiple_20database_20handles_134',['Readonly configuration and multiple database handles',['../readonly.html#readonly_handles',1,'']]],
  ['configuration_20and_20recovery_135',['Readonly configuration and recovery',['../readonly.html#readonly_recovery',1,'']]],
  ['configuration_20choices_20and_20their_20implications_136',['Configuration choices and their implications',['../arch-logging.html#log_configuration',1,'']]],
  ['configuration_20compilation_137',['Scripts Supporting Configuration Compilation',['../arch-config-compile.html#compile_scripts',1,'']]],
  ['configuration_20considerations_138',['Database read-only configuration considerations',['../readonly.html#readonly_config',1,'']]],
  ['configuration_20options_139',['Configuration options',['../arch-block.html#configuration',1,'']]],
  ['configuration_20options_140',['Wtperf configuration options',['../wtperf.html#config',1,'']]],
  ['configuration_20ordering_141',['Configuration ordering',['../database_config.html#config_order',1,'']]],
  ['configuration_20string_20compilation_142',['Configuration String Compilation',['../arch-config-compile.html',1,'arch-toc-api']]],
  ['configuration_20string_20parsing_20examples_143',['Configuration String Parsing examples',['../struct_w_t___c_o_n_f_i_g___p_a_r_s_e_r.html#config_parse_examples',1,'']]],
  ['configuration_20strings_144',['Configuration Strings',['../config_strings.html',1,'programming']]],
  ['configuration_20strings_145',['Configuration strings',['../custom_data_sources.html#custom_ds_config',1,'']]],
  ['configuration_20strings_146',['configuration strings',['../custom_data_sources.html#custom_ds_config_add',1,'Creating data-specific configuration strings'],['../custom_data_sources.html#custom_ds_config_parsing',1,'Parsing configuration strings']]],
  ['configurations_20and_20timestamps_147',['In-memory configurations and timestamps',['../timestamp_misc.html#timestamps_misc_in_memory',1,'']]],
  ['configure_20and_20build_20wiredtiger_20with_20llvm_20flags_148',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['configure_20and_20compile_20wiredtiger_20with_20xray_20instrumentation_149',['Step 2: Configure and compile WiredTiger with XRay instrumentation',['../tool-xray.html#autotoc_md57',1,'']]],
  ['configure_20with_20clang_20as_20your_20c_20compiler_20and_20enable_20libfuzzer_150',['Step 1: Configure with Clang as your C compiler and enable LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'']]],
  ['configure_20your_20build_20to_20compile_20with_20clang_20coverage_151',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['configure_5fmethod_152',['configure_method',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#ab81828b0c9dccc1ccf3d8ef863804137',1,'WT_CONNECTION']]],
  ['configuring_20ignore_5fprepare_153',['Configuring ignore_prepare',['../timestamp_prepare.html#timestamp_prepare_ignore_prepare',1,'']]],
  ['configuring_20runtime_20diagnostics_154',['Configuring runtime diagnostics',['../debugging.html#extra_diagnostics_configuration',1,'']]],
  ['configuring_20transaction_20timestamp_20information_20with_20wt_5fsession_3a_3abegin_5ftransaction_155',['Configuring transaction timestamp information with WT_SESSION::begin_transaction',['../timestamp_txn_api.html#timestamp_txn_api_begin',1,'']]],
  ['configuring_20transaction_20timestamp_20information_20with_20wt_5fsession_3a_3acommit_5ftransaction_156',['Configuring transaction timestamp information with WT_SESSION::commit_transaction',['../timestamp_txn_api.html#timestamp_txn_api_commit',1,'']]],
  ['configuring_20transaction_20timestamp_20information_20with_20wt_5fsession_3a_3aprepare_5ftransaction_157',['Configuring transaction timestamp information with WT_SESSION::prepare_transaction',['../timestamp_txn_api.html#timestamp_txn_api_prepare',1,'']]],
  ['configuring_20transaction_20timestamp_20information_20with_20wt_5fsession_3a_3atimestamp_5ftransaction_158',['Configuring transaction timestamp information with WT_SESSION::timestamp_transaction',['../timestamp_txn_api.html#timestamp_txn_api_timestamp_transaction',1,'']]],
  ['configuring_20verbose_20categories_159',['Configuring Verbose Categories',['../verbose_messaging.html#verbosity_configuration',1,'']]],
  ['configuring_20wiredtiger_160',['Configuring WiredTiger',['../build-posix.html#posix_configure',1,'Configuring WiredTiger'],['../build-windows.html#windows_configure',1,'Configuring WiredTiger']]],
  ['connecting_20to_20a_20database_161',['Connecting to a database',['../basic_api.html#basic_connection',1,'']]],
  ['connection_162',['Connection',['../arch-connection.html',1,'arch-toc-fundamentals']]],
  ['connection_163',['connection',['../struct_w_t___s_e_s_s_i_o_n.html#a28a33717c138b4c481019947e230f8f6',1,'WT_SESSION']]],
  ['connection_20class_164',['Connection class',['../arch-cloud-storage-extension.html#extension_connection',1,'']]],
  ['connection_20close_165',['Connection close',['../tune_close.html',1,'programming']]],
  ['connection_20level_20configuration_166',['Connection-Level Configuration',['../arch-prefetch.html#prefetch_api_connection',1,'']]],
  ['considerations_167',['considerations',['../tune_page_size_and_comp.html#compression_considerations',1,'Compression considerations'],['../readonly.html#readonly_config',1,'Database read-only configuration considerations'],['../arch-fast-truncate.html#ft_vlcs',1,'VLCS considerations']]],
  ['considering_20current_20cache_20busyness_168',['Considering Current Cache Busyness',['../arch-prefetch.html#prefetch_other_cache_busyness',1,'']]],
  ['contact_20information_169',['WiredTiger community and contact information',['../community.html',1,'index']]],
  ['content_170',['Pinned Content',['../chunkcache.html#pinned',1,'']]],
  ['content_171',['content',['../arch-cache.html#arch_cache_size',1,'Cache size and content'],['../chunkcache.html#inserts',1,'Newly inserted or modified content'],['../chunkcache.html#persistence',1,'Persisted content']]],
  ['content_20into_20the_20cache_172',['Pre-fetching Content Into the Cache',['../arch-prefetch.html#prefetch_algorithm_process_pages',1,'']]],
  ['control_173',['Concurrency control',['../transactions_api.html#transactions_concurrency',1,'']]],
  ['control_20of_20the_20outlier_20thresholds_174',['Getting a more precise control of the outlier thresholds',['../tool-optrack.html#autotoc_md37',1,'']]],
  ['convert_20xray_20logs_20to_20the_20operation_20tracking_20format_20optional_175',['Convert XRay logs to the Operation Tracking format (optional)',['../tool-xray.html#autotoc_md59',1,'']]],
  ['cookies_176',['Address Cookies',['../arch-block.html#block_address_cookie',1,'']]],
  ['cookies_20in_20tiered_20storage_177',['Cookies in Tiered Storage',['../arch-tiered-storage.html#ts_cookies',1,'']]],
  ['copy_178',['Debug copy',['../arch-cursor.html#arch_cursor_debug_copy',1,'']]],
  ['copy_20of_20the_20wtperf_20binary_20and_20the_20xray_20log_179',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['copyright_180',['wt copyright',['../command_line.html#util_copyright',1,'']]],
  ['core_20scaling_181',['Multi-core scaling',['../overview.html#multi_core',1,'']]],
  ['corpus_182',['Corpus',['../tool-libfuzzer.html#autotoc_md15',1,'']]],
  ['correctness_20of_20allowing_20reading_20while_20allowing_20writes_183',['Correctness of allowing reading while allowing writes',['../arch-usage-patterns.html#slotted-arrays-correctness',1,'']]],
  ['counting_20events_184',['Counting events',['../tool-perf.html#autotoc_md44',1,'']]],
  ['counts_185',['Data Handle Reference Counts',['../arch-dhandle.html#dhandle_data_handle_reference_counts',1,'']]],
  ['coverage_186',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['coverage_20for_20an_20llvm_20libfuzzer_20fuzzer_187',['Viewing code coverage for an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md20',1,'']]],
  ['coverage_20information_188',['Step 3: Generate code coverage information',['../tool-libfuzzer.html#autotoc_md23',1,'']]],
  ['cpu_20architectures_189',['Supported CPU architectures',['../portability.html#cpu',1,'']]],
  ['cpu_20flame_20graphs_190',['CPU Flame Graphs',['../tool-perf-flamegraphs.html',1,'tool-index']]],
  ['create_191',['Create',['../arch-schema.html#schema_create',1,'']]],
  ['create_192',['create',['../group__wt__ext.html#a68491dde82170031c6526fe140ea39eb',1,'WT_DATA_SOURCE::create'],['../struct_w_t___s_e_s_s_i_o_n.html#a358ca4141d59c345f401c58501276bbb',1,'WT_SESSION::create()'],['../command_line.html#util_create',1,'wt create']]],
  ['creating_20a_20table_193',['Creating a table',['../basic_api.html#basic_create_table',1,'']]],
  ['creating_20data_20specific_20configuration_20strings_194',['Creating data-specific configuration strings',['../custom_data_sources.html#custom_ds_config_add',1,'']]],
  ['creating_20tables_20using_20lsm_20trees_195',['Creating tables using LSM trees',['../lsm.html#lsm_schema',1,'']]],
  ['creation_196',['Data Handle Creation',['../arch-dhandle.html#dhandle_data_handle_creation',1,'']]],
  ['creation_20and_20the_20block_20manager_197',['File creation and the block manager',['../arch-block.html#creation',1,'']]],
  ['cross_20platform_20support_198',['Cross-Platform Support',['../arch-toc-platform.html',1,'arch-index']]],
  ['current_20cache_20busyness_199',['Considering Current Cache Busyness',['../arch-prefetch.html#prefetch_other_cache_busyness',1,'']]],
  ['cursor_200',['Cursor',['../arch-cursor.html',1,'Cursor'],['../arch-cursor.html#arch_random_cursor',1,'Random Cursor']]],
  ['cursor_201',['cursor',['../arch-metadata.html#metadata_cursor',1,'&quot;metadata:&quot; cursor'],['../arch-metadata.html#metadata_create_cursor',1,'&quot;metadata:create&quot; cursor'],['../cursor_ops.html#cursor_bound',1,'Apply bounds to the cursor'],['../cursor_ops.html#cursor_closing',1,'Closing a cursor'],['../backup.html#backup_export',1,'Export tables using backup cursor'],['../cursor_ops.html#cursor_opening',1,'Opening a cursor'],['../cursor_ops.html#cursor_position',1,'Positioning a cursor']]],
  ['cursor_20caching_202',['Cursor caching',['../arch-cursor.html#arch_cursor_caching',1,'']]],
  ['cursor_20formats_203',['Cursor formats',['../schema.html#schema_cursor_formats',1,'']]],
  ['cursor_20interface_204',['History store cursor interface',['../arch-hs.html#arch_hs_cursor',1,'']]],
  ['cursor_20interface_20and_20visibility_20rules_205',['History store cursor interface and visibility rules',['../arch-hs.html#arch_hs_cursor_visibility',1,'']]],
  ['cursor_20key_20value_20memory_20scoping_206',['Cursor key/value memory scoping',['../cursor_ops.html#cursor_memory_scoping',1,'']]],
  ['cursor_20operations_207',['Cursor operations',['../cursor_ops.html',1,'cursors']]],
  ['cursor_20persistence_208',['Cursor persistence',['../tune_cursor_persist.html',1,'programming']]],
  ['cursor_20position_20after_20error_209',['Cursor position after error',['../cursor_ops.html#cursor_error',1,'']]],
  ['cursor_20projections_210',['Index cursor projections',['../schema.html#schema_index_projections',1,'']]],
  ['cursor_20random_211',['Cursor random',['../cursor_random.html',1,'cursor_ops']]],
  ['cursor_20sweep_212',['Session cursor sweep',['../arch-cursor.html#arch_cursor_sweep',1,'']]],
  ['cursor_20types_213',['Cursor types',['../cursors.html#cursor_types',1,'']]],
  ['cursors_214',['Cursors',['../cursors.html',1,'Cursors'],['../arch-session.html#arch_session_cur',1,'Cursors']]],
  ['cursors_215',['cursors',['../basic_api.html#basic_cursors',1,'Accessing data with cursors'],['../arch-cursor.html#arch_cursor_backup',1,'Backup cursors'],['../durability_checkpoint.html#checkpoint_cursors',1,'Checkpoint cursors'],['../arch-cursor.html#arch_cursor_dump',1,'Dump cursors'],['../backup.html#backup_duplicate',1,'Duplicate backup cursors'],['../arch-cursor.html#arch_cursor_duplicate',1,'Duplicating cursors'],['../arch-cursor.html#arch_cursor_file',1,'File cursors'],['../cursor_join.html',1,'Join cursors'],['../arch-cursor.html#arch_cursor_join',1,'Join cursors'],['../cursor_log.html',1,'Log cursors'],['../durability_log.html#commit_log_cursors',1,'Log cursors'],['../arch-cursor.html#arch_cursor_bound',1,'Range bounded cursors'],['../arch-cursor.html#arch_cursor_table',1,'Table and index cursors']]],
  ['cursors_20and_20eviction_216',['Cursors and Eviction',['../cursors.html#cursors_eviction',1,'']]],
  ['cursors_20and_20transactions_217',['Cursors and transactions',['../transactions_api.html#cursors_transactions',1,'']]],
  ['cursors_20btrees_20and_20data_20handles_218',['File cursors, Btrees and data handles',['../arch-cursor.html#arch_cursor_dhandle',1,'']]],
  ['custom_20collators_219',['Custom Collators',['../custom_collators.html',1,'Custom Collators'],['../custom_collators.html#custom_collators_intro',1,'Introduction to Custom Collators']]],
  ['custom_20collators_20and_20recovery_220',['Custom Collators and Recovery',['../custom_collators.html#custom_collators_recovery',1,'']]],
  ['custom_20collators_20for_20indices_221',['Custom Collators for Indices',['../custom_collators.html#custom_collators_indices',1,'']]],
  ['custom_20collators_20in_20raw_20mode_222',['Custom Collators in raw mode',['../custom_extractors.html#custom_extractors_raw',1,'']]],
  ['custom_20compression_20engines_223',['Custom compression engines',['../compression.html#compression_custom',1,'']]],
  ['custom_20data_20sources_224',['Custom Data Sources',['../custom_data_sources.html',1,'programming']]],
  ['custom_20encryption_20extensions_225',['Custom encryption extensions',['../encryption.html#encryption_custom',1,'']]],
  ['custom_20extractors_226',['Custom Extractors',['../custom_extractors.html',1,'Custom Extractors'],['../custom_extractors.html#custom_extractors_intro',1,'Introduction to Custom Extractors']]],
  ['custom_20file_20systems_227',['Custom File Systems',['../custom_file_systems.html',1,'programming']]],
  ['custom_20tiered_20storage_20sources_228',['Custom Tiered Storage sources',['../custom_storage_sources.html',1,'programming']]],
  ['customization_229',['File System and Handle Customization',['../arch-fs-os.html#file_customization',1,'']]],
  ['customize_230',['customize',['../group__wt__ext.html#adc24bc0e035643b8e2b596022c84b6e0',1,'WT_COLLATOR::customize'],['../group__wt__ext.html#a947e253ec628a29b62e4b6656eb7b92a',1,'WT_ENCRYPTOR::customize'],['../group__wt__ext.html#aead7ade6a5c1ea31917ed8cd0ef841aa',1,'WT_EXTRACTOR::customize']]],
  ['cycle_231',['cycle',['../tune_page_size_and_comp.html#data_life_cycle',1,'Data life cycle'],['../arch-connection.html#arch_conn_lifecycle',1,'Life cycle']]]
];
