var searchData=
[
  ['b_20tree_20data_20source_20wt_5fbtree_0',['B-Tree Data Source (WT_BTREE)',['../arch-btree.html#btree_btree_data_source',1,'']]],
  ['b_20tree_20in_20memory_20representation_1',['B-Tree In-Memory Representation',['../arch-btree.html#btree_btree_in_memory_representation',1,'']]],
  ['b_20trees_2',['B Trees',['../arch-btree.html',1,'B-Trees'],['../arch-rts.html#iterating-over-b-trees',1,'Iterating over B-Trees']]],
  ['background_3',['Background',['../lsm.html#lsm_background',1,'Background'],['../tiered_storage.html#tiered_background',1,'Background']]],
  ['background_20compaction_4',['Background compaction',['../arch-compact.html#autotoc_md10',1,'Background compaction'],['../compact.html#background',1,'Background compaction']]],
  ['backup_5',['Backup',['../arch-backup.html',1,'arch-toc-on-disk']]],
  ['backup_6',['backup',['../backup.html#backup_incremental-block',1,'Block-based Incremental backup'],['../arch-backup.html#autotoc_md2',1,'Block-based incremental backup'],['../backup.html#backup_incremental',1,'Log-based Incremental backup'],['../arch-backup.html#autotoc_md3',1,'Log-based incremental backup'],['../arch-backup.html#autotoc_md4',1,'Target backup'],['../command_line.html#util_backup',1,'wt backup']]],
  ['backup_20and_20o_5fdirect_7',['Backup and O_DIRECT',['../backup.html#backup_o_direct',1,'']]],
  ['backup_20cursor_8',['Export tables using backup cursor',['../backup.html#backup_export',1,'']]],
  ['backup_20cursors_9',['Backup cursors',['../arch-cursor.html#arch_cursor_backup',1,'']]],
  ['backup_20cursors_10',['Duplicate backup cursors',['../backup.html#backup_duplicate',1,'']]],
  ['backup_20from_20an_20application_11',['Backup from an application',['../backup.html#backup_process',1,'']]],
  ['backup_20from_20the_20command_20line_12',['Backup from the command line',['../backup.html#backup_util',1,'']]],
  ['backups_13',['Backups',['../backup.html',1,'Backups'],['../durability_log.html#commit_durability_backup',1,'Backups']]],
  ['backups_14',['Checkpoint durability and backups',['../durability_checkpoint.html#checkpoint_backup',1,'']]],
  ['barrier_15',['barrier',['../arch-concurrency.html#acq-bar',1,'Acquire barrier'],['../arch-concurrency.html#com-bar',1,'Compiler barrier'],['../arch-concurrency.html#full-bar',1,'Full barrier'],['../arch-concurrency.html#rel-bar',1,'Release barrier']]],
  ['barriers_16',['Memory Barriers',['../arch-concurrency.html#memory-barriers',1,'']]],
  ['basecfg_20file_17',['WiredTiger.basecfg file',['../database_config.html#config_base',1,'']]],
  ['based_20incremental_20backup_18',['based Incremental backup',['../backup.html#backup_incremental-block',1,'Block-based Incremental backup'],['../backup.html#backup_incremental',1,'Log-based Incremental backup']]],
  ['based_20incremental_20backup_19',['based incremental backup',['../arch-backup.html#autotoc_md2',1,'Block-based incremental backup'],['../arch-backup.html#autotoc_md3',1,'Log-based incremental backup']]],
  ['basic_20operation_20',['Basic operation',['../arch-cache.html#arch_cache_basics',1,'']]],
  ['becoming_20familiar_20with_20the_20operation_20tracking_20log_20files_21',['Becoming familiar with the operation tracking log files',['../tool-optrack.html#autotoc_md33',1,'']]],
  ['begin_5ftransaction_22',['begin_transaction',['../struct_w_t___s_e_s_s_i_o_n.html#a7e26b16b26b5870498752322fad790bf',1,'WT_SESSION']]],
  ['between_20memory_20and_20disk_23',['Moving Data Between Memory and Disk',['../arch-toc-mem-disk.html',1,'arch-index']]],
  ['binary_20and_20the_20xray_20log_24',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['bind_5fconfiguration_25',['bind_configuration',['../struct_w_t___s_e_s_s_i_o_n.html#aedd139d6424440d5300e88c4fa061f41',1,'WT_SESSION']]],
  ['binding_20parameters_26',['Binding Parameters',['../arch-config-compile.html#compile_bind',1,'']]],
  ['block_27',['What is a block?',['../arch-block.html#block_what',1,'']]],
  ['block_20allocation_28',['File block allocation',['../tune_file_alloc.html#tuning_system_file_block_allocation',1,'']]],
  ['block_20based_20incremental_20backup_29',['Block-based Incremental backup',['../backup.html#backup_incremental-block',1,'']]],
  ['block_20based_20incremental_20backup_30',['Block-based incremental backup',['../arch-backup.html#autotoc_md2',1,'']]],
  ['block_20manager_31',['Block Manager',['../arch-block.html',1,'Block Manager'],['../arch-tiered-storage.html#ts_block_manager',1,'Block Manager'],['../arch-tiered-storage.html#ts_block_files',1,'Files in the Block Manager']]],
  ['block_20manager_32',['block manager',['../arch-block.html#creation',1,'File creation and the block manager'],['../arch-block.html#block_usage',1,'How WiredTiger uses the block manager']]],
  ['block_20manager_20implementation_20details_33',['Block manager implementation details',['../arch-block.html#block_implementation',1,'']]],
  ['blocks_34',['Diagnostic Code Blocks',['../debugging.html#diagnostic_code_blocks',1,'']]],
  ['blocks_35',['Descriptor blocks',['../arch-block.html#desc_block',1,'']]],
  ['bloom_20filters_36',['Bloom filters',['../lsm.html#lsm_bloom',1,'']]],
  ['bound_37',['bound',['../struct_w_t___c_u_r_s_o_r.html#a1f31636c1cf31f72df576b82b03a4c44',1,'WT_CURSOR']]],
  ['bounded_20cursors_38',['Range bounded cursors',['../arch-cursor.html#arch_cursor_bound',1,'']]],
  ['bounds_20to_20the_20cursor_39',['Apply bounds to the cursor',['../cursor_ops.html#cursor_bound',1,'']]],
  ['bsd_20os_20x_20_3a_40',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['btrees_20and_20data_20handles_41',['File cursors, Btrees and data handles',['../arch-cursor.html#arch_cursor_dhandle',1,'']]],
  ['buckets_20and_20prefixes_42',['Storage Sources, Buckets, and Prefixes',['../arch-tiered-storage.html#ts_buckets',1,'']]],
  ['buffer_20cache_43',['System buffer cache',['../tune_system_buffer_cache.html',1,'programming']]],
  ['build_20and_20run_20fuzzer_44',['Step 2: Build and run fuzzer',['../tool-libfuzzer.html#autotoc_md22',1,'']]],
  ['build_20as_20usual_45',['Step 2: Build as usual',['../tool-libfuzzer.html#autotoc_md13',1,'']]],
  ['build_20options_46',['gcc/clang build options',['../tune_build_options.html',1,'programming']]],
  ['build_20to_20compile_20with_20clang_20coverage_47',['Step 1: Configure your build to compile with Clang coverage',['../tool-libfuzzer.html#autotoc_md21',1,'']]],
  ['build_20wiredtiger_20with_20llvm_20flags_48',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['building_20and_20installing_20wiredtiger_20on_20posix_20linux_20bsd_20os_20x_20_3a_49',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['building_20and_20installing_20wiredtiger_20on_20windows_50',['Building and installing WiredTiger on Windows',['../build-windows.html',1,'index']]],
  ['building_20and_20running_20an_20llvm_20libfuzzer_20fuzzer_51',['Building and running an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'']]],
  ['building_20on_20windows_52',['Building on Windows',['../build-windows.html#windows_building',1,'']]],
  ['building_20using_20git_20and_20github_53',['Building using Git and GitHub',['../build-posix.html#posix_github',1,'Building using Git and GitHub'],['../build-windows.html#windows_github',1,'Building using Git and GitHub']]],
  ['building_20wiredtiger_54',['Building WiredTiger',['../build-posix.html#posix_building',1,'']]],
  ['builtin_20data_20sources_55',['Builtin data sources',['../data_sources.html#data_builtin',1,'']]],
  ['bulk_20load_56',['Bulk-load',['../tune_bulk_load.html',1,'programming']]],
  ['bulk_20loads_57',['Bulk loads',['../durability_log.html#commit_durability_bulk',1,'']]],
  ['busyness_58',['Considering Current Cache Busyness',['../arch-prefetch.html#prefetch_other_cache_busyness',1,'']]],
  ['by_20rounding_20up_20the_20prepare_20timestamp_59',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]]
];
