var searchData=
[
  ['unbound_20parameters_0',['Compiling Unbound Parameters',['../arch-config-compile.html#compile_unbound',1,'']]],
  ['uncommitted_20modifies_1',['Snapshot Read-uncommitted \&amp; Modifies',['../arch-snapshot.html#snapshot_read_uncommitted',1,'']]],
  ['unnecessary_20pages_20into_20memory_2',['Skipping reading unnecessary pages into memory',['../arch-rts.html#rts-page-skip',1,'']]],
  ['unpack_5fint_3',['unpack_int',['../group__wt__ext.html#a1ea4c874fa755ef49fc9645088dcad84',1,'WT_EXTENSION_API']]],
  ['unpack_5fitem_4',['unpack_item',['../group__wt__ext.html#a2cab4053dd45354e393401d45eea8888',1,'WT_EXTENSION_API']]],
  ['unpack_5fstart_5',['unpack_start',['../group__wt__ext.html#ae87ae081fa676db65a7e06fe03a20fc6',1,'WT_EXTENSION_API']]],
  ['unpack_5fstr_6',['unpack_str',['../group__wt__ext.html#aba527dfba833b01bb7c70ede18b45990',1,'WT_EXTENSION_API']]],
  ['unpack_5fuint_7',['unpack_uint',['../group__wt__ext.html#a65aa50ee5d12ed2eb70e157277c7603f',1,'WT_EXTENSION_API']]],
  ['unpacking_20data_8',['Packing and Unpacking Data',['../packing.html',1,'schema']]],
  ['unstable_20updates_9',['How RTS aborts unstable updates',['../arch-rts.html#rts-abort-updates',1,'']]],
  ['up_20the_20prepare_20timestamp_10',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]],
  ['up_20the_20read_20timestamp_11',['Rounding up the read timestamp',['../timestamp_misc.html#timestamp_read_roundup',1,'']]],
  ['update_12',['update',['../struct_w_t___c_u_r_s_o_r.html#a444cdc0952e7f8d55d23173516c7037f',1,'WT_CURSOR']]],
  ['update_20restore_20eviction_13',['Update restore eviction',['../eviction.html#update_restore_eviction',1,'']]],
  ['updates_14',['updates',['../arch-rts.html#rts-abort-updates',1,'How RTS aborts unstable updates'],['../arch-rts.html#iterating-over-updates',1,'Iterating over updates']]],
  ['updates_20and_20disk_20pages_15',['Handling of timestamps in updates and disk pages',['../arch-timestamp.html#arch-timestamp-handling',1,'']]],
  ['updating_16',['Inserting, removing and updating',['../cursor_ops.html#cursor_writes',1,'']]],
  ['upgrading_20and_20downgrading_20databases_17',['Upgrading and downgrading databases',['../upgrade.html',1,'programming']]],
  ['upgrading_20compression_20engines_18',['Upgrading compression engines',['../compression.html#compression_upgrading',1,'']]],
  ['upgrading_20to_20version_2011_200_200_19',['Upgrading to Version 11.0.0',['../upgrading.html#version_1100',1,'']]],
  ['upgrading_20to_20version_2011_201_200_20',['Upgrading to Version 11.1.0',['../upgrading.html#version_1110',1,'']]],
  ['upgrading_20to_20version_2011_202_200_21',['Upgrading to Version 11.2.0',['../upgrading.html#version_1120',1,'']]],
  ['upgrading_20to_20version_2011_203_200_22',['Upgrading to Version 11.3.0',['../upgrading.html#version_1130',1,'']]],
  ['upgrading_20to_20version_20older_20than_2011_200_200_23',['Upgrading to Version older than 11.0.0',['../upgrading.html#pre_1100',1,'']]],
  ['upgrading_20wiredtiger_20applications_24',['Upgrading WiredTiger applications',['../upgrading.html',1,'index']]],
  ['uri_25',['uri',['../struct_w_t___c_u_r_s_o_r.html#a9158605cfaab4e3b00c5ef1af3d3bc3f',1,'WT_CURSOR']]],
  ['usage_26',['usage',['../arch-row-column.html#row_column_internal_use',1,'Internal usage'],['../arch-concurrency.html#lock-usage',1,'Lock usage']]],
  ['usage_20patterns_27',['Usage Patterns',['../arch-usage-patterns.html',1,'arch-toc-int-wt-dev']]],
  ['use_20cases_28',['Use cases',['../arch-usage-patterns.html#slotted-arrays-use-cases',1,'']]],
  ['use_20operation_20tracking_29',['Why use operation tracking?',['../tool-optrack.html#autotoc_md25',1,'']]],
  ['useful_30',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['uses_20the_20block_20manager_31',['How WiredTiger uses the block manager',['../arch-block.html#block_usage',1,'']]],
  ['using_20an_20encryption_20extension_32',['Using an encryption extension',['../encryption.html#encryption_use',1,'']]],
  ['using_20backup_20cursor_33',['Export tables using backup cursor',['../backup.html#backup_export',1,'']]],
  ['using_20git_20and_20github_34',['using Git and GitHub',['../build-posix.html#posix_github',1,'Building using Git and GitHub'],['../build-windows.html#windows_github',1,'Building using Git and GitHub']]],
  ['using_20iaa_20compression_35',['Using iaa compression',['../compression.html#compression_iaa',1,'']]],
  ['using_20lsm_20trees_36',['Creating tables using LSM trees',['../lsm.html#lsm_schema',1,'']]],
  ['using_20lz4_20compression_37',['Using LZ4 compression',['../compression.html#compression_lz4',1,'']]],
  ['using_20rollback_20to_20stable_20with_20timestamps_38',['Using rollback-to-stable with timestamps',['../timestamp_misc.html#timestamp_misc_rts',1,'']]],
  ['using_20snappy_20compression_39',['Using snappy compression',['../compression.html#compression_snappy',1,'']]],
  ['using_20snapshots_40',['Transactions using Snapshots',['../arch-snapshot.html#snapshot_transaction',1,'']]],
  ['using_20the_20log_41',['Using the log',['../arch-logging.html#log_usage',1,'']]],
  ['using_20the_20wt_5fevent_5fhandler_42',['Message handling using the WT_EVENT_HANDLER',['../message_handling.html#event_message_handling',1,'']]],
  ['using_20transaction_20prepare_20with_20timestamps_43',['Using transaction prepare with timestamps',['../timestamp_prepare.html',1,'programming']]],
  ['using_20zlib_20compression_44',['Using zlib compression',['../compression.html#compression_zlib',1,'']]],
  ['using_20zstd_20compression_45',['Using zstd compression',['../compression.html#compression_zstd',1,'']]],
  ['usual_46',['Step 2: Build as usual',['../tool-libfuzzer.html#autotoc_md13',1,'']]],
  ['utilities_47',['Fuzz Utilities',['../tool-libfuzzer.html#autotoc_md18',1,'']]],
  ['utility_48',['utility',['../arch-metadata.html#metadata_wt_util',1,'Printing metadata with the wt utility'],['../command_line.html',1,'WiredTiger command line utility']]]
];
