var searchData=
[
  ['language_20name_20space_0',['C language name space',['../namespace.html#namespace_c',1,'']]],
  ['largest_20key_1',['Returning the largest key',['../cursor_ops.html#cursor_largest',1,'']]],
  ['largest_5fkey_2',['largest_key',['../struct_w_t___c_u_r_s_o_r.html#a49f70806bf693462e5644edbbb864c1b',1,'WT_CURSOR']]],
  ['last_5fcheckpoint_20timestamp_3',['Reading the &quot;last_checkpoint&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_last_checkpoint',1,'']]],
  ['layout_4',['Layout',['../arch-data-file.html#data_file_format',1,'Data File Format and Layout'],['../arch-data-file.html#data_file_on_disk_page_format',1,'On-Disk Page Format and Layout']]],
  ['layout_5',['WT_CONF storage layout',['../arch-config-compile.html#compile_layout',1,'']]],
  ['leaf_20child_20reconciliation_6',['Leaf (child) reconciliation',['../arch-fast-truncate.html#ft_leaf_reconciliation',1,'']]],
  ['leaf_20key_20value_20max_7',['internal/leaf key/value max',['../tune_page_size_and_comp.html#key_val_max',1,'']]],
  ['leaf_5fpage_5fmax_8',['leaf_page_max',['../tune_page_size_and_comp.html#leaf_page_max',1,'']]],
  ['len_9',['len',['../struct_w_t___c_o_n_f_i_g___i_t_e_m.html#adff0f6e5a3f781f0228015e8336f1a14',1,'WT_CONFIG_ITEM']]],
  ['length_20column_20stores_10',['length column stores',['../arch-row-column.html#row_column_flcs',1,'Fixed length column-stores'],['../arch-row-column.html#row_column_vlcs',1,'Variable length column-stores']]],
  ['level_20configuration_11',['Level Configuration',['../arch-prefetch.html#prefetch_api_connection',1,'Connection-Level Configuration'],['../arch-prefetch.html#prefetch_api_session',1,'Session-Level Configuration']]],
  ['level_20durability_12',['level durability',['../durability_checkpoint.html',1,'Checkpoint-level durability'],['../durability_log.html',1,'Commit-level durability'],['../tune_durability.html',1,'Commit-level durability'],['../durability_log.html#commit_durability_enable',1,'Enabling commit-level durability'],['../durability_log.html#commit_durability_tuning',1,'Tuning commit-level durability']]],
  ['level_20durability_20and_20logs_13',['Commit-level durability and logs',['../durability_log.html#commit_durability_logs',1,'']]],
  ['level_20durability_20and_20timestamps_14',['Logged objects, commit-level durability and timestamps',['../timestamp_model.html#timestamps_durability_commit',1,'']]],
  ['level_20durability_20without_20timestamps_15',['Commit-level durability (without timestamps)',['../durability_overview.html#explain_durability_commit',1,'']]],
  ['levels_16',['Verbosity Levels',['../verbose_messaging.html#verbosity_levels',1,'']]],
  ['levels_17',['levels',['../transactions_api.html#isolation_levels',1,'Isolation levels'],['../explain_isolation.html',1,'Tutorial: isolation levels']]],
  ['libfuzzer_18',['LibFuzzer',['../tool-libfuzzer.html#autotoc_md12',1,'Step 1: Configure with Clang as your C compiler and enable LibFuzzer'],['../tool-libfuzzer.html',1,'Testing with LLVM LibFuzzer']]],
  ['libfuzzer_20fuzzer_19',['LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'Building and running an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md16',1,'Implementing an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md20',1,'Viewing code coverage for an LLVM LibFuzzer fuzzer']]],
  ['library_20',['3rd party software always included in the WiredTiger library',['../license.html#license_library',1,'']]],
  ['library_3a_20ppc64_21',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['library_3a_20s390x_22',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['libsodium_20encryption_20extension_23',['The libsodium encryption extension',['../encryption.html#encryption_sodium',1,'']]],
  ['licensing_24',['WiredTiger licensing',['../license.html',1,'index']]],
  ['life_20cycle_25',['Life cycle',['../arch-connection.html#arch_conn_lifecycle',1,'']]],
  ['life_20cycle_26',['Data life cycle',['../tune_page_size_and_comp.html#data_life_cycle',1,'']]],
  ['lifecycle_27',['Data Handle Lifecycle',['../arch-dhandle.html#dhandle_data_handle_lifecycle',1,'']]],
  ['line_28',['Backup from the command line',['../backup.html#backup_util',1,'']]],
  ['line_20utility_29',['WiredTiger command line utility',['../command_line.html',1,'index']]],
  ['linux_20bsd_20os_20x_20_3a_30',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['linux_20transparent_20huge_20pages_31',['Linux transparent huge pages',['../tune_transparent_huge_pages.html',1,'programming']]],
  ['linux_20zone_20reclamation_20memory_20management_32',['Linux zone reclamation memory management',['../tune_zone_reclaim.html',1,'programming']]],
  ['list_33',['wt list',['../command_line.html#util_list',1,'']]],
  ['lists_34',['Extent lists',['../arch-block.html#block_lists',1,'']]],
  ['llvm_20and_20graphviz_35',['Step 1: Install LLVM and graphviz',['../tool-xray.html#autotoc_md56',1,'']]],
  ['llvm_20flags_36',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['llvm_20libfuzzer_37',['Testing with LLVM LibFuzzer',['../tool-libfuzzer.html',1,'tool-index']]],
  ['llvm_20libfuzzer_20fuzzer_38',['LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'Building and running an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md16',1,'Implementing an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md20',1,'Viewing code coverage for an LLVM LibFuzzer fuzzer']]],
  ['load_39',['load',['../tune_bulk_load.html',1,'Bulk-load'],['../command_line.html#util_load',1,'wt load']]],
  ['load_5fextension_40',['load_extension',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#ab6a56facfd217e5ff687aa4c012e8d68',1,'WT_CONNECTION']]],
  ['loadable_20extensions_41',['Loadable extensions',['../extensions.html#extensions_loadable',1,'']]],
  ['loader_20options_42',['Changing compiler or loader options',['../build-posix.html#posix_compiler',1,'']]],
  ['loads_43',['Bulk loads',['../durability_log.html#commit_durability_bulk',1,'']]],
  ['loadtext_44',['wt loadtext',['../command_line.html#util_loadtext',1,'']]],
  ['local_20extensions_45',['Local extensions',['../extensions.html#extensions_local',1,'']]],
  ['local_20file_20removal_46',['Local File Removal',['../arch-tiered-storage.html#ts_block_local_file_removal',1,'']]],
  ['lock_47',['Eviction (no queue lock)',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples-eviction0',1,'']]],
  ['lock_20usage_48',['Lock usage',['../arch-concurrency.html#lock-usage',1,'']]],
  ['locking_49',['Locking',['../arch-concurrency.html#locking',1,'']]],
  ['locks_50',['locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-cache-and-eviction',1,'Cache and Eviction locks'],['../arch-locking-hierarchy.html#arch-locking-hierarchy-checkpoint-schema',1,'Checkpoint and Schema locks'],['../arch-locking-hierarchy.html#arch-locking-hierarchy-log',1,'Log locks'],['../arch-locking-hierarchy.html#arch-locking-hierarchy-checkpoint-misc',1,'Miscellaneous locks']]],
  ['locks_20hierarchy_51',['Locks hierarchy',['../arch-locking-hierarchy.html',1,'arch-toc-int-wt-dev']]],
  ['log_52',['Log',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples-log',1,'']]],
  ['log_53',['log',['../tool-xray.html#autotoc_md60',1,'Step 1: Take a copy of the wtperf binary and the XRay log'],['../arch-logging.html#log_usage',1,'Using the log']]],
  ['log_20based_20incremental_20backup_54',['Log-based Incremental backup',['../backup.html#backup_incremental',1,'']]],
  ['log_20based_20incremental_20backup_55',['Log-based incremental backup',['../arch-backup.html#autotoc_md3',1,'']]],
  ['log_20cursors_56',['Log cursors',['../cursor_log.html',1,'Log cursors'],['../durability_log.html#commit_log_cursors',1,'Log cursors']]],
  ['log_20file_20archival_20and_20removal_57',['Log file archival and removal',['../durability_log.html#commit_durability_archiving',1,'']]],
  ['log_20file_20format_58',['Log File Format',['../arch-log-file.html',1,'arch-toc-recovery']]],
  ['log_20files_59',['log files',['../tool-optrack.html#autotoc_md33',1,'Becoming familiar with the operation tracking log files'],['../tool-optrack.html#autotoc_md34',1,'Processing the log files'],['../tool-optrack.html#autotoc_md32',1,'Working with log files']]],
  ['log_20locks_60',['Log locks',['../arch-locking-hierarchy.html#arch-locking-hierarchy-log',1,'']]],
  ['log_20operations_20and_20records_61',['Log operations and records',['../arch-logging.html#log_records',1,'']]],
  ['log_20related_20files_20in_20the_20database_20directory_62',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['log_20structured_20merge_20trees_63',['Log-Structured Merge Trees',['../lsm.html',1,'programming']]],
  ['log_5fflush_64',['log_flush',['../struct_w_t___s_e_s_s_i_o_n.html#a1843292630960309129dcfe00e1a3817',1,'WT_SESSION']]],
  ['log_5fprintf_65',['log_printf',['../struct_w_t___s_e_s_s_i_o_n.html#ac85541ca42d7596857d9f50e03c78eb5',1,'WT_SESSION']]],
  ['logged_20objects_20commit_20level_20durability_20and_20timestamps_66',['Logged objects, commit-level durability and timestamps',['../timestamp_model.html#timestamps_durability_commit',1,'']]],
  ['logging_67',['Logging',['../arch-logging.html',1,'Logging'],['../tool-statistics.html',1,'Statistics Logging']]],
  ['logging_68',['logging',['../readonly.html#readonly_logging',1,'Readonly configuration and logging'],['../statistics.html#statistics_log',1,'Statistics logging']]],
  ['logging_20subsystem_20data_20structures_20and_20algorithms_69',['Logging subsystem data structures and algorithms',['../arch-logging.html#log_subsystem',1,'']]],
  ['logs_70',['Commit-level durability and logs',['../durability_log.html#commit_durability_logs',1,'']]],
  ['logs_20to_20the_20operation_20tracking_20format_20optional_71',['Convert XRay logs to the Operation Tracking format (optional)',['../tool-xray.html#autotoc_md59',1,'']]],
  ['looking_20at_20the_20data_3a_20part_201_72',['Looking at the data: Part 1',['../tool-optrack.html#autotoc_md36',1,'']]],
  ['looking_20at_20the_20data_3a_20part_202_73',['Looking at the data: Part 2',['../tool-optrack.html#autotoc_md38',1,'']]],
  ['lsm_20trees_74',['LSM trees',['../lsm.html#lsm_schema',1,'Creating tables using LSM trees'],['../lsm.html#lsm_description',1,'Description of LSM trees'],['../lsm.html#lsm_api',1,'Interface to LSM trees'],['../readonly.html#readonly_lsm',1,'Readonly configuration and LSM trees']]],
  ['lsm_5fpre_5fmerge_75',['lsm_pre_merge',['../group__wt__ext.html#afe905b28d7831df185f9623c62f40e35',1,'WT_DATA_SOURCE']]],
  ['lz4_20compression_76',['Using LZ4 compression',['../compression.html#compression_lz4',1,'']]]
];
