var searchData=
[
  ['familiar_20with_20the_20operation_20tracking_20log_20files_0',['Becoming familiar with the operation tracking log files',['../tool-optrack.html#autotoc_md33',1,'']]],
  ['fast_20truncate_1',['Deleted Pages and Fast-Truncate',['../arch-fast-truncate.html',1,'arch-toc-fundamentals']]],
  ['features_2',['WiredTiger Overview and Features',['../overview.html',1,'index']]],
  ['fetch_3',['Pre-fetch',['../arch-prefetch.html',1,'arch-toc-mem-disk']]],
  ['fetch_20algorithm_4',['Pre-fetch Algorithm',['../arch-prefetch.html#prefetch_algorithm',1,'']]],
  ['fetch_20api_5',['Pre-fetch API',['../arch-prefetch.html#prefetch_api',1,'']]],
  ['fetch_20queue_6',['Populating the Pre-fetch Queue',['../arch-prefetch.html#prefetch_algorithm_populate_queue',1,'']]],
  ['fetch_20queue_20remain_20valid_7',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['fetching_20content_20into_20the_20cache_8',['Pre-fetching Content Into the Cache',['../arch-prefetch.html#prefetch_algorithm_process_pages',1,'']]],
  ['fetching_20useful_9',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['fetching_20when_20is_20pre_20fetching_20useful_10',['What is pre-fetching? When is pre-fetching useful?',['../arch-prefetch.html#prefetch_overview',1,'']]],
  ['fh_5fadvise_11',['fh_advise',['../group__wt__ext.html#a5b68b388279c64add7b0ef893b1d2e00',1,'WT_FILE_HANDLE']]],
  ['fh_5fextend_12',['fh_extend',['../group__wt__ext.html#ab4b685446f0ce09b7270dd32bb771ce7',1,'WT_FILE_HANDLE']]],
  ['fh_5fextend_5fnolock_13',['fh_extend_nolock',['../group__wt__ext.html#a2479acb713a211b2d7cc84aaada4b29b',1,'WT_FILE_HANDLE']]],
  ['fh_5flock_14',['fh_lock',['../group__wt__ext.html#a5db2aa421c5297d9119b9517e1117afb',1,'WT_FILE_HANDLE']]],
  ['fh_5fmap_15',['fh_map',['../group__wt__ext.html#aff0f1b582876fc0fad4d2093197d1124',1,'WT_FILE_HANDLE']]],
  ['fh_5fmap_5fdiscard_16',['fh_map_discard',['../group__wt__ext.html#a02b0e75636d323ce5bd42fdf7e83615e',1,'WT_FILE_HANDLE']]],
  ['fh_5fmap_5fpreload_17',['fh_map_preload',['../group__wt__ext.html#a350e1db2cd51c8c2479b03beae9af90f',1,'WT_FILE_HANDLE']]],
  ['fh_5fread_18',['fh_read',['../group__wt__ext.html#ad41718cb1f7a59cfb21a68785aa09897',1,'WT_FILE_HANDLE']]],
  ['fh_5fsize_19',['fh_size',['../group__wt__ext.html#a1e0b90f0a4fcf943e81b22b94069738b',1,'WT_FILE_HANDLE']]],
  ['fh_5fsync_20',['fh_sync',['../group__wt__ext.html#ad4f3371981540000e182ed0cb75eefad',1,'WT_FILE_HANDLE']]],
  ['fh_5fsync_5fnowait_21',['fh_sync_nowait',['../group__wt__ext.html#ad4203cea23fd8f62765564ba9a24fe6c',1,'WT_FILE_HANDLE']]],
  ['fh_5ftruncate_22',['fh_truncate',['../group__wt__ext.html#aadcd969865c263c9e9b00d39308e296c',1,'WT_FILE_HANDLE']]],
  ['fh_5funmap_23',['fh_unmap',['../group__wt__ext.html#a9e8786a0eedb67d92a9e8e5239faef6b',1,'WT_FILE_HANDLE']]],
  ['fh_5fwrite_24',['fh_write',['../group__wt__ext.html#ab69c295b076627307a6528793d7a9b43',1,'WT_FILE_HANDLE']]],
  ['field_25',['field',['../arch-fast-truncate.html#ft_instantiated_updates',1,'The inst_updates field'],['../arch-fast-truncate.html#ft_instantiated_instantiated',1,'The instantiated flag and the page_del field']]],
  ['fields_26',['WT_CURSOR key/value fields',['../custom_data_sources.html#custom_ds_cursor_fields',1,'']]],
  ['file_27',['file',['../arch-metadata.html#metadata_turtle',1,'Turtle file'],['../database_config.html#config_base',1,'WiredTiger.basecfg file'],['../database_config.html#config_file',1,'WiredTiger.config file']]],
  ['file_20allocation_28',['File allocation',['../tune_file_alloc.html',1,'programming']]],
  ['file_20archival_20and_20removal_29',['Log file archival and removal',['../durability_log.html#commit_durability_archiving',1,'']]],
  ['file_20block_20allocation_30',['File block allocation',['../tune_file_alloc.html#tuning_system_file_block_allocation',1,'']]],
  ['file_20checkpoint_31',['Data file checkpoint',['../arch-tiered-storage.html#ts_checkpoint_data_file',1,'']]],
  ['file_20compaction_32',['Checkpoints and file compaction',['../durability_checkpoint.html#checkpoint_compaction',1,'']]],
  ['file_20creation_20and_20the_20block_20manager_33',['File creation and the block manager',['../arch-block.html#creation',1,'']]],
  ['file_20cursors_34',['File cursors',['../arch-cursor.html#arch_cursor_file',1,'']]],
  ['file_20cursors_20btrees_20and_20data_20handles_35',['File cursors, Btrees and data handles',['../arch-cursor.html#arch_cursor_dhandle',1,'']]],
  ['file_20format_36',['File Format',['../arch-data-file.html',1,'Data File Format'],['../arch-log-file.html',1,'Log File Format']]],
  ['file_20format_37',['Choosing a file format',['../file_formats.html#file_formats_choice',1,'']]],
  ['file_20format_20and_20layout_38',['Data File Format and Layout',['../arch-data-file.html#data_file_format',1,'']]],
  ['file_20formats_39',['File formats',['../file_formats.html#file_formats_formats',1,'']]],
  ['file_20formats_20and_20compression_40',['File formats and compression',['../file_formats.html',1,'File formats and compression'],['../file_formats.html#file_formats_compression',1,'File formats and compression']]],
  ['file_20functions_41',['Data File Functions',['../arch-data-file.html#data_file_functions',1,'']]],
  ['file_20growth_42',['File growth',['../tune_file_alloc.html#tuning_system_file_block_grow',1,'']]],
  ['file_20handle_20interface_43',['File Handle Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_handle',1,'Cloud File Handle Interface'],['../arch-fs-os.html#file_handle',1,'File Handle Interface']]],
  ['file_20handle_20interfaces_44',['WiredTiger File System and File Handle Interfaces',['../arch-fs-os.html#file_system_and_handle',1,'']]],
  ['file_20permissions_45',['File permissions',['../security.html#file_permissions',1,'']]],
  ['file_20removal_46',['Local File Removal',['../arch-tiered-storage.html#ts_block_local_file_removal',1,'']]],
  ['file_20stream_47',['File Stream',['../arch-fs-os.html#file_stream',1,'']]],
  ['file_20system_20and_20file_20handle_20interfaces_48',['WiredTiger File System and File Handle Interfaces',['../arch-fs-os.html#file_system_and_handle',1,'']]],
  ['file_20system_20and_20handle_20customization_49',['File System and Handle Customization',['../arch-fs-os.html#file_customization',1,'']]],
  ['file_20system_20interface_50',['File System Interface',['../arch-cloud-storage-extension.html#extension_cloud_file_system',1,'Cloud File System Interface'],['../arch-fs-os.html#file_system',1,'File System Interface']]],
  ['file_20system_20interface_20and_20operating_20system_20support_51',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['file_20system_20name_20space_52',['File system name space',['../namespace.html#namespace_filesystem',1,'']]],
  ['file_20systems_53',['Custom File Systems',['../custom_file_systems.html',1,'programming']]],
  ['file_20systems_54',['Remote file systems',['../filesystems.html#remote',1,'']]],
  ['file_5fsystem_55',['file_system',['../group__wt__ext.html#a8a8cadc351799d3f5c1b55d266cff780',1,'WT_FILE_HANDLE']]],
  ['file_5fsystem_5fget_56',['file_system_get',['../group__wt__ext.html#a2faf34830a57d69b6e7e8ae6310e69f7',1,'WT_EXTENSION_API']]],
  ['files_57',['Files',['../arch-schema.html#schema_files',1,'Data Files'],['../arch-data-file.html#data_file_database_files',1,'Database Files'],['../arch-btree.html#btree_range_truncate_file',1,'Range Truncate On Files'],['../data_sources.html#data_files',1,'Raw Files']]],
  ['files_58',['files',['../tool-optrack.html#autotoc_md33',1,'Becoming familiar with the operation tracking log files'],['../tool-optrack.html#autotoc_md34',1,'Processing the log files'],['../tool-optrack.html#autotoc_md32',1,'Working with log files']]],
  ['files_20and_20pages_59',['Reading files and pages',['../arch-block.html#read',1,'']]],
  ['files_20in_20the_20block_20manager_60',['Files in the Block Manager',['../arch-tiered-storage.html#ts_block_files',1,'']]],
  ['files_20in_20the_20database_20directory_61',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['filesystems_62',['Filesystems',['../filesystems.html',1,'admin']]],
  ['filters_63',['Bloom filters',['../lsm.html#lsm_bloom',1,'']]],
  ['finding_20candidate_20pages_64',['Finding Candidate Pages',['../arch-prefetch.html#prefetch_algorithm_find_pages',1,'']]],
  ['fixed_20length_20column_20stores_65',['Fixed length column-stores',['../arch-row-column.html#row_column_flcs',1,'']]],
  ['flag_20and_20the_20page_5fdel_20field_66',['The instantiated flag and the page_del field',['../arch-fast-truncate.html#ft_instantiated_instantiated',1,'']]],
  ['flags_67',['Step 2: Configure and build WiredTiger with LLVM flags',['../tool-xray.html#autotoc_md61',1,'']]],
  ['flame_20graphs_68',['CPU Flame Graphs',['../tool-perf-flamegraphs.html',1,'tool-index']]],
  ['flamegraphs_69',['Generating FlameGraphs',['../tool-perf-flamegraphs.html#autotoc_md41',1,'']]],
  ['flat_20string_20format_70',['Flat string format',['../message_handling.html#message_handling_output_flat_string',1,'']]],
  ['flcs_20and_20deleted_20pages_71',['FLCS and deleted pages',['../arch-fast-truncate.html#ft_flcs',1,'']]],
  ['flush_20actions_72',['Flush actions',['../arch-tiered-storage.html#ts_checkpoint_flush',1,'']]],
  ['flush_20call_20configuration_73',['Flush call configuration',['../durability_log.html#commit_durability_flush_config',1,'Flush call configuration'],['../tune_durability.html#tune_durability_flush_config',1,'Flush call configuration']]],
  ['flush_20checkpoint_20operations_74',['Flush Checkpoint Operations',['../arch-tiered-storage.html#ts_flush',1,'']]],
  ['flush_5ftier_20operation_75',['The flush_tier operation',['../tiered_storage.html#flush_tier',1,'']]],
  ['for_20a_20single_20table_76',['RTS for a single table',['../arch-rts.html#rts-for-a-single-table',1,'']]],
  ['for_20an_20llvm_20libfuzzer_20fuzzer_77',['Viewing code coverage for an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md20',1,'']]],
  ['for_20indices_78',['Custom Collators for Indices',['../custom_collators.html#custom_collators_indices',1,'']]],
  ['for_20multiple_20operating_20systems_79',['Support for Multiple Operating Systems',['../arch-fs-os.html#multiple_os',1,'']]],
  ['for_20older_20versions_20of_20a_20key_20in_20history_20store_80',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['for_20viewing_81',['Preparing data for viewing',['../tool-optrack.html#autotoc_md35',1,'']]],
  ['foreground_20compaction_82',['Foreground compaction',['../compact.html#foreground',1,'']]],
  ['format_83',['Format',['../arch-data-file.html',1,'Data File Format'],['../arch-log-file.html',1,'Log File Format']]],
  ['format_84',['format',['../file_formats.html#file_formats_choice',1,'Choosing a file format'],['../message_handling.html#message_handling_output_flat_string',1,'Flat string format'],['../dump_formats.html#dump_formats_json',1,'JSON dump format'],['../message_handling.html#message_handling_output_json',1,'JSON format'],['../arch-fast-truncate.html#ft_on_disk_format',1,'On-disk format'],['../dump_formats.html#dump_formats_text',1,'Text dump format'],['../timestamp_model.html#timestamps_format',1,'Timestamp format']]],
  ['format_20and_20layout_85',['Format and Layout',['../arch-data-file.html#data_file_format',1,'Data File Format and Layout'],['../arch-data-file.html#data_file_on_disk_page_format',1,'On-Disk Page Format and Layout']]],
  ['format_20of_20the_20wt_5fevent_5fhandler_86',['Output format of the WT_EVENT_HANDLER',['../message_handling.html#message_handling_output',1,'']]],
  ['format_20optional_87',['Convert XRay logs to the Operation Tracking format (optional)',['../tool-xray.html#autotoc_md59',1,'']]],
  ['format_20types_88',['Format types',['../schema.html#schema_format_types',1,'']]],
  ['formats_89',['Formats',['../arch-schema.html#schema_data_formats',1,'Data Formats'],['../dump_formats.html',1,'Dump Formats']]],
  ['formats_90',['formats',['../schema.html#schema_cursor_formats',1,'Cursor formats'],['../file_formats.html#file_formats_formats',1,'File formats'],['../schema.html#schema_key_and_value_formats',1,'Key and value formats']]],
  ['formats_20and_20compression_91',['formats and compression',['../file_formats.html',1,'File formats and compression'],['../file_formats.html#file_formats_compression',1,'File formats and compression']]],
  ['from_20an_20application_92',['Backup from an application',['../backup.html#backup_process',1,'']]],
  ['from_20the_20command_20line_93',['Backup from the command line',['../backup.html#backup_util',1,'']]],
  ['fs_5fdirectory_5flist_94',['fs_directory_list',['../group__wt__ext.html#a461137686ca8dc659b314b29f7c98299',1,'WT_FILE_SYSTEM']]],
  ['fs_5fdirectory_5flist_5ffree_95',['fs_directory_list_free',['../group__wt__ext.html#a96913fda6ff35e7543fabb02b76d71eb',1,'WT_FILE_SYSTEM']]],
  ['fs_5fexist_96',['fs_exist',['../group__wt__ext.html#a04768a78e64d45bb61b170e6c2dcb3a2',1,'WT_FILE_SYSTEM']]],
  ['fs_5fopen_5ffile_97',['fs_open_file',['../group__wt__ext.html#a86d9e245b3e20bb3faae46767c11df99',1,'WT_FILE_SYSTEM']]],
  ['fs_5fremove_98',['fs_remove',['../group__wt__ext.html#a1c57a707ff18f2766c3132ddcb405b26',1,'WT_FILE_SYSTEM']]],
  ['fs_5frename_99',['fs_rename',['../group__wt__ext.html#a39b082e5c6649954d3ebc2b158fe9ab8',1,'WT_FILE_SYSTEM']]],
  ['fs_5fsize_100',['fs_size',['../group__wt__ext.html#a2e97ea38029d156f3ead1cea90652c47',1,'WT_FILE_SYSTEM']]],
  ['full_101',['Eviction (full)',['../arch-locking-hierarchy.html#arch-locking-hierarchy-examples-eviction',1,'']]],
  ['full_20barrier_102',['Full barrier',['../arch-concurrency.html#full-bar',1,'']]],
  ['full_20database_103',['Full database',['../arch-backup.html#autotoc_md1',1,'']]],
  ['function_20calls_104',['Track function calls',['../operation_tracking.html',1,'programming']]],
  ['functions_105',['Data File Functions',['../arch-data-file.html#data_file_functions',1,'']]],
  ['fundamentals_106',['Fundamentals',['../arch-toc-fundamentals.html',1,'arch-index']]],
  ['further_20details_107',['Further details',['../arch-usage-patterns.html#growable-arrays-further-details',1,'']]],
  ['future_108',['Future',['../arch-tiered-storage.html#ts_future',1,'']]],
  ['fuzz_20utilities_109',['Fuzz Utilities',['../tool-libfuzzer.html#autotoc_md18',1,'']]],
  ['fuzzer_110',['fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'Building and running an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md16',1,'Implementing an LLVM LibFuzzer fuzzer'],['../tool-libfuzzer.html#autotoc_md22',1,'Step 2: Build and run fuzzer'],['../tool-libfuzzer.html#autotoc_md14',1,'Step 3: Run a fuzzer'],['../tool-libfuzzer.html#autotoc_md20',1,'Viewing code coverage for an LLVM LibFuzzer fuzzer']]]
];
