var searchData=
[
  ['race_0',['Win the Race',['../arch-usage-patterns.html#win-the-race',1,'']]],
  ['random_1',['Cursor random',['../cursor_random.html',1,'cursor_ops']]],
  ['random_20cursor_2',['Random Cursor',['../arch-cursor.html#arch_random_cursor',1,'']]],
  ['range_20bounded_20cursors_3',['Range bounded cursors',['../arch-cursor.html#arch_cursor_bound',1,'']]],
  ['range_20truncate_20on_20files_4',['Range Truncate On Files',['../arch-btree.html#btree_range_truncate_file',1,'']]],
  ['range_5ftruncate_5',['range_truncate',['../group__wt__ext.html#aaf57e661895f06a479dc359d51819d7c',1,'WT_DATA_SOURCE']]],
  ['rationale_20and_20details_6',['Safety rationale and details',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_safety',1,'']]],
  ['raw_20files_7',['Raw Files',['../data_sources.html#data_files',1,'']]],
  ['raw_20mode_8',['Raw mode',['../cursors.html#cursor_raw',1,'']]],
  ['raw_20mode_9',['Custom Collators in raw mode',['../custom_extractors.html#custom_extractors_raw',1,'']]],
  ['read_10',['wt read',['../command_line.html#util_read',1,'']]],
  ['read_20only_20configuration_20considerations_11',['Database read-only configuration considerations',['../readonly.html#readonly_config',1,'']]],
  ['read_20only_20mode_12',['Database read-only mode',['../readonly.html',1,'programming']]],
  ['read_20only_20objects_13',['Read-only objects',['../tune_read_only.html',1,'programming']]],
  ['read_20timestamp_14',['read timestamp',['../timestamp_misc.html#timestamp_read_roundup',1,'Rounding up the read timestamp'],['../timestamp_txn_api.html#timestamp_txn_api_read_timestamp',1,'Setting the transaction&apos;s read timestamp']]],
  ['read_20uncommitted_20modifies_15',['Snapshot Read-uncommitted \&amp; Modifies',['../arch-snapshot.html#snapshot_read_uncommitted',1,'']]],
  ['reading_16',['Reading',['../arch-usage-patterns.html#slotted-arrays-reading',1,'Reading'],['../arch-usage-patterns.html#growable-arrays-reading',1,'Reading']]],
  ['reading_20files_20and_20pages_17',['Reading files and pages',['../arch-block.html#read',1,'']]],
  ['reading_20metadata_18',['Reading Metadata',['../arch-metadata.html#metadata_reading',1,'']]],
  ['reading_20the_20all_5fdurable_20timestamp_19',['Reading the &quot;all_durable&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_all_durable',1,'']]],
  ['reading_20the_20last_5fcheckpoint_20timestamp_20',['Reading the &quot;last_checkpoint&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_last_checkpoint',1,'']]],
  ['reading_20the_20oldest_5freader_20timestamp_21',['Reading the &quot;oldest_reader&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_oldest_reader',1,'']]],
  ['reading_20the_20oldest_5ftimestamp_20timestamp_22',['Reading the &quot;oldest_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_oldest_timestamp',1,'']]],
  ['reading_20the_20pinned_20timestamp_23',['Reading the &quot;pinned&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_pinned',1,'']]],
  ['reading_20the_20recovery_20timestamp_24',['Reading the &quot;recovery&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_recovery',1,'']]],
  ['reading_20the_20stable_5ftimestamp_20timestamp_25',['Reading the &quot;stable_timestamp&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_stable_timestamp',1,'']]],
  ['reading_20unnecessary_20pages_20into_20memory_26',['Skipping reading unnecessary pages into memory',['../arch-rts.html#rts-page-skip',1,'']]],
  ['reading_20while_20allowing_20writes_27',['Correctness of allowing reading while allowing writes',['../arch-usage-patterns.html#slotted-arrays-correctness',1,'']]],
  ['reading_20wiredtiger_20metadata_28',['Reading WiredTiger Metadata',['../cursors.html#metadata',1,'']]],
  ['readonly_20configuration_20and_20logging_29',['Readonly configuration and logging',['../readonly.html#readonly_logging',1,'']]],
  ['readonly_20configuration_20and_20lsm_20trees_30',['Readonly configuration and LSM trees',['../readonly.html#readonly_lsm',1,'']]],
  ['readonly_20configuration_20and_20multiple_20database_20handles_31',['Readonly configuration and multiple database handles',['../readonly.html#readonly_handles',1,'']]],
  ['readonly_20configuration_20and_20recovery_32',['Readonly configuration and recovery',['../readonly.html#readonly_recovery',1,'']]],
  ['reads_20and_20writes_33',['Atomic reads and writes',['../portability.html#atomic-reads-writes',1,'']]],
  ['reclamation_20memory_20management_34',['Linux zone reclamation memory management',['../tune_zone_reclaim.html',1,'programming']]],
  ['reconciliation_35',['reconciliation',['../arch-hs.html#arch_hs_reconciliation',1,'History store and reconciliation'],['../arch-fast-truncate.html#ft_internal_reconciliation',1,'Internal page reconciliation'],['../arch-fast-truncate.html#ft_leaf_reconciliation',1,'Leaf (child) reconciliation']]],
  ['reconfigure_36',['reconfigure',['../struct_w_t___c_u_r_s_o_r.html#ad6a97a309e2c1ada7ca32a422c46612a',1,'WT_CURSOR::reconfigure()'],['../struct_w_t___s_e_s_s_i_o_n.html#a578f0fbd8a83339f1f9c00e135f006e6',1,'WT_SESSION::reconfigure()'],['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a579141678af06217b22869cbc604c6d4',1,'WT_CONNECTION::reconfigure()']]],
  ['records_37',['Log operations and records',['../arch-logging.html#log_records',1,'']]],
  ['recovery_38',['Recovery',['../custom_collators.html#custom_collators_recovery',1,'Custom Collators and Recovery'],['../arch-toc-recovery.html',1,'Recovery'],['../durability_log.html#commit_durability_recovery',1,'Recovery']]],
  ['recovery_39',['recovery',['../extensions.html#extensions_recovery',1,'Extensions and recovery'],['../readonly.html#readonly_recovery',1,'Readonly configuration and recovery']]],
  ['recovery_20timestamp_40',['Reading the &quot;recovery&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_recovery',1,'']]],
  ['reference_20counts_41',['Data Handle Reference Counts',['../arch-dhandle.html#dhandle_data_handle_reference_counts',1,'']]],
  ['reference_20guide_42',['Reference Guide',['../index.html',1,'']]],
  ['references_20on_20the_20pre_20fetch_20queue_20remain_20valid_43',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['related_20files_20in_20the_20database_20directory_44',['Log-related files in the database directory',['../arch-logging.html#log_files',1,'']]],
  ['related_20pages_45',['Related pages',['../arch-eviction.html#eviction_related',1,'Related pages'],['../arch-logging.html#log_related',1,'Related pages']]],
  ['release_46',['Release',['../arch-concurrency.html#rel-marked',1,'']]],
  ['release_47',['Message passing with acquire and release',['../arch-usage-patterns.html#message-passing',1,'']]],
  ['release_20barrier_48',['Release barrier',['../arch-concurrency.html#rel-bar',1,'']]],
  ['remain_20valid_49',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['remote_20file_20systems_50',['Remote file systems',['../filesystems.html#remote',1,'']]],
  ['removal_51',['Local File Removal',['../arch-tiered-storage.html#ts_block_local_file_removal',1,'']]],
  ['removal_52',['Log file archival and removal',['../durability_log.html#commit_durability_archiving',1,'']]],
  ['remove_53',['remove',['../struct_w_t___c_u_r_s_o_r.html#abbba24fe607fee519c4c9c4669cd4455',1,'WT_CURSOR']]],
  ['removing_20and_20updating_54',['Inserting, removing and updating',['../cursor_ops.html#cursor_writes',1,'']]],
  ['rename_55',['Rename',['../arch-schema.html#schema_rename',1,'']]],
  ['rename_56',['rename',['../group__wt__ext.html#a0522ef61652b275fa4aadab7fd1ac884',1,'WT_DATA_SOURCE::rename'],['../struct_w_t___s_e_s_s_i_o_n.html#a1d24b02549009f78b7c6463da0247614',1,'WT_SESSION::rename()'],['../command_line.html#util_rename',1,'wt rename']]],
  ['replaying_20prepared_20transactions_20by_20rounding_20up_20the_20prepare_20timestamp_57',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]],
  ['representation_58',['B-Tree In-Memory Representation',['../arch-btree.html#btree_btree_in_memory_representation',1,'']]],
  ['representation_20of_20timestamps_20and_20time_20windows_59',['Representation of timestamps and time windows',['../arch-timestamp.html#arch-timestamp-representation',1,'']]],
  ['requirements_20of_20wiredtiger_60',['Hardware requirements of WiredTiger',['../portability.html#hardware-requirements',1,'']]],
  ['reserve_61',['reserve',['../struct_w_t___c_u_r_s_o_r.html#a3acc1fd180c4a4220b459734305c90a6',1,'WT_CURSOR']]],
  ['reset_62',['reset',['../struct_w_t___c_u_r_s_o_r.html#afc1b42c22c9c85e1ba08ce3b34437565',1,'WT_CURSOR::reset()'],['../struct_w_t___s_e_s_s_i_o_n.html#a307800663ed211447a18c46863c28787',1,'WT_SESSION::reset(WT_SESSION *session)']]],
  ['reset_5fsnapshot_63',['reset_snapshot',['../struct_w_t___s_e_s_s_i_o_n.html#a2117021276bad0e6f541e61a5459ec59',1,'WT_SESSION']]],
  ['resetting_20the_20session_20snapshot_64',['Resetting the session snapshot',['../transactions_api.html#snapshot_reset',1,'']]],
  ['resident_20objects_65',['Cache resident objects',['../tune_cache.html#tuning_cache_resident',1,'']]],
  ['resources_66',['Other Resources',['../tool-index.html#tool-other',1,'']]],
  ['restore_20eviction_67',['Update restore eviction',['../eviction.html#update_restore_eviction',1,'']]],
  ['return_20name_20space_68',['Error return name space',['../namespace.html#namespace_error',1,'']]],
  ['returning_20the_20largest_20key_69',['Returning the largest key',['../cursor_ops.html#cursor_largest',1,'']]],
  ['rollback_20to_20stable_70',['History store and rollback to stable',['../arch-hs.html#arch_hs_rts',1,'']]],
  ['rollback_20to_20stable_20rts_71',['Rollback to Stable (RTS)',['../arch-rts.html',1,'arch-toc-fundamentals']]],
  ['rollback_20to_20stable_20with_20timestamps_72',['Using rollback-to-stable with timestamps',['../timestamp_misc.html#timestamp_misc_rts',1,'']]],
  ['rollback_5fto_5fstable_73',['rollback_to_stable',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a93dbc74accb426582b3c5c2f69e04b28',1,'WT_CONNECTION']]],
  ['rollback_5ftransaction_74',['rollback_transaction',['../struct_w_t___s_e_s_s_i_o_n.html#ab45f521464ad9e54d9b15efc2ffe20a1',1,'WT_SESSION']]],
  ['rotn_20encryption_20extension_75',['The rotn encryption extension',['../encryption.html#encryption_rotn',1,'']]],
  ['rounding_76',['Automatic prepare timestamp rounding',['../timestamp_prepare_roundup.html',1,'programming']]],
  ['rounding_20up_20the_20prepare_20timestamp_77',['Replaying prepared transactions by rounding up the prepare timestamp',['../timestamp_prepare_roundup.html#timestamp_prepare_roundup_replay',1,'']]],
  ['rounding_20up_20the_20read_20timestamp_78',['Rounding up the read timestamp',['../timestamp_misc.html#timestamp_read_roundup',1,'']]],
  ['row_20store_20and_20column_20store_79',['Row Store and Column Store',['../arch-row-column.html',1,'arch-toc-data-src']]],
  ['row_20stores_80',['Row-stores',['../arch-row-column.html#row_column_rs',1,'']]],
  ['rows_20and_20columns_81',['Tables, rows and columns',['../schema.html#schema_intro',1,'']]],
  ['rts_82',['RTS',['../arch-rts.html#rts-overview',1,'Overview of RTS'],['../arch-rts.html',1,'Rollback to Stable (RTS)']]],
  ['rts_20aborts_20unstable_20updates_83',['How RTS aborts unstable updates',['../arch-rts.html#rts-abort-updates',1,'']]],
  ['rts_20for_20a_20single_20table_84',['RTS for a single table',['../arch-rts.html#rts-for-a-single-table',1,'']]],
  ['rules_85',['History store cursor interface and visibility rules',['../arch-hs.html#arch_hs_cursor_visibility',1,'']]],
  ['run_20a_20fuzzer_86',['Step 3: Run a fuzzer',['../tool-libfuzzer.html#autotoc_md14',1,'']]],
  ['run_20fuzzer_87',['Step 2: Build and run fuzzer',['../tool-libfuzzer.html#autotoc_md22',1,'']]],
  ['run_20mode_88',['Dry-run mode',['../arch-rts.html#dry-run-mode',1,'']]],
  ['run_20wtperf_89',['Step 3: Run wtperf',['../tool-xray.html#autotoc_md58',1,'']]],
  ['running_20an_20llvm_20libfuzzer_20fuzzer_90',['Building and running an LLVM LibFuzzer fuzzer',['../tool-libfuzzer.html#autotoc_md11',1,'']]],
  ['running_20perf_20with_20wiredtiger_91',['Running perf with WiredTiger',['../tool-perf.html#autotoc_md43',1,'']]],
  ['running_20wiredtiger_20c_20c_20tests_92',['Running WiredTiger C C Tests',['../build-posix.html#posix_ctest',1,'Running WiredTiger C/C++ Tests'],['../build-windows.html#windows_ctest',1,'Running WiredTiger C/C++ Tests']]],
  ['runtime_93',['Runtime',['../arch-connection.html#arch_conn_runtime',1,'']]],
  ['runtime_20diagnostics_94',['Configuring runtime diagnostics',['../debugging.html#extra_diagnostics_configuration',1,'']]],
  ['runtime_20overhead_95',['Will operation tracking introduce runtime overhead?',['../tool-optrack.html#autotoc_md27',1,'']]]
];
