var searchData=
[
  ['o_0',['Direct I/O',['../tune_system_buffer_cache.html#tuning_system_buffer_cache_direct_io',1,'']]],
  ['o_20more_20valuable_1',['Making I/O more valuable',['../overview.html#io',1,'']]],
  ['o_5fdirect_2',['Backup and O_DIRECT',['../backup.html#backup_o_direct',1,'']]],
  ['object_20ids_3',['Object IDs',['../arch-tiered-storage.html#ts_objectid',1,'']]],
  ['object_20notation_20json_20compatibility_4',['JavaScript Object Notation (JSON) compatibility',['../config_strings.html#config_json',1,'']]],
  ['objects_5',['Sharing of Tiered Objects',['../arch-tiered-storage.html#ts_future_sharing',1,'']]],
  ['objects_6',['objects',['../tune_cache.html#tuning_cache_resident',1,'Cache resident objects'],['../durability_checkpoint.html#checkpoint_target',1,'Checkpointing specific objects'],['../tune_read_only.html',1,'Read-only objects']]],
  ['objects_20commit_20level_20durability_20and_20timestamps_7',['Logged objects, commit-level durability and timestamps',['../timestamp_model.html#timestamps_durability_commit',1,'']]],
  ['of_20a_20key_20in_20history_20store_8',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['of_20allowing_20reading_20while_20allowing_20writes_9',['Correctness of allowing reading while allowing writes',['../arch-usage-patterns.html#slotted-arrays-correctness',1,'']]],
  ['of_20encryption_20in_20wiredtiger_10',['Overview of Encryption in WiredTiger',['../encryption.html#encryption_overview',1,'']]],
  ['of_20lsm_20trees_11',['Description of LSM trees',['../lsm.html#lsm_description',1,'']]],
  ['of_20other_20deleted_20pages_12',['Generation of other deleted pages',['../arch-fast-truncate.html#ft_deleted_generation',1,'']]],
  ['of_20rts_13',['Overview of RTS',['../arch-rts.html#rts-overview',1,'']]],
  ['of_20terms_14',['Glossary of Terms',['../arch-glossary.html',1,'arch-index']]],
  ['of_20the_20implementation_15',['Pointers to pieces of the implementation',['../arch-fast-truncate.html#ft_pointers',1,'']]],
  ['of_20the_20outlier_20thresholds_16',['Getting a more precise control of the outlier thresholds',['../tool-optrack.html#autotoc_md37',1,'']]],
  ['of_20the_20wt_5fevent_5fhandler_17',['Output format of the WT_EVENT_HANDLER',['../message_handling.html#message_handling_output',1,'']]],
  ['of_20the_20wtperf_20binary_20and_20the_20xray_20log_18',['Step 1: Take a copy of the wtperf binary and the XRay log',['../tool-xray.html#autotoc_md60',1,'']]],
  ['of_20tiered_20objects_19',['Sharing of Tiered Objects',['../arch-tiered-storage.html#ts_future_sharing',1,'']]],
  ['of_20tiered_20storage_20in_20wiredtiger_20',['Overview of Tiered Storage in WiredTiger',['../custom_storage_sources.html#storage_overview',1,'']]],
  ['of_20timestamps_20and_20time_20windows_21',['Representation of timestamps and time windows',['../arch-timestamp.html#arch-timestamp-representation',1,'']]],
  ['of_20timestamps_20in_20updates_20and_20disk_20pages_22',['Handling of timestamps in updates and disk pages',['../arch-timestamp.html#arch-timestamp-handling',1,'']]],
  ['of_20wiredtiger_23',['Hardware requirements of WiredTiger',['../portability.html#hardware-requirements',1,'']]],
  ['offset_24',['offset',['../group__wt.html#ab51931e55a2bc958cb82155aa9bd413f',1,'WT_MODIFY']]],
  ['older_20than_2011_200_200_25',['Upgrading to Version older than 11.0.0',['../upgrading.html#pre_1100',1,'']]],
  ['older_20versions_20of_20a_20key_20in_20history_20store_26',['Searching for older versions of a key in History Store',['../arch-hs.html#arch_hs_read',1,'']]],
  ['oldest_5freader_20timestamp_27',['Reading the &quot;oldest_reader&quot; timestamp',['../timestamp_global_api.html#timestamp_global_query_api_oldest_reader',1,'']]],
  ['oldest_5ftimestamp_20timestamp_28',['oldest_timestamp timestamp',['../timestamp_global_api.html#timestamp_global_query_api_oldest_timestamp',1,'Reading the &quot;oldest_timestamp&quot; timestamp'],['../timestamp_global_api.html#timestamp_global_set_api_oldest_timestamp',1,'Setting the &quot;oldest_timestamp&quot; timestamp']]],
  ['on_20disk_20concepts_29',['On Disk Concepts',['../arch-toc-on-disk.html',1,'arch-index']]],
  ['on_20disk_20format_30',['On-disk format',['../arch-fast-truncate.html#ft_on_disk_format',1,'']]],
  ['on_20disk_20page_20format_20and_20layout_31',['On-Disk Page Format and Layout',['../arch-data-file.html#data_file_on_disk_page_format',1,'']]],
  ['on_20files_32',['Range Truncate On Files',['../arch-btree.html#btree_range_truncate_file',1,'']]],
  ['on_20portability_33',['General information on portability',['../portability.html',1,'index']]],
  ['on_20posix_20linux_20bsd_20os_20x_20_3a_34',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['on_20the_20history_20store_35',['Operations on the history store',['../arch-rts.html#operations-on-the-history-store',1,'']]],
  ['on_20the_20pre_20fetch_20queue_20remain_20valid_36',['Ensuring References on the Pre-fetch Queue Remain Valid',['../arch-prefetch.html#prefetch_other_refs',1,'']]],
  ['on_20visibility_37',['Notes on visibility',['../arch-fast-truncate.html#ft_visibility',1,'']]],
  ['on_20windows_38',['on Windows',['../build-windows.html',1,'Building and installing WiredTiger on Windows'],['../build-windows.html#windows_building',1,'Building on Windows']]],
  ['only_20configuration_20considerations_39',['Database read-only configuration considerations',['../readonly.html#readonly_config',1,'']]],
  ['only_20mode_40',['Database read-only mode',['../readonly.html',1,'programming']]],
  ['only_20objects_41',['Read-only objects',['../tune_read_only.html',1,'programming']]],
  ['open_20source_42',['NoSQL and Open Source',['../overview.html#nosql',1,'']]],
  ['open_5fcursor_43',['open_cursor',['../group__wt__ext.html#a81e45e31dedcdeaf8ff970d3c118da2e',1,'WT_DATA_SOURCE::open_cursor'],['../struct_w_t___s_e_s_s_i_o_n.html#afb5b4a69c2c5cafe411b2b04fdc1c75d',1,'WT_SESSION::open_cursor()']]],
  ['open_5fsession_44',['open_session',['../struct_w_t___c_o_n_n_e_c_t_i_o_n.html#adad5965cd4a60f65b5ac01f7ca6d1fc0',1,'WT_CONNECTION']]],
  ['opening_20a_20cursor_45',['Opening a cursor',['../cursor_ops.html#cursor_opening',1,'']]],
  ['operating_20system_20support_46',['File System Interface and Operating System Support',['../arch-fs-os.html',1,'arch-toc-platform']]],
  ['operating_20systems_47',['Support for Multiple Operating Systems',['../arch-fs-os.html#multiple_os',1,'']]],
  ['operation_48',['Truncate Operation',['../arch-btree.html#btree_truncate_operation',1,'']]],
  ['operation_49',['operation',['../arch-cache.html#arch_cache_basics',1,'Basic operation'],['../tiered_storage.html#flush_tier',1,'The flush_tier operation']]],
  ['operation_20tracking_50',['Operation Tracking',['../tool-optrack.html',1,'tool-index']]],
  ['operation_20tracking_51',['operation tracking',['../tool-optrack.html#autotoc_md31',1,'Enable operation tracking'],['../tool-optrack.html#autotoc_md25',1,'Why use operation tracking?']]],
  ['operation_20tracking_20format_20optional_52',['Convert XRay logs to the Operation Tracking format (optional)',['../tool-xray.html#autotoc_md59',1,'']]],
  ['operation_20tracking_20introduce_20runtime_20overhead_53',['Will operation tracking introduce runtime overhead?',['../tool-optrack.html#autotoc_md27',1,'']]],
  ['operation_20tracking_20log_20files_54',['Becoming familiar with the operation tracking log files',['../tool-optrack.html#autotoc_md33',1,'']]],
  ['operation_20tracking_20work_55',['How does operation tracking work?',['../tool-optrack.html#autotoc_md26',1,'']]],
  ['operations_56',['Operations',['../arch-tiered-storage.html#ts_flush',1,'Flush Checkpoint Operations'],['../arch-btree.html#btree_truncate_interaction_with_other_operations',1,'Interaction With Other Operations'],['../arch-session.html#arch_session_ops',1,'Operations']]],
  ['operations_57',['Cursor operations',['../cursor_ops.html',1,'cursors']]],
  ['operations_20and_20records_58',['Log operations and records',['../arch-logging.html#log_records',1,'']]],
  ['operations_20on_20the_20history_20store_59',['Operations on the history store',['../arch-rts.html#operations-on-the-history-store',1,'']]],
  ['optional_60',['Convert XRay logs to the Operation Tracking format (optional)',['../tool-xray.html#autotoc_md59',1,'']]],
  ['optionally_20included_20in_20the_20wiredtiger_20library_3a_20ppc64_61',['3rd party software optionally included in the WiredTiger library: PPC64',['../license.html#license_crc32-power8',1,'']]],
  ['optionally_20included_20in_20the_20wiredtiger_20library_3a_20s390x_62',['3rd party software optionally included in the WiredTiger library: s390x',['../license.html#license_crc32-zseries',1,'']]],
  ['options_63',['OPTIONS',['../command_line.html#util_global_options',1,'']]],
  ['options_64',['Options',['../command_line.html#util_backup_options',1,'Options'],['../command_line.html#util_compact_options',1,'Options'],['../command_line.html#util_copyright_options',1,'Options'],['../command_line.html#util_create_options',1,'Options'],['../command_line.html#util_downgrade_options',1,'Options'],['../command_line.html#util_drop_options',1,'Options'],['../command_line.html#util_dump_options',1,'Options'],['../command_line.html#util_list_options',1,'Options'],['../command_line.html#util_load_options',1,'Options'],['../command_line.html#util_loadtext_options',1,'Options'],['../command_line.html#util_printlog_options',1,'Options'],['../command_line.html#util_read_options',1,'Options'],['../command_line.html#util_rename_options',1,'Options'],['../command_line.html#util_salvage_options',1,'Options'],['../command_line.html#util_stat_options',1,'Options'],['../command_line.html#util_truncate_options',1,'Options'],['../command_line.html#util_verify_options',1,'Options'],['../command_line.html#util_write_options',1,'Options']]],
  ['options_65',['options',['../build-posix.html#posix_compiler',1,'Changing compiler or loader options'],['../arch-block.html#configuration',1,'Configuration options'],['../tune_build_options.html',1,'gcc/clang build options'],['../wtperf.html#config',1,'Wtperf configuration options']]],
  ['or_20loader_20options_66',['Changing compiler or loader options',['../build-posix.html#posix_compiler',1,'']]],
  ['or_20modified_20content_67',['Newly inserted or modified content',['../chunkcache.html#inserts',1,'']]],
  ['ordering_68',['Configuration ordering',['../database_config.html#config_order',1,'']]],
  ['organization_69',['Data Organization',['../arch-toc-data-org.html',1,'arch-index']]],
  ['os_20x_20_3a_70',['Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):',['../build-posix.html',1,'index']]],
  ['os_5fcache_5fdirty_5fmax_71',['os_cache_dirty_max',['../tune_system_buffer_cache.html#tuning_system_buffer_cache_os_cache_dirty_max',1,'']]],
  ['os_5fcache_5fmax_72',['os_cache_max',['../tune_system_buffer_cache.html#tuning_system_buffer_cache_os_cache_max',1,'']]],
  ['other_20components_73',['Interaction With Other Components',['../arch-prefetch.html#prefetch_other',1,'']]],
  ['other_20deleted_20pages_74',['Generation of other deleted pages',['../arch-fast-truncate.html#ft_deleted_generation',1,'']]],
  ['other_20notes_75',['Miscellaneous other notes',['../arch-fast-truncate.html#ft_misc',1,'']]],
  ['other_20operations_76',['Interaction With Other Operations',['../arch-btree.html#btree_truncate_interaction_with_other_operations',1,'']]],
  ['other_20resources_77',['Other Resources',['../tool-index.html#tool-other',1,'']]],
  ['outlier_20thresholds_78',['Getting a more precise control of the outlier thresholds',['../tool-optrack.html#autotoc_md37',1,'']]],
  ['output_79',['Examining the output',['../tool-perf.html#autotoc_md46',1,'']]],
  ['output_20format_20of_20the_20wt_5fevent_5fhandler_80',['Output format of the WT_EVENT_HANDLER',['../message_handling.html#message_handling_output',1,'']]],
  ['over_20b_20trees_81',['Iterating over B-Trees',['../arch-rts.html#iterating-over-b-trees',1,'']]],
  ['over_20pages_82',['Iterating over pages',['../arch-rts.html#iterating-over-pages',1,'']]],
  ['over_20updates_83',['Iterating over updates',['../arch-rts.html#iterating-over-updates',1,'']]],
  ['overhead_84',['Will operation tracking introduce runtime overhead?',['../tool-optrack.html#autotoc_md27',1,'']]],
  ['overview_85',['Overview',['../arch-backup.html#autotoc_md0',1,'Overview'],['../arch-checkpoint.html#autotoc_md5',1,'Overview'],['../arch-usage-patterns.html#slotted-arrays-overview',1,'Overview'],['../tool-libfuzzer.html#autotoc_md17',1,'Overview'],['../tool-optrack.html#autotoc_md24',1,'Overview'],['../tool-perf.html#autotoc_md42',1,'Overview']]],
  ['overview_86',['overview',['../durability_overview.html',1,'Durability overview'],['../eviction.html#eviction_overview',1,'Eviction overview'],['../timestamp_model.html',1,'Timestamp overview']]],
  ['overview_20and_20features_87',['WiredTiger Overview and Features',['../overview.html',1,'index']]],
  ['overview_20of_20encryption_20in_20wiredtiger_88',['Overview of Encryption in WiredTiger',['../encryption.html#encryption_overview',1,'']]],
  ['overview_20of_20rts_89',['Overview of RTS',['../arch-rts.html#rts-overview',1,'']]],
  ['overview_20of_20tiered_20storage_20in_20wiredtiger_90',['Overview of Tiered Storage in WiredTiger',['../custom_storage_sources.html#storage_overview',1,'']]]
];
