var NAVTREEINDEX7 =
{
"tune_page_size_and_comp.html#table_compress":[0,3,57,2,0],
"tune_read_only.html":[0,3,58],
"tune_statistics.html":[0,3,44],
"tune_system_buffer_cache.html":[0,3,59],
"tune_system_buffer_cache.html#tuning_system_buffer_cache_direct_io":[0,3,59,0],
"tune_system_buffer_cache.html#tuning_system_buffer_cache_os_cache_dirty_max":[0,3,59,1],
"tune_system_buffer_cache.html#tuning_system_buffer_cache_os_cache_max":[0,3,59,2],
"tune_transparent_huge_pages.html":[0,3,60],
"tune_zone_reclaim.html":[0,3,61],
"upgrade.html":[0,3,37],
"upgrading.html":[0,7],
"upgrading.html#version_1101":[0,7,0],
"verbose_messaging.html":[0,3,23],
"verbose_messaging.html#verbosity_categories":[0,3,23,1],
"verbose_messaging.html#verbosity_configuration":[0,3,23,1,0],
"verbose_messaging.html#verbosity_levels":[0,3,23,0],
"wtperf.html":[0,3,45],
"wtperf.html#config":[0,3,45,1],
"wtperf.html#monitor":[0,3,45,0]
};
