var index =
[
    [ "WiredTiger Overview and Features", "overview.html", [
      [ "Multi-core scaling", "overview.html#multi_core", null ],
      [ "Hot caches", "overview.html#cache", null ],
      [ "Making I/O more valuable", "overview.html#io", null ],
      [ "Production quality", "overview.html#quality", null ],
      [ "NoSQL and Open Source", "overview.html#nosql", null ]
    ] ],
    [ "Building and installing WiredTiger on POSIX (Linux, *BSD, OS X):", "build-posix.html", "build-posix" ],
    [ "Building and installing WiredTiger on Windows", "build-windows.html", [
      [ "Building using Git and GitHub", "build-windows.html#windows_github", null ],
      [ "Building on Windows", "build-windows.html#windows_building", null ],
      [ "Installing WiredTiger", "build-windows.html#windows_installing", null ],
      [ "Configuring WiredTiger", "build-windows.html#windows_configure", null ]
    ] ],
    [ "Writing WiredTiger applications", "programming.html", "programming" ],
    [ "WiredTiger command line utility", "command_line.html", "command_line" ],
    [ "Managing WiredTiger databases", "admin.html", "admin" ],
    [ "WiredTiger Change Log", "md_changelog.html", [
      [ "WiredTiger release 10.0.0, 2021-04-12", "md_changelog.html#autotoc_md5", null ],
      [ "WiredTiger release 3.2.1, 2019-08-27", "md_changelog.html#autotoc_md6", null ],
      [ "WiredTiger release 3.1.0, 2018-07-12", "md_changelog.html#autotoc_md7", null ],
      [ "WiredTiger release 3.0.0, 2018-01-08", "md_changelog.html#autotoc_md8", null ],
      [ "WiredTiger release 2.9.3, 2017-06-27", "md_changelog.html#autotoc_md9", null ],
      [ "WiredTiger release 2.9.2, 2017-05-25", "md_changelog.html#autotoc_md10", null ],
      [ "WiredTiger release 2.9.1, 2016-12-22", "md_changelog.html#autotoc_md11", null ],
      [ "WiredTiger release 2.9.0, 2016-09-06", "md_changelog.html#autotoc_md12", null ],
      [ "WiredTiger release 2.8.0, 2015-03-24", "md_changelog.html#autotoc_md13", null ],
      [ "WiredTiger release 2.7.0, 2015-12-08", "md_changelog.html#autotoc_md14", null ],
      [ "WiredTiger release 2.6.1, 2015-05-13", "md_changelog.html#autotoc_md15", null ],
      [ "WiredTiger release 2.6.0, 2015-05-13", "md_changelog.html#autotoc_md16", null ],
      [ "WiredTiger release 2.5.3, 2015-04-22", "md_changelog.html#autotoc_md17", null ],
      [ "WiredTiger release 2.5.2, 2015-03-23", "md_changelog.html#autotoc_md18", null ],
      [ "WiredTiger release 2.5.1, 2015-03-07", "md_changelog.html#autotoc_md19", null ],
      [ "WiredTiger release 2.5.0, 2014-12-24", "md_changelog.html#autotoc_md20", null ],
      [ "WiredTiger release 2.4.1, 2014-11-06", "md_changelog.html#autotoc_md21", null ],
      [ "WiredTiger release 2.4.0, 2014-10-15", "md_changelog.html#autotoc_md22", null ],
      [ "WiredTiger release 2.3.1, 2014-08-14", "md_changelog.html#autotoc_md23", null ],
      [ "WiredTiger release 2.3.0, 2014-07-29", "md_changelog.html#autotoc_md24", null ],
      [ "WiredTiger release 2.2.1, 2014-06-24", "md_changelog.html#autotoc_md25", null ],
      [ "WiredTiger release 2.2.0, 2014-05-21", "md_changelog.html#autotoc_md26", null ],
      [ "WiredTiger release 2.1.2, 2014-03-27", "md_changelog.html#autotoc_md27", null ],
      [ "WiredTiger release 2.1.1, 2014-03-04", "md_changelog.html#autotoc_md28", null ],
      [ "WiredTiger release 2.1.0, 2014-02-04", "md_changelog.html#autotoc_md29", null ],
      [ "WiredTiger release 2.0.1, 2013-12-12", "md_changelog.html#autotoc_md30", null ],
      [ "WiredTiger release 1.6.6, 2013-11-19", "md_changelog.html#autotoc_md31", null ],
      [ "WiredTiger release 1.6.5, 2013-10-09", "md_changelog.html#autotoc_md32", null ],
      [ "WiredTiger release 1.6.4, 2013-08-20", "md_changelog.html#autotoc_md33", null ],
      [ "WiredTiger release 1.6.3, 2013-07-12", "md_changelog.html#autotoc_md34", null ],
      [ "WiredTiger release 1.6.2, 2013-06-18", "md_changelog.html#autotoc_md35", null ],
      [ "WiredTiger release 1.6.1, 2013-05-31", "md_changelog.html#autotoc_md36", null ],
      [ "WiredTiger release 1.6.0, 2013-05-16", "md_changelog.html#autotoc_md37", null ],
      [ "WiredTiger release 1.5.3, 2013-04-26", "md_changelog.html#autotoc_md38", null ],
      [ "WiredTiger release 1.5.2, 2013-03-28", "md_changelog.html#autotoc_md39", null ],
      [ "WiredTiger release 1.5.1, 2013-03-25", "md_changelog.html#autotoc_md40", null ],
      [ "WiredTiger release 1.5.0, 2013-03-14", "md_changelog.html#autotoc_md41", null ],
      [ "WiredTiger release 1.4.2, 2013-01-14", "md_changelog.html#autotoc_md42", null ],
      [ "WiredTiger release 1.4.1, 2012-12-12", "md_changelog.html#autotoc_md43", null ],
      [ "WiredTiger release 1.4.0, 2012-12-03", "md_changelog.html#autotoc_md44", null ],
      [ "WiredTiger release 1.3.8, 2012-11-22", "md_changelog.html#autotoc_md45", null ],
      [ "WiredTiger release 1.3.7, 2012-11-09", "md_changelog.html#autotoc_md46", null ],
      [ "WiredTiger release 1.3.6, 2012-11-06", "md_changelog.html#autotoc_md47", null ],
      [ "WiredTiger release 1.3.5, 2012-10-26", "md_changelog.html#autotoc_md48", null ],
      [ "WiredTiger release 1.3.4, 2012-10-19", "md_changelog.html#autotoc_md49", null ],
      [ "WiredTiger release 1.3.3, 2012-10-11", "md_changelog.html#autotoc_md50", null ],
      [ "WiredTiger release 1.3.2, 2012-10-03", "md_changelog.html#autotoc_md51", null ],
      [ "WiredTiger release 1.3.1, 2012-09-25", "md_changelog.html#autotoc_md52", null ],
      [ "WiredTiger release 1.3.0, 2012-09-17", "md_changelog.html#autotoc_md53", null ],
      [ "WiredTiger release 1.2.2, 2012-06-20", "md_changelog.html#autotoc_md54", null ],
      [ "WiredTiger release 1.2.1, 2012-06-15", "md_changelog.html#autotoc_md55", null ],
      [ "WiredTiger release 1.2.0, 2012-06-04", "md_changelog.html#autotoc_md56", null ],
      [ "WiredTiger release 1.1.5, 2012-04-26", "md_changelog.html#autotoc_md57", null ],
      [ "WiredTiger release 1.1.4, 2012-04-16", "md_changelog.html#autotoc_md58", null ],
      [ "WiredTiger release 1.1.3, 2012-04-04", "md_changelog.html#autotoc_md59", null ],
      [ "WiredTiger release 1.1.2, 2012-03-20", "md_changelog.html#autotoc_md60", null ],
      [ "WiredTiger release 1.1.1, 2012-03-12", "md_changelog.html#autotoc_md61", null ],
      [ "WiredTiger release 1.1.0, 2012-02-28", "md_changelog.html#autotoc_md62", null ]
    ] ],
    [ "Upgrading WiredTiger applications", "upgrading.html", [
      [ "Upgrading to Version 10.0.0", "upgrading.html#version_1000", null ],
      [ "Upgrading to Version 3.2.1", "upgrading.html#version_321", null ],
      [ "Upgrading to Version 3.1.0", "upgrading.html#version_310", null ],
      [ "Upgrading to Version 3.0.0", "upgrading.html#version_300", null ],
      [ "Upgrading to Version 2.9.2", "upgrading.html#version_292", null ],
      [ "Upgrading to Version 2.9.1", "upgrading.html#version_291", null ],
      [ "Upgrading to Version 2.9.0", "upgrading.html#version_290", null ],
      [ "Upgrading to Version 2.8.0", "upgrading.html#version_280", null ],
      [ "Upgrading to Version 2.7.0", "upgrading.html#version_270", null ],
      [ "Upgrading to Version 2.6.1", "upgrading.html#version_261", null ],
      [ "Upgrading to Version 2.6.0", "upgrading.html#version_260", null ],
      [ "Upgrading to Version 2.5.3", "upgrading.html#version_253", null ],
      [ "Upgrading to Version 2.5.2", "upgrading.html#version_252", null ],
      [ "Upgrading to Version 2.5.1", "upgrading.html#version_251", null ],
      [ "Upgrading to Version 2.5.0", "upgrading.html#version_250", null ],
      [ "Upgrading to Version 2.4.1", "upgrading.html#version_241", null ],
      [ "Upgrading to Version 2.4.0", "upgrading.html#version_240", null ],
      [ "Upgrading to Version 2.3.1", "upgrading.html#version_231", null ],
      [ "Upgrading to Version 2.3.0", "upgrading.html#version_230", null ],
      [ "Upgrading to Version 2.2.1", "upgrading.html#version_221", null ],
      [ "Upgrading to Version 2.2.0", "upgrading.html#version_220", null ],
      [ "Upgrading to Version 2.1.2", "upgrading.html#version_212", null ],
      [ "Upgrading to Version 2.1.1", "upgrading.html#version_211", null ],
      [ "Upgrading to Version 2.1", "upgrading.html#version_21", null ],
      [ "Upgrading to Version 2.0", "upgrading.html#version_20", null ],
      [ "Upgrading to Version 1.6.6", "upgrading.html#version_166", null ],
      [ "Upgrading to Version 1.6.5", "upgrading.html#version_165", null ],
      [ "Upgrading to Version 1.6.4", "upgrading.html#version_164", null ],
      [ "Upgrading to Version 1.6.3", "upgrading.html#version_163", null ],
      [ "Upgrading to Version 1.6.2", "upgrading.html#version_162", null ],
      [ "Upgrading to Version 1.6.1", "upgrading.html#version_161", null ],
      [ "Upgrading to Version 1.6.0", "upgrading.html#version_160", null ],
      [ "Upgrading to Version 1.5.3", "upgrading.html#version_153", null ],
      [ "Upgrading to Version 1.4.3", "upgrading.html#version_143", null ],
      [ "Upgrading to Version 1.3.9", "upgrading.html#version_139", null ],
      [ "Upgrading to Version 1.3.8", "upgrading.html#version_138", null ],
      [ "Upgrading to Version 1.3.6", "upgrading.html#version_136", null ],
      [ "Upgrading to Version 1.3.5", "upgrading.html#version_135", null ],
      [ "Upgrading to Version 1.3", "upgrading.html#version_13", null ]
    ] ],
    [ "WiredTiger licensing", "license.html", [
      [ "3rd party software always included in the WiredTiger library", "license.html#license_library", null ],
      [ "3rd party software optionally included in the WiredTiger library: PPC64", "license.html#license_crc32-power8", null ],
      [ "3rd party software optionally included in the WiredTiger library: s390x", "license.html#license_crc32-zseries", null ],
      [ "3rd party software included in the WiredTiger distribution", "license.html#license_distribution", null ]
    ] ],
    [ "WiredTiger testing", "testing.html", [
      [ "Unit Test Suite", "testing.html#test_suite", [
        [ "Python", "testing.html#test_python", null ],
        [ "CSuite", "testing.html#test_csuite", null ],
        [ "CPPSuite", "testing.html#test_cppsuite", null ],
        [ "Format", "testing.html#test_format", null ],
        [ "WT Perf", "testing.html#test_perf", null ],
        [ "Workgen", "testing.html#test_workgen", null ]
      ] ],
      [ "Compatibility Testing", "testing.html#testing_compatibility", null ],
      [ "Correctness Testing", "testing.html#testing_correctness", null ],
      [ "Performance Testing", "testing.html#testing_performance", null ],
      [ "Stress Testing", "testing.html#testing_stress", null ],
      [ "Concurrency testing", "testing.html#testing_threads", null ],
      [ "Runtime correctness checking", "testing.html#testing_runtime", null ],
      [ "Static analysis", "testing.html#testing_static", null ],
      [ "Coverage", "testing.html#testing_coverage", [
        [ "Tests", "testing.html#coverage_tests", null ],
        [ "Tagging scheme", "testing.html#coverage_tags", null ],
        [ "Code", "testing.html#coverage_code", null ],
        [ "Cyclomatic Complexity", "testing.html#coverage_cyclomatic", null ]
      ] ]
    ] ],
    [ "Tools and Techniques", "tool-index.html", "tool-index" ],
    [ "WiredTiger Architecture Guide", "arch-index.html", "arch-index" ],
    [ "WiredTiger community and contact information", "community.html", null ]
];