.TH "include Directory Reference" 3 "Wed Apr 22 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwiredtiger\&.in\fP"
.br
.ti -1c
.RI "file \fBwiredtiger_ext\&.h\fP"
.br
.in -1c
