.TH "admin" 3 "Fri Dec 4 2015" "Version Version 2.7.0" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin \- Managing WiredTiger databases 
This section covers topics of interest for system administrators managing WiredTiger applications:
.PP
.IP "\(bu" 2
\fBDatabase Home Directory\fP
.IP "\(bu" 2
\fBDatabase Configuration\fP
.IP "\(bu" 2
\fBBackup from the command line\fP
.IP "\(bu" 2
\fBFilesystems\fP
.IP "\(bu" 2
\fBSecurity\fP 
.PP

