.TH "community" 3 "Wed Apr 22 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
community \- WiredTiger community and contact information 
MongoDB Inc\&. and the WiredTiger community maintain and develop \fC\fBWiredTiger on GitHub\fP\fP, and all contributors are welcome!
.PP
All source code and revision histories for this software are available in the \fC\fBWiredTiger source tree repository\fP\fP\&.
.PP
Please submit any feature suggestions and bug reports at \fC\fBWiredTiger's Issues page\fP\fP\&.
.PP
Discussion of WiredTiger issues and development can also be found in the \fC\fBWiredTiger Google Group\fP\fP\&.
.PP
To contact MongoDB, Inc\&. about WiredTiger, please send email to \fBinfo@wiredtiger.com\fP\&. 
