.TH "compact" 3 "Sat Jul 2 2016" "Version Version 2.8.1" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compact \- Compaction 
The \fBWT_SESSION::compact\fP method can be used to compact data sources\&.
.PP
The data source does not have to be quiescent, compaction may be performed on an active data source\&.
.PP
Because checkpoints named by the application are not discarded until explicitly removed or replaced, they may prevent \fBWT_SESSION::compact\fP from accomplishing anything\&. 
