.TH "compact_lang_java" 3 "Sat Jul 2 2016" "Version Version 2.8.1" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compact_lang_java \- Compaction in Java 
The Session\&.compact method can be used to compact data sources\&.
.PP
The data source does not have to be quiescent, compaction may be performed on an active data source\&.
.PP
Because checkpoints named by the application are not discarded until explicitly removed or replaced, they may prevent Session\&.compact from accomplishing anything\&. 
