.TH "cursor_random" 3 "Fri Dec 4 2015" "Version Version 2.7.0" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cursor_random \- Cursor random 
The \fCnext_random\fP configuration to the \fBWT_SESSION::open_cursor\fP method configures the cursor to return a pseudo-random record from a row-store object (the configuration is not supported on other types of objects)\&. 
