.TH "cursor_random_lang_java" 3 "Fri Dec 4 2015" "Version Version 2.7.0" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cursor_random_lang_java \- Cursor random in Java 
The \fCnext_random\fP configuration to the Session\&.open_cursor method configures the cursor to return a pseudo-random record from a row-store object (the configuration is not supported on other types of objects)\&. 
