.TH "home" 3 "Wed Apr 22 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
home \- Database Home Directory 
WiredTiger file naming is based on the \fChome\fP argument specified to the \fBwiredtiger_open\fP function and the \fCWIREDTIGER_HOME\fP environment variable, determined by the following steps:
.PP
.IP "1." 4
If a \fChome\fP argument is specified to the \fBwiredtiger_open\fP function, its value is used as the database directory\&.
.IP "2." 4
If the \fCWIREDTIGER_HOME\fP environment variable is not set, the database directory is the process' current working directory\&. No current working directory path is maintained by the WiredTiger software and changing the working directory after opening the WiredTiger database may cause failure\&.
.IP "3." 4
If the process is running with special privileges, the \fBwiredtiger_open\fP function must be configured with the \fCuse_environment_priv\fP flag\&. The \fCuse_environment_priv\fP flag is intended for applications that have or acquire special privileges and wish to use an environment-specified home directory: if such an application does not configure the \fBwiredtiger_open\fP function with the \fCuse_environment_priv\fP flag, setting an environment value will cause the open to fail\&. On ISO/IEC 9945-1:1990 (POSIX\&.1) systems, 'special privileges' is defined as a real user ID not equal to the effective user ID, or the real group ID not equal to the effective group ID\&.
.IP "4." 4
Otherwise, the value of the \fCWIREDTIGER_HOME\fP environment variable is used as the database directory\&.
.PP
.PP
Finally, consider security when configuring WiredTiger to use the \fCWIREDTIGER_HOME\fP environment variable, especially in applications which run with permissions other than the user's\&. Such applications are potentially vulnerable to allowing users access to databases they could not otherwise access\&. 
