.TH "license" 3 "Fri Dec 4 2015" "Version Version 2.7.0" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
license \- WiredTiger licensing 
The complete WiredTiger software package is Open Source software: you are welcome to modify and redistribute it under the terms of \fC\fBversion 2\fP\fP or \fC\fBversion 3\fP\fP of the \fBGNU General Public License\fP as published by the Free Software Foundation\&. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the \fBGNU General Public License\fP for details\&.
.PP
For a license to use the WiredTiger software under conditions other than those described above, or for technical support for this software, please contact MongoDB, Inc\&. at info@wiredtiger.com\&.
.SH "3rd party software included in the WiredTiger library"
.PP
Every build of the WiredTiger library binary includes the following 3rd party software, distributed under their license terms\&. Redistribution of the WiredTiger library should comply with these copyrights\&.
.PP
Distribution FilesCopyright HolderLicense \fCsrc/include/bitstring\&.i\fP University of California, Berkeley\fCBSD-3-Clause License\fP \fCsrc/include/queue\&.h\fP University of California, Berkeley\fCBSD-3-Clause License\fP \fCsrc/os_posix/getopt\&.c\fP University of California, Berkeley\fCBSD-3-Clause License\fP \fCsrc/support/hash_city\&.c\fP Google, Inc\&.\fCThe MIT License\fP \fCsrc/support/hash_fnv\&.c\fP AuthorsPublic Domain 
.SH "3rd party software optionally included in the WiredTiger library: LevelDB"
.PP
If the \fC--enable-leveldb\fP configuration option is specified when configuring the WiredTiger build, additional 3rd party software is included in the WiredTiger LevelDB library binary, distributed under their license terms\&. Redistribution of the WiredTiger library built with the \fC--enable-leveldb\fP configuration option should comply with these copyrights\&.
.PP
Distribution FilesCopyright HolderLicense \fCapi/leveldb/basho/*\fP Basho Technologies, Inc\&.\fCApache License, Version 2\&.0\fP \fCapi/leveldb/hyperleveldb/*\fP The HyperLevelDB Authors\fCBSD-3-Clause License\fP \fCapi/leveldb/leveldb/*\fP Google, Inc\&.\fCBSD-3-Clause License\fP \fCapi/leveldb/rocksdb/*\fP Facebook, Inc\&.\fCBSD-3-Clause License\fP 
.SH "3rd party software included in the WiredTiger distribution"
.PP
The WiredTiger software distribution includes additional 3rd party software licensed under a variety of licenses\&. \fBThis software is NOT included in the WiredTiger library binary as built by the distribution\&.\fP This software is used for peripheral tasks, such as building the WiredTiger documentation, testing the WiredTiger software or graphically displaying WiredTiger run-time output\&. If you extract portions of the WiredTiger software distribution for inclusion in other packages, or redistribute selected portions of the WiredTiger sources, please review the copyright notices and LICENSE files included in the WiredTiger distribution for the terms and conditions of such redistribution\&.
.SH "Public domain software"
.PP
Many portions of the WiredTiger distribution are public domain software\&. Public domain files have notices releasing the software into the public domain and may be freely used and redistributed\&. 
