.TH "namespace_lang_java" 3 "Sat Jul 2 2016" "Version Version 2.8.1" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
namespace_lang_java \- Name spaces in Java 

.SH "Process' environment name space"
.PP
WiredTiger's environment variables begin with the string 'WIREDTIGER'\&.
.SH "Java language name space"
.PP
WiredTiger's public classes are in the \fCcom\&.wiredtiger\&.db\fP package\&.
.PP
The \fCcom\&.wiredtiger\&.db\&.wiredtiger\fP class contains static methods and inherited constants\&.
.SH "File system name space"
.PP
WiredTiger's files begin with the string 'WiredTiger'; applications should not create files in the WiredTiger file system name space\&. 
