.TH "programming_lang_java" 3 "Wed Apr 22 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
programming_lang_java \- Writing WiredTiger applications in Java 
This section covers topics of interest for programmers writing WiredTiger applications in Java\&.
.PP
We follow SQL terminology: a database is set of tables managed together\&. Tables consist of rows, where each row is a key and its associated value\&. Tables may optionally have an associated schema, splitting the value into a set of columns\&. Tables may also have associated indices, each of which is ordered by one or more columns\&.
.PP
.SS "Using the API"
.PP
.IP "\(bu" 2
\fBGetting Started with the API in Java\fP
.IP "\(bu" 2
\fBConfiguration Strings in Java\fP
.IP "\(bu" 2
\fBCursors in Java\fP
.IP "\(bu" 2
\fBTransactions in Java\fP
.IP "\(bu" 2
\fBError handling in Java\fP
.PP
.PP
.SS "Storage options"
.PP
.IP "\(bu" 2
\fBSchema, Columns, Column Groups, Indices and Projections in Java\fP
.IP "\(bu" 2
\fBLog-Structured Merge Trees in Java\fP
.IP "\(bu" 2
\fBFile formats and compression in Java\fP
.IP "\(bu" 2
\fBCompressors in Java\fP
.PP
.PP
.SS "Programming notes"
.PP
.IP "\(bu" 2
\fBMultithreading in Java\fP
.IP "\(bu" 2
\fBName spaces in Java\fP
.PP
.PP
.SS "Advanced topics"
.PP
.IP "\(bu" 2
\fBAsynchronous operations in Java\fP
.IP "\(bu" 2
\fBBackups in Java\fP
.IP "\(bu" 2
\fBCheckpoint durability in Java\fP
.IP "\(bu" 2
\fBCompaction in Java\fP
.IP "\(bu" 2
\fBLog cursors in Java\fP
.IP "\(bu" 2
\fBCommit-level durability in Java\fP
.IP "\(bu" 2
\fBPer-process shared caches in Java\fP
.IP "\(bu" 2
\fBStatistics in Java\fP
.IP "\(bu" 2
\fBUpgrading and downgrading databases\fP
.PP
.PP
.SS "Performance monitoring and tuning"
.PP
.IP "\(bu" 2
\fBPerformance monitoring with statistics\fP
.IP "\(bu" 2
\fBSimulating workloads with wtperf\fP
.IP "\(bu" 2
\fBVisualizing performance with wtstats\fP 
.PP
.PP
.IP "\(bu" 2
\fBMemory allocator\fP
.IP "\(bu" 2
\fBPage and overflow key/value sizes\fP
.IP "\(bu" 2
\fBCache and eviction tuning\fP
.IP "\(bu" 2
\fBBulk-load\fP
.IP "\(bu" 2
\fBCursor persistence\fP
.IP "\(bu" 2
\fBRead-only objects\fP
.IP "\(bu" 2
\fBCommit-level durability\fP
.IP "\(bu" 2
\fBChecksums\fP
.IP "\(bu" 2
\fBCompression\fP
.IP "\(bu" 2
\fBFile allocation\fP
.IP "\(bu" 2
\fBSystem buffer cache\fP
.IP "\(bu" 2
\fBLinux transparent huge pages\fP
.IP "\(bu" 2
\fBConnection close\fP
.IP "\(bu" 2
\fBMutexes\fP
.IP "\(bu" 2
\fBLinux zone reclamation memory management\fP 
.PP

