.TH "tune_transparent_huge_pages" 3 "Wed Apr 22 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tune_transparent_huge_pages \- Linux transparent huge pages 
The performance of WiredTiger applications can be adversely affected when transparent huge pages are enabled on Linux systems\&. Some Linux systems enable transparent huge pages by default\&. See the RedHat Enterprise Linux system documentation's \fCHuge Pages and Transparent Huge Pages\fP for more information\&.
.PP
To disable transparent huge pages run the following command as the root user:
.PP
.PP
.nf
echo never > /sys/kernel/mm/transparent_hugepage/enabled
.fi
.PP
 
