.TH "WiredTiger Java API" 3 "Sat Apr 11 2015" "Version Version 2.5.3" "WiredTiger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WiredTiger Java API \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.wiredtiger\&.db\&.AsyncOp\fP"
.br
.RI "\fIA \fBWT_ASYNC_OP\fP handle is the interface to an asynchronous operation\&. \fP"
.ti -1c
.RI "class \fBcom\&.wiredtiger\&.db\&.Connection\fP"
.br
.RI "\fIA connection to a WiredTiger database\&. \fP"
.ti -1c
.RI "class \fBcom\&.wiredtiger\&.db\&.Cursor\fP"
.br
.RI "\fIA \fBWT_CURSOR\fP handle is the interface to a cursor\&. \fP"
.ti -1c
.RI "class \fBcom\&.wiredtiger\&.db\&.Session\fP"
.br
.RI "\fIAll data operations are performed in the context of a \fBWT_SESSION\fP\&. \fP"
.ti -1c
.RI "class \fBcom\&.wiredtiger\&.db\&.wiredtiger\fP"
.br
.ti -1c
.RI "interface \fBcom\&.wiredtiger\&.db\&.wiredtigerConstants\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Java wrappers around the WiredTiger C API\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for WiredTiger from the source code\&.
